icedb: icedb::Databases::Database_impl Class Reference
icedb::Databases::Database_impl Class Reference
#include <Database_impl.hpp>
Public Member Functions
Database_impl ()
Database_impl (size_t virtualMemSizeInBytes)
virtual ~Database_impl ()
Groups::Group::Group_ptr openGroup (const std::string &path) override
Groups::Group::Group_ptr createGroup (const std::string &path) override
Groups::Group::Group_ptr createGroupStructure (const std::string &groupName) override
Groups::Group::Group_ptr createGroupStructure (const std::vector< std::string > &groupNames) override
Public Member Functions inherited from icedb::Databases::Database
virtual ~Database ()
Static Private Member Functions
static std::shared_ptr< H5::H5File > makeDatabaseFileStandard (const std::string &p)
Private Attributes
std::shared_ptr< H5::H5File > hFile
file_image hFileImage
Used if a virtual base is needed (the typical case)
Friends
class Database
Additional Inherited Members
Public Types inherited from icedb::Databases::Database
typedef std::unique_ptr< Database > Database_ptr
Static Public Member Functions inherited from icedb::Databases::Database
static Database_ptr createSampleDatabase (const std::string &location)
static Database_ptr createSingleFileDatabase (const std::string &location)
static Database_ptr openDatabase (const std::string &location, fs::IOopenFlags flags=fs::IOopenFlags::READ_ONLY)
static Database_ptr openVirtualDatabase (size_t memSizeInBytes)
static void indexDatabase (const std::string &location)
Protected Member Functions inherited from icedb::Databases::Database
Database ()
Detailed Description
Definition at line 19 of file Database_impl.hpp.
Constructor & Destructor Documentation
Database_impl() [1/2]
icedb::Databases::Database_impl::Database_impl ()
Definition at line 56 of file databases.cpp.
                                      : hFileImage(fs::impl::getUniqueVROOTname(), 10 * 1024 * 1024)
         { }
Database_impl() [2/2]
icedb::Databases::Database_impl::Database_impl (size_t virtualMemSizeInBytes)
Definition at line 59 of file databases.cpp.
                                                                  : hFileImage(fs::impl::getUniqueVROOTname(), virtualMemSizeInBytes)
         { }
~Database_impl()
icedb::Databases::Database_impl::~Database_impl () virtual
Definition at line 62 of file databases.cpp.
 {}
Member Function Documentation
createGroup()
Groups::Group::Group_ptr icedb::Databases::Database_impl::createGroup (const std::string & path) override virtual
Implements icedb::Databases::Database.
Definition at line 48 of file databases.cpp.
References icedb::Groups::Group::createGroup(), and icedb::Databases::file_image::hFile.
{
             return Groups::Group::createGroup(path, hFile.get());
         }
createGroupStructure() [1/2]
Groups::Group::Group_ptr icedb::Databases::Database_impl::createGroupStructure (const std::string & groupName) override virtual
Implements icedb::Databases::Database.
Definition at line 193 of file databases.cpp.
References icedb::fs::hdf5::createGroupStructure(), hFile, and icedb::Groups::Group::openGroup().
         {
             H5::Group grp = icedb::fs::hdf5::createGroupStructure(groupName, *(hFile.get()));
             std::shared_ptr<H5::Group> ngrp = std::make_shared<H5::Group>(grp);
             return Groups::Group::openGroup(ngrp);
         }
createGroupStructure() [2/2]
Groups::Group::Group_ptr icedb::Databases::Database_impl::createGroupStructure (const std::vector< std::string > & groupNames) override virtual
Implements icedb::Databases::Database.
Definition at line 199 of file databases.cpp.
References icedb::fs::hdf5::createGroupStructure(), hFile, and icedb::Groups::Group::openGroup().
         {
             H5::Group grp = icedb::fs::hdf5::createGroupStructure(groupNames, *(hFile.get()));
             std::shared_ptr<H5::Group> ngrp = std::make_shared<H5::Group>(grp);
             return Groups::Group::openGroup(ngrp);
         }
makeDatabaseFileStandard()
std::shared_ptr< H5::H5File > icedb::Databases::Database_impl::makeDatabaseFileStandard (const std::string & p) static private
Definition at line 34 of file databases.cpp.
References basegrp, icedb::fs::hdf5::getHDF5IOflags(), and icedb::fs::TRUNCATE.
Referenced by icedb::Databases::Database::createSampleDatabase(), icedb::Databases::Database::createSingleFileDatabase(), and icedb::Databases::Database::indexDatabase().
{
                 auto res = std::make_shared<H5::H5File>(p,
                     fs::hdf5::getHDF5IOflags(fs::IOopenFlags::TRUNCATE),
                     H5P_DEFAULT);
                 constexpr uint64_t dbverno = 1;
                 auto basegrp = res->openGroup("."); //->getHDF5Group();
                 icedb::fs::hdf5::addAttr<uint64_t, H5::Group>(&basegrp, "Version", dbverno);
                 icedb::fs::hdf5::addAttr<std::string, H5::Group>(&basegrp, "Software", "libicedb");
                 //icedb::fs::hdf5::addAttr<uint64_t, H5::H5File>(res.get(), "Version", dbverno);
                 //icedb::fs::hdf5::addAttr<std::string, H5::H5File>(res.get(), "Software", "libicedb");
                 return res;
             }
openGroup()
Groups::Group::Group_ptr icedb::Databases::Database_impl::openGroup (const std::string & path) override virtual
Implements icedb::Databases::Database.
Definition at line 52 of file databases.cpp.
References icedb::Databases::file_image::hFile, and icedb::Groups::Group::openGroup().
{
             return Groups::Group::openGroup(path, hFile.get());
         }
Friends And Related Function Documentation
Database
friend class Database friend
Definition at line 20 of file Database_impl.hpp.
Member Data Documentation
hFile
std::shared_ptr<H5::H5File> icedb::Databases::Database_impl::hFile private
Definition at line 21 of file Database_impl.hpp.
Referenced by createGroupStructure().
hFileImage
file_image icedb::Databases::Database_impl::hFileImage private
Used if a virtual base is needed (the typical case)
Definition at line 22 of file Database_impl.hpp.
The documentation for this class was generated from the following files:
lib/private/Database_impl.hpp
lib/src/databases.cpp