icedb: icedb::Databases::Database Class Reference
icedb::Databases::Database Class Reference abstract
#include <Database.hpp>
Public Types
typedef std::unique_ptr< Database > Database_ptr
Public Member Functions
virtual ~Database ()
virtual Groups::Group::Group_ptr openGroup (const std::string &path)=0
virtual Groups::Group::Group_ptr createGroup (const std::string &path)=0
virtual Groups::Group::Group_ptr createGroupStructure (const std::string &groupName)=0
virtual Groups::Group::Group_ptr createGroupStructure (const std::vector< std::string > &groupNames)=0
Static Public Member Functions
static Database_ptr createSampleDatabase (const std::string &location)
static Database_ptr createSingleFileDatabase (const std::string &location)
static Database_ptr openDatabase (const std::string &location, fs::IOopenFlags flags=fs::IOopenFlags::READ_ONLY)
static Database_ptr openVirtualDatabase (size_t memSizeInBytes)
static void indexDatabase (const std::string &location)
Protected Member Functions
Database ()
Detailed Description
Definition at line 16 of file Database.hpp.
Member Typedef Documentation
Database_ptr
typedef std::unique_ptr<Database> icedb::Databases::Database::Database_ptr
Definition at line 20 of file Database.hpp.
Constructor & Destructor Documentation
Database()
icedb::Databases::Database::Database () protected
Definition at line 66 of file databases.cpp.
 {}
~Database()
icedb::Databases::Database::~Database () virtual
Definition at line 64 of file databases.cpp.
 {}
Member Function Documentation
createGroup()
virtual Groups::Group::Group_ptr icedb::Databases::Database::createGroup (const std::string & path) pure virtual
Implemented in icedb::Databases::Database_impl.
createGroupStructure() [1/2]
virtual Groups::Group::Group_ptr icedb::Databases::Database::createGroupStructure (const std::string & groupName) pure virtual
Implemented in icedb::Databases::Database_impl.
createGroupStructure() [2/2]
virtual Groups::Group::Group_ptr icedb::Databases::Database::createGroupStructure (const std::vector< std::string > & groupNames) pure virtual
Implemented in icedb::Databases::Database_impl.
createSampleDatabase()
Database::Database_ptr icedb::Databases::Database::createSampleDatabase (const std::string & location) static
Definition at line 68 of file databases.cpp.
References icedb::fs::hdf5::getHDF5IOflags(), icedb::Databases::Database_impl::makeDatabaseFileStandard(), openDatabase(), icedb::fs::READ_WRITE, and icedb::fs::TRUNCATE.
Referenced by main().
         {
             const auto flag_truncate = fs::hdf5::getHDF5IOflags(fs::IOopenFlags::TRUNCATE);
             sfs::path pBase(location);
             sfs::create_directories(pBase);
             Expects(sfs::exists(pBase));
             sfs::create_directory(pBase / "3d_Structures");
             sfs::create_directory(pBase / "Physical_Particle_Properties");
             sfs::create_directory(pBase / "Extended_Scattering_Variables");
             sfs::create_directory(pBase / "Essential_Scattering_Variables");
             sfs::create_directory(pBase / "Testing");
             Database_impl::makeDatabaseFileStandard((pBase / "3d_Structures" / "3dS-1.hdf5").string());
             Database_impl::makeDatabaseFileStandard((pBase / "3d_Structures" / "3dS-2.hdf5").string());
             Database_impl::makeDatabaseFileStandard((pBase / "3d_Structures" / "3dS-3.hdf5").string());
             Database_impl::makeDatabaseFileStandard((pBase / "Physical_Particle_Properties" / "ppp.hdf5").string());
             Database_impl::makeDatabaseFileStandard((pBase / "Essential_Scattering_Variables" / "esv1.hdf5").string());
             Database_impl::makeDatabaseFileStandard((pBase / "Essential_Scattering_Variables" / "esv2.hdf5").string());
             Database_impl::makeDatabaseFileStandard((pBase / "Testing" / "scratch.hdf5").string());
             Database_impl::makeDatabaseFileStandard((pBase / "metadata.hdf5").string());
             return (openDatabase(location, icedb::fs::IOopenFlags::READ_WRITE));
         }
createSingleFileDatabase()
Database::Database_ptr icedb::Databases::Database::createSingleFileDatabase (const std::string & location) static
Definition at line 95 of file databases.cpp.
References icedb::fs::hdf5::getHDF5IOflags(), icedb::Databases::Database_impl::makeDatabaseFileStandard(), openDatabase(), icedb::fs::READ_WRITE, and icedb::fs::TRUNCATE.
Referenced by openDatabase().
{
             const auto flag_truncate = fs::hdf5::getHDF5IOflags(fs::IOopenFlags::TRUNCATE);
             //sfs::path pBase(location);
             //sfs::create_directories(pBase);
             //Expects(sfs::exists(pBase));
             Database_impl::makeDatabaseFileStandard(location);
             return (openDatabase(location, icedb::fs::IOopenFlags::READ_WRITE));
         }
indexDatabase()
void icedb::Databases::Database::indexDatabase (const std::string & location) static
Todo:
createGroupStructure cannot currently handle passing back an H5File (in the no groups case). It is a bug in HDF5. Once fixed, the if-else cases should be collapsed into one.
Definition at line 161 of file databases.cpp.
References icedb::fs::impl::collectActualHDF5files(), icedb::fs::hdf5::createGroupStructure(), icedb::fs::hdf5::explodeHDF5groupPath(), icedb::Databases::Database_impl::makeDatabaseFileStandard(), and icedb::fs::impl::resolveSymlinkPathandForceExists().
Referenced by main().
         {
             sfs::path pBaseS = fs::impl::resolveSymlinkPathandForceExists(location);
             fs::impl::CollectedFilesRet_Type mountFiles = fs::impl::collectActualHDF5files(pBaseS);
             Expects(mountFiles.size() > 0);
             if (mountFiles.size() == 1) return;
             std::unique_ptr<Database_impl> res = std::make_unique<Database_impl>();
             res->hFile = Database_impl::makeDatabaseFileStandard(location + "/index.hdf5");
             // Check for the existence of the appropriate groups in the relative path tree
             // Create any missing groups in the relative path tree, and then make the link.
             for (const auto &toMount : mountFiles) {
                 std::string mountStr = toMount.second;
                 if (mountStr == "index.hdf5") continue;
                 auto explodedPath = fs::hdf5::explodeHDF5groupPath(mountStr);
                 std::string linkName = *(explodedPath.rbegin());
                 explodedPath.pop_back();
                 if (explodedPath.size()) {
                     auto grp = fs::hdf5::createGroupStructure(explodedPath, *(res->hFile.get()));
                     H5Lcreate_external(toMount.second.c_str(), "/", grp.getLocId(), linkName.c_str(), H5P_DEFAULT, H5P_DEFAULT);
                 } else {
                     H5Lcreate_external(toMount.second.c_str(), "/", res->hFile->getLocId(), linkName.c_str(), H5P_DEFAULT, H5P_DEFAULT);
                 }
             }
         }
openDatabase()
Database::Database_ptr icedb::Databases::Database::openDatabase (const std::string & location, fs::IOopenFlags flags = fs::IOopenFlags::READ_ONLY) static
Note
HDF5 C++ bug in constness on 1.8.5, CentOS 6. I cannot directly pass H5P_DEFAULT to the trivial constructor for H5::PropList as an rvalue
Definition at line 118 of file databases.cpp.
References icedb::fs::impl::collectActualHDF5files(), icedb::fs::CREATE, icedb::fs::hdf5::createGroupStructure(), createSingleFileDatabase(), icedb::fs::hdf5::getHDF5IOflags(), icedb::fs::impl::resolveSymLinks(), and icedb::fs::TRUNCATE.
Referenced by createSampleDatabase(), createSingleFileDatabase(), and main().
         {
             sfs::path pBaseS = fs::impl::resolveSymLinks(location);
             if (!sfs::exists(pBaseS)) {
                 if (flags == fs::IOopenFlags::TRUNCATE || flags == fs::IOopenFlags::CREATE) {
                     return createSingleFileDatabase(location);
                 } else throw(std::invalid_argument("Attempting to open a database root that does not exist. Did you mean to first create this database?"));
             }
             fs::impl::CollectedFilesRet_Type mountFiles = fs::impl::collectActualHDF5files(pBaseS);
             unsigned int Hflags = fs::hdf5::getHDF5IOflags(flags);
             auto res = std::make_unique<Database_impl>();
             //std::unique_ptr<Database_impl, mem::icedb_delete<Database_impl> > res(new Database_impl);
                 //= std::make_unique(<Database_impl, mem::icedb_delete<Database_impl> >();
             Expects(mountFiles.size() > 0);
             if (mountFiles.size() == 1) {
                 res->hFile = std::make_shared<H5::H5File>(
                     mountFiles.begin()->first.string().c_str(), Hflags, H5P_DEFAULT);
             }
             else {
                 res->hFile = res->hFileImage.getHFile();
                 // Check for the existence of the appropriate groups in the relative path tree
                 // Create any missing groups in the relative path tree
                 for (const auto &toMount : mountFiles) {
                     std::string mountStr = toMount.second;
                     if (mountStr == "index.hdf5") continue;
                     H5::Group grp = icedb::fs::hdf5::createGroupStructure(mountStr, *(res->hFile.get()));
                     // Open files and mount in the relative path tree
                     std::shared_ptr<H5::H5File> newHfile = std::make_shared<H5::H5File>(toMount.first.string(), Hflags);
                     //res._impl->mappedFiles[toMount.second] = newHfile;
                     H5::PropList pl(H5P_DEFAULT);
                     res->hFile->mount(toMount.second, *(newHfile.get()), pl);
                 }
             }
             return std::move(res);
         }
openGroup()
virtual Groups::Group::Group_ptr icedb::Databases::Database::openGroup (const std::string & path) pure virtual
Implemented in icedb::Databases::Database_impl.
openVirtualDatabase()
Database::Database_ptr icedb::Databases::Database::openVirtualDatabase (size_t memSizeInBytes) static
Definition at line 107 of file databases.cpp.
         {
             auto res = std::make_unique<Database_impl>();
             //std::unique_ptr<Database_impl, mem::icedb_delete<Database_impl> > res(new Database_impl);
             //= std::make_unique(<Database_impl, mem::icedb_delete<Database_impl> >();
             res->hFile = res->hFileImage.getHFile();
             return std::move(res);
         }
The documentation for this class was generated from the following files:
lib/icedb/Database.hpp
lib/src/databases.cpp