icedb: icedb::Groups::Group_impl Class Reference
icedb::Groups::Group_impl Class Reference
#include <Group_impl.hpp>
Public Member Functions
Group_impl ()
Group_impl (const std::string &name, gsl::not_null< H5::Group *> parent)
Group_impl (const std::string &name, gsl::not_null< H5::H5File *> parent)
Group_impl (const std::string &name, gsl::not_null< const Group *> parent)
Group_impl (Group_HDF_shared_ptr grp)
virtual ~Group_impl ()
Group_ptr createGroup (const std::string &groupName) override
Create a group.
Group_ptr openGroup (const std::string &groupName) const override
Opens a group.
bool doesGroupExist (const std::string &groupName) const override
Does a group with this name exist?
std::set< std::string > getGroupNames () const override
void deleteGroup (const std::string &groupName) override
Unlink the specified child group.
Group_HDF_shared_ptr getHDF5Group () const override
Get the fundamental HDF5 object that the group is built on.
Public Member Functions inherited from icedb::Groups::Group
virtual ~Group ()
Public Member Functions inherited from icedb::Attributes::CanHaveAttributes
~CanHaveAttributes ()
bool doesAttributeExist (const std::string &attributeName) const
Does the object have an attribute with the given name?
std::type_index getAttributeTypeId (const std::string &attributeName) const
Returns the type of an attribute.
template<class Type >
bool isAttributeOfType (const std::string &attributeName) const
Is the type of the attribute "Type"?
std::set< std::string > getAttributeNames () const
List all attributes attached to this object.
void deleteAttribute (const std::string &attributeName)
Delete an attribute, by name, that is attached to this object.
template<class DataType >
void readAttributeData (const std::string &attributeName, std::vector< size_t > &dimensions, std::vector< DataType > &data) const
Function to read the data from an attribute using the provided input vectors.
template<class DataType >
void writeAttributeData (const std::string &attributeName, const std::vector< size_t > &dimensionas, const std::vector< DataType > &data)
Function to write an attribute to an object, with the provided raw data.
template<class DataType >
Attribute< DataType > readAttribute (const std::string &attributeName) const
Convenience function to read an attribute's data and return an Attribute object.
template<class DataType >
void writeAttribute (const Attribute< DataType > &attribute)
Convenience function to write an Attribute to an object.
template<class DataType >
void writeAttribute (const std::string &name, std::initializer_list< size_t > dims, std::initializer_list< DataType > data)
Convenience function to write a small Attribute to an object, using initializer lists.
Public Member Functions inherited from icedb::Tables::CanHaveTables
~CanHaveTables ()
std::set< std::string > getTableNames () const
Lists all table names that are children of this object.
bool doesTableExist (const std::string &tableName) const
Does a table exist with the given name.
void unlinkTable (const std::string &tableName)
Unlink a table. In HDF5, this is not the same as erasing a table, which never actually happens.
Table::Table_Type openTable (const std::string &tableName)
std::vector< size_t > getChunkStrategy (const std::vector< size_t > &dims)
The default chunking strategy for this table. Used for storage i/o speed, and for compression.
template<class DataType >
Table::Table_Type createTable (const std::string &tableName, const std::vector< size_t > &dims, const std::vector< size_t > *chunks=nullptr)
Create a table.
template<class DataType >
Table::Table_Type createTable (const std::string &tableName, std::initializer_list< size_t > dims, const std::vector< size_t > *chunks=nullptr)
Create a table.
template<class DataType >
Table::Table_Type createTable (const std::string &tableName, std::initializer_list< size_t > dims, std::initializer_list< DataType > data, const std::vector< size_t > *chunks=nullptr)
Create a table and writes initial data. Used with small tables.
template<class DataType >
Table::Table_Type createTable (const std::string &tableName, std::initializer_list< size_t > dims, const std::vector< DataType > &data, const std::vector< size_t > *chunks=nullptr)
Create a table and sets the table's initial data.
template<class DataType >
Table::Table_Type createTable (const std::string &tableName, std::initializer_list< size_t > dims, const gsl::span< DataType > &data, const std::vector< size_t > *chunks=nullptr)
Create a table and sets the table's initial data.
template<class DataType >
Table::Table_Type createTable (const std::string &tableName, std::initializer_list< size_t > dims, const gsl::span< const DataType > &data, const std::vector< size_t > *chunks=nullptr)
Create a table and sets the table's initial data.
Public Member Functions inherited from icedb::Attributes::CanHaveAttributes_impl
CanHaveAttributes_impl (std::shared_ptr< H5::H5Object >)
CanHaveAttributes_impl ()
virtual ~CanHaveAttributes_impl ()
Public Member Functions inherited from icedb::Tables::CanHaveTables_impl
virtual ~CanHaveTables_impl ()
CanHaveTables_impl ()
Private Attributes
Group_HDF_shared_ptr grp
Friends
class Group
Additional Inherited Members
Public Types inherited from icedb::Groups::Group
typedef std::unique_ptr< Groups::Group > Group_ptr
typedef std::shared_ptr< H5::Group > Group_HDF_shared_ptr
Static Public Member Functions inherited from icedb::Groups::Group
static Group_ptr createGroup (const std::string &name, gsl::not_null< H5::Group *> parent)
Create a group with a specified parent (static function)
static Group_ptr createGroup (const std::string &name, gsl::not_null< H5::H5File *> parent)
Create a group with a specified parent (static function)
static Group_ptr createGroup (const std::string &name, gsl::not_null< const Group *> parent)
Create a group with a specified parent (static function)
static Group_ptr openGroup (const std::string &name, gsl::not_null< H5::Group *> parent)
Open a group under the specified parent (static function)
static Group_ptr openGroup (const std::string &name, gsl::not_null< H5::H5File *> parent)
Open a group under the specified parent (static function)
static Group_ptr openGroup (const std::string &name, gsl::not_null< const Group *> parent)
Open a group under the specified parent (static function)
static Group_ptr openGroup (Group_HDF_shared_ptr group)
Open an icedb group from an HDF5 group object.
static Group_ptr mount (const std::string &subdirname, gsl::not_null< const Group *> containingParent, gsl::not_null< H5::H5File *> pointsTo)
Mount an HDF5 file as a child 'group'.
Static Public Member Functions inherited from icedb::Attributes::CanHaveAttributes
static bool doesAttributeExist (gsl::not_null< const H5::H5Object *> parent, const std::string &attributeName)
Does an object (parent) have an attribute with the given name?
static std::type_index getAttributeTypeId (gsl::not_null< const H5::H5Object *> parent, const std::string &attributeName)
Returns the type of an attribute.
template<class DataType >
static void readAttributeData (gsl::not_null< const H5::H5Object *> parent, const std::string &attributeName, std::vector< size_t > &dimensions, std::vector< DataType > &data)
Function to read the data from an attribute.
template<class DataType >
static Attribute< DataType > readAttribute (gsl::not_null< const H5::H5Object *> obj, const std::string &attributeName)
Convenience function to read an attribute's data and return an Attribute object.
Public Attributes inherited from icedb::Groups::Group
const std::string name
The name of the group.
Static Public Attributes inherited from icedb::Groups::Group
static const std::string _icedb_obj_type_identifier = { "_icedb_obj_type" }
The tag used in icedb to identify a group.
Protected Member Functions inherited from icedb::Groups::Group
Group ()
Group (const std::string &name)
Protected Member Functions inherited from icedb::Attributes::CanHaveAttributes
CanHaveAttributes ()
Protected Member Functions inherited from icedb::Tables::CanHaveTables
CanHaveTables ()
Trivial constructor used when CanHaveTables is a virtual base class.
Protected Member Functions inherited from icedb::Attributes::CanHaveAttributes_impl
virtual void _setAttributeParent (std::shared_ptr< H5::H5Object > obj) override
virtual std::shared_ptr< H5::H5Object > _getAttributeParent () const override
Protected Member Functions inherited from icedb::Tables::CanHaveTables_impl
void _setTablesParent (std::shared_ptr< H5::Group > obj) override
CanHaveTables needs post-constructor setup. This sets the base HDF5 object that gets manipulated.
std::shared_ptr< H5::Group > _getTablesParent () const override
Gets the base HDF5 object that is manipulated.
Detailed Description
Definition at line 14 of file Group_impl.hpp.
Constructor & Destructor Documentation
Group_impl() [1/5]
icedb::Groups::Group_impl::Group_impl ()
Definition at line 11 of file Groups.cpp.
References icedb::Groups::Group::_icedb_obj_type_identifier.
 : Group() {}
Group_impl() [2/5]
icedb::Groups::Group_impl::Group_impl (const std::string & name, gsl::not_null< H5::Group *> parent)
Definition at line 19 of file Groups.cpp.
References icedb::Attributes::CanHaveAttributes_impl::_setAttributeParent(), icedb::Tables::CanHaveTables_impl::_setTablesParent(), grp, icedb::Groups::Group::name, icedb::fs::hdf5::openGroup(), and icedb::Attributes::CanHaveAttributes_impl::parent.
             : Group{ name }
         {
             auto ugrp = fs::hdf5::openGroup(parent.get(), name.c_str());
             //grp = std::shared_ptr<H5::Group>(ugrp.release());
             grp = std::shared_ptr<H5::Group>(ugrp.release()); // , mem::icedb_delete<H5::Group>());
             this->_setAttributeParent(grp);
             this->_setTablesParent(grp);
         }
Group_impl() [3/5]
icedb::Groups::Group_impl::Group_impl (const std::string & name, gsl::not_null< H5::H5File *> parent)
Definition at line 28 of file Groups.cpp.
References icedb::Attributes::CanHaveAttributes_impl::_setAttributeParent(), icedb::Tables::CanHaveTables_impl::_setTablesParent(), grp, icedb::Groups::Group::name, icedb::fs::hdf5::openGroup(), and icedb::Attributes::CanHaveAttributes_impl::parent.
             : Group{ name }
         {
             auto ugrp = fs::hdf5::openGroup(parent.get(), name.c_str());
             //grp = std::shared_ptr<H5::Group>(ugrp.release());
             grp = std::shared_ptr<H5::Group>(ugrp.release()); // , mem::icedb_delete<H5::Group>());
             this->_setAttributeParent(grp);
             this->_setTablesParent(grp);
         }
Group_impl() [4/5]
icedb::Groups::Group_impl::Group_impl (const std::string & name, gsl::not_null< const Group *> parent)
Definition at line 39 of file Groups.cpp.
References icedb::Attributes::CanHaveAttributes_impl::_setAttributeParent(), icedb::Tables::CanHaveTables_impl::_setTablesParent(), grp, icedb::Groups::Group::name, icedb::fs::hdf5::openGroup(), and icedb::Attributes::CanHaveAttributes_impl::parent.
             : Group{ name }
         {
             auto ugrp = fs::hdf5::openGroup(parent->getHDF5Group().get(), name.c_str());
             //grp = std::shared_ptr<H5::Group>(ugrp.release());
             grp = std::shared_ptr<H5::Group>(ugrp.release()); // , mem::icedb_delete<H5::Group>());
             this->_setAttributeParent(grp);
             this->_setTablesParent(grp);
         }
Group_impl() [5/5]
icedb::Groups::Group_impl::Group_impl (Group_HDF_shared_ptr grp)
Definition at line 49 of file Groups.cpp.
References icedb::Attributes::CanHaveAttributes_impl::_setAttributeParent(), icedb::Tables::CanHaveTables_impl::_setTablesParent(), and grp.
             : Group( "UNKNOWN" )
         {
             this->grp = grp;
             this->_setAttributeParent(grp);
             this->_setTablesParent(grp);
         }
~Group_impl()
icedb::Groups::Group_impl::~Group_impl () virtual
Definition at line 17 of file Groups.cpp.
 {}
Member Function Documentation
createGroup()
Group::Group_ptr icedb::Groups::Group_impl::createGroup (const std::string & groupName) override virtual
Create a group.
Parameters
groupName is the new group's name
Exceptions
if read-only
if a group with htis name already exists
Returns
a pointer to the new group
Implements icedb::Groups::Group.
Definition at line 61 of file Groups.cpp.
References icedb::Groups::Group::createGroup(), and grp.
{
             return std::move(Group::createGroup(groupName, this->grp.get()));
         }
deleteGroup()
void icedb::Groups::Group_impl::deleteGroup (const std::string & groupName) override virtual
Unlink the specified child group.
Parameters
groupName is the name of the group to be unlinked
Exceptions
if groupName is invalid
if a group with name groupName does not exist
Implements icedb::Groups::Group.
Definition at line 138 of file Groups.cpp.
References grp.
{
             grp->unlink(groupName);
         }
doesGroupExist()
bool icedb::Groups::Group_impl::doesGroupExist (const std::string & groupName) const override virtual
Does a group with this name exist?
Returns
true if it exists, false otherwise
Parameters
groupName is the name of the group
Exceptions
if groupName is somehow invalid
Implements icedb::Groups::Group.
Definition at line 142 of file Groups.cpp.
References getGroupNames().
{
             auto gnames = getGroupNames();
             if (gnames.count(groupName)) return true;
             return false;
         }
getGroupNames()
std::set< std::string > icedb::Groups::Group_impl::getGroupNames () const override virtual
Note
This shared pointer gets a custom deallocator. TODO: Add deallocator for strings.
Implements icedb::Groups::Group.
Definition at line 148 of file Groups.cpp.
References icedb::fs::hdf5::getGroupMembersTypes(), and grp.
Referenced by doesGroupExist().
{
             auto objs = fs::hdf5::getGroupMembersTypes(*(grp.get()));
             std::set<std::string> res;
             for (const auto &o : objs)
             {
                 if (o.second == H5G_obj_t::H5G_GROUP) res.insert(o.first);
             }
             return res;
         }
getHDF5Group()
std::shared_ptr< H5::Group > icedb::Groups::Group_impl::getHDF5Group () const override virtual
Get the fundamental HDF5 object that the group is built on.
Implements icedb::Groups::Group.
Definition at line 57 of file Groups.cpp.
References grp.
{
             return grp;
         }
openGroup()
Group::Group_ptr icedb::Groups::Group_impl::openGroup (const std::string & groupName) const override virtual
Opens a group.
Parameters
groupName is the name of the group to be opened
Exceptions
if the group does not exist
Returns
a pointer to the newly-opened group
Implements icedb::Groups::Group.
Definition at line 107 of file Groups.cpp.
References grp, icedb::Groups::Group::name, icedb::Groups::Group::openGroup(), and icedb::Attributes::CanHaveAttributes_impl::parent.
Referenced by icedb::Groups::Group::mount().
{
             return std::make_unique<Group_impl>(groupName, grp.get());
             //return std::move(Group::Group_ptr(new Group_impl(groupName, grp.get())));
         }
Friends And Related Function Documentation
Group
friend class Group friend
Definition at line 19 of file Group_impl.hpp.
Member Data Documentation
grp
Group_HDF_shared_ptr icedb::Groups::Group_impl::grp private
Note
This shared pointer has a custom deallocator, to ensure that it is freed in the correct module.
Definition at line 17 of file Group_impl.hpp.
Referenced by createGroup(), deleteGroup(), getGroupNames(), getHDF5Group(), Group_impl(), openGroup(), and icedb::Shapes::Shape_impl::Shape_impl().
The documentation for this class was generated from the following files:
lib/private/Group_impl.hpp
lib/src/Groups.cpp