icedb: icedb::registry::options Class Reference
icedb::registry::options Class Reference
#include <options.hpp>
Public Member Functions
virtual ~options ()
void enumVals (std::ostream &out) const
bool hasVal (const std::string &key) const
template<class T >
T getVal (const std::string &key) const
Retrieves an option. Throws if nonexistant.
template<class T >
T getVal (const std::string &key, const T &defaultval) const
Retrieves an option. Returns defaultval if nonexistant.
template<class T >
options_ptr setVal (const std::string &key, const T &value)
Adds or replaces an option.
template<class T >
options_ptr add (const std::string &key, const T &value)
Adds an option. Throws if the same name already exists.
void filename (const std::string &val)
std::string filename () const
void extension (const std::string &val)
std::string extension () const
void filetype (const std::string &val)
std::string filetype () const
void exportType (const std::string &val)
std::string exportType () const
Static Public Member Functions
static std::shared_ptr< options > generate ()
Protected Member Functions
options ()
Protected Attributes
std::shared_ptr< options_inner > p
Detailed Description
Definition at line 10 of file options.hpp.
Constructor & Destructor Documentation
options()
icedb::registry::options::options () protected
Definition at line 15 of file options.cpp.
{
             p = std::shared_ptr<options_inner>(new options_inner);
         }
~options()
icedb::registry::options::~options () virtual
Definition at line 21 of file options.cpp.
 {}
Member Function Documentation
add()
template<class T > options_ptr icedb::registry::options::add (const std::string & key, const T & value)
Adds an option. Throws if the same name already exists.
Definition at line 59 of file options.cpp.
References ICEDB_throw, and icedb::error::xKeyExists.
         {
             if (hasVal(key)) ICEDB_throw(::icedb::error::error_types::xKeyExists)
                 .add<std::string>("key", key)
                 .add<T>("newValue", value);
             return this->setVal<T>(key, value);
         }
enumVals()
void icedb::registry::options::enumVals (std::ostream & out) const
Definition at line 22 of file options.cpp.
{
             //out << "\tName\t\tValue" << std::endl;
             for (const auto &v : p->_mapStr)
             {
                 if (v.first != "password")
                 {
                     out << "\t" << v.first << ":\t" << v.second << std::endl;
                 }
                 else {
                     out << "\t" << v.first << ":\t" << "********" << std::endl;
                 }
             }
         }
exportType() [1/2]
void icedb::registry::options::exportType (const std::string & val) inline
Definition at line 36 of file options.hpp.
 { setVal<std::string>("exportType", val); }
exportType() [2/2]
std::string icedb::registry::options::exportType () const inline
Definition at line 37 of file options.hpp.
 { return getVal<std::string>("exportType", ""); }
extension() [1/2]
void icedb::registry::options::extension (const std::string & val) inline
Definition at line 32 of file options.hpp.
 { setVal<std::string>("extension", val); }
extension() [2/2]
std::string icedb::registry::options::extension () const inline
Definition at line 33 of file options.hpp.
 { return getVal<std::string>("extension", ""); }
filename() [1/2]
void icedb::registry::options::filename (const std::string & val) inline
Definition at line 30 of file options.hpp.
 { setVal<std::string>("filename", val); }
filename() [2/2]
std::string icedb::registry::options::filename () const inline
Definition at line 31 of file options.hpp.
 { return getVal<std::string>("filename", ""); }
filetype() [1/2]
void icedb::registry::options::filetype (const std::string & val) inline
Definition at line 34 of file options.hpp.
 { setVal<std::string>("filetype", val); }
filetype() [2/2]
std::string icedb::registry::options::filetype () const inline
Definition at line 35 of file options.hpp.
 { return getVal<std::string>("filetype", ""); }
generate()
std::shared_ptr< options > icedb::registry::options::generate () static
Definition at line 18 of file options.cpp.
Referenced by icedb::units::converter::canConvert(), icedb::units::conv_spec::conv_spec(), icedb::units::converter::getConverter(), and icedb::error::xError::push().
{
             auto res = std::shared_ptr<options>(new options); return res;
         }
getVal() [1/2]
template<class T > T icedb::registry::options::getVal (const std::string & key) const
Retrieves an option. Throws if nonexistant.
Definition at line 39 of file options.cpp.
         {
             if (!hasVal(key)) return boost::lexical_cast<T>(std::string(""));
             //RDthrow(Ryan_Debug::ICEDB_LOG_ERROR::xMissingKey())
             //  << Ryan_Debug::ICEDB_LOG_ERROR::key(key);
             std::string valS = p->_mapStr.at(key);
             T res = boost::lexical_cast<T>(valS);
             return res;
         }
getVal() [2/2]
template<class T > T icedb::registry::options::getVal (const std::string & key, const T & defaultval) const
Retrieves an option. Returns defaultval if nonexistant.
Definition at line 48 of file options.cpp.
         {
             if (!hasVal(key)) return defaultval;
             return getVal<T>(key);
         }
hasVal()
bool icedb::registry::options::hasVal (const std::string & key) const
Definition at line 35 of file options.cpp.
{
             if (p->_mapStr.count(key)) return true;
             return false;
         }
setVal()
template<class T > options_ptr icedb::registry::options::setVal (const std::string & key, const T & value)
Adds or replaces an option.
Definition at line 53 of file options.cpp.
         {
             std::string valS = boost::lexical_cast<std::string>(value);
             p->_mapStr[key] = valS;
             return this->shared_from_this();
         }
Member Data Documentation
p
std::shared_ptr<options_inner> icedb::registry::options::p protected
Definition at line 14 of file options.hpp.
The documentation for this class was generated from the following files:
lib/private/options.hpp
lib/src/options.cpp