icedb: icedb::splitSet::intervals< T > Class Template Reference
icedb::splitSet::intervals< T > Class Template Reference
Class to define and search on intervals.
#include <splitSet.hpp>
Public Member Functions
intervals (const std::string &s="")
intervals (const std::vector< std::string > &s)
~intervals ()
void append (const std::string &instr, const std::map< std::string, std::string > *aliases=nullptr)
void append (const std::vector< std::string > &s, const std::map< std::string, std::string > *aliases=nullptr)
void append (const intervals< T > &src)
bool inRange (const T &val) const
bool isNear (const T &val, const T &linSep, const T &factorSep) const
Public Attributes
std::vector< std::pair< T, T > > ranges
Detailed Description
template<class T>
class icedb::splitSet::intervals< T >
Class to define and search on intervals.
This is a simple class used for searching based on user input. It does not provide interval unions, intersections, etc. It can, however, aid in setting these up, such as for a database query.
Accepts standard paramSet notation, but also adds the '-' range operator, implying that values may be found in a certain range.
Definition at line 67 of file splitSet.hpp.
Constructor & Destructor Documentation
intervals() [1/2]
template<class T > icedb::splitSet::intervals< T >::intervals (const std::string & s = "")
Definition at line 429 of file splitSet.cpp.
 { if (s.size()) append(s); }
intervals() [2/2]
template<class T > icedb::splitSet::intervals< T >::intervals (const std::vector< std::string > & s)
Definition at line 432 of file splitSet.cpp.
 { append(s); }
~intervals()
template<class T > icedb::splitSet::intervals< T >::~intervals ()
Definition at line 435 of file splitSet.cpp.
 {}
Member Function Documentation
append() [1/3]
template<class T > void icedb::splitSet::intervals< T >::append (const std::string & instr, const std::map< std::string, std::string > * aliases = nullptr)
Definition at line 438 of file splitSet.cpp.
References icedb::splitSet::extractInterval(), icedb::splitSet::splitSet(), and icedb::splitSet::splitVector().
         {
             std::vector<std::string> splits;
             splitVector(instr, splits, ',');
             std::set<T> vals;
             for (const auto &s : splits)
             {
                 std::map<std::string, std::string> defaliases;
                 if (!aliases) aliases = &defaliases; // Provides a convenient default
                 if (aliases->count(s))
                 {
                     std::string ssubst = aliases->at(s);
                     // Recursively call splitSet to handle bundles of aliases
                     append(ssubst, aliases);
                 }
                 else {
                     T start, end, interval;
                     size_t n;
                     std::string specializer;
                     bool isRange = false;
                     extractInterval(s, start, end, interval, n, specializer);
                     if (specializer == "range")
                     {
                         ranges.push_back(std::pair<T, T>(start, end));
                     } else if (start == end) {
                         ranges.push_back(std::pair<T, T>(start, end));
                     } else {
                         splitSet(start, end, interval, specializer, vals);
                     }
                 }
             }
             for (const auto &v : vals)
             {
                 ranges.push_back(std::pair<T, T>(v, v));
             }
         }
append() [2/3]
template<class T > void icedb::splitSet::intervals< T >::append (const std::vector< std::string > & s, const std::map< std::string, std::string > * aliases = nullptr)
Definition at line 478 of file splitSet.cpp.
         {
             for (const auto &str : s) append(str, aliases);
         }
append() [3/3]
template<class T > void icedb::splitSet::intervals< T >::append (const intervals< T > & src)
Definition at line 485 of file splitSet.cpp.
References icedb::splitSet::intervals< T >::ranges.
         {
             ranges.insert(ranges.end(), src.ranges.begin(), src.ranges.end());
         }
inRange()
template<class T > bool icedb::splitSet::intervals< T >::inRange (const T & val) const
Definition at line 490 of file splitSet.cpp.
         {
             for (const auto &r : ranges)
             {
                 if (val >= r.first && val < r.second) return true;
                 if (r.first == r.second) {
                     if (val == r.first) return true;
                 }
             }
             return false;
         }
isNear()
template<class T > bool icedb::splitSet::intervals< T >::isNear (const T & val, const T & linSep, const T & factorSep) const
Definition at line 502 of file splitSet.cpp.
         {
             for (const auto &r : ranges)
             {
                 T lower = (r.first * (static_cast<T>(1) - factorSep)) - linSep,
                     upper = (r.second * (static_cast<T>(1) + factorSep)) + linSep;
                 if (val >= lower && val < upper) return true;
             }
             return false;
         }
Member Data Documentation
ranges
template<class T> std::vector<std::pair<T, T> > icedb::splitSet::intervals< T >::ranges
Definition at line 70 of file splitSet.hpp.
Referenced by icedb::splitSet::intervals< T >::append().
The documentation for this class was generated from the following files:
lib/icedb/splitSet.hpp
lib/src/splitSet.cpp