icedb: icedb::units::conv_spec Class Reference
icedb::units::conv_spec Class Reference
Perform interconversions between frequency, wavelength and wavenumber (GHz, Hz, m, cm, um, cm^-1, m^-1)
#include <units.hpp>
Public Member Functions
conv_spec (const std::string &inUnits, const std::string &outUnits)
Public Member Functions inherited from icedb::units::converter
virtual ~converter ()
virtual double convert (double inVal) const
bool isValid () const
Is this conversion valid?
converter (const std::string &inUnits, const std::string &outUnits)
Static Public Member Functions
static std::shared_ptr< const converter > generate (const std::string &inUnits, const std::string &outUnits)
Static Public Member Functions inherited from icedb::units::converter
static bool canConvert (const std::string &inUnits, const std::string &outUnits)
Check if two units can be interconverted.
static std::shared_ptr< const converter > generate (const std::string &inUnits, const std::string &outUnits)
Additional Inherited Members
Protected Member Functions inherited from icedb::units::converter
converter ()
Static Protected Member Functions inherited from icedb::units::converter
static Unithandler_p getConverter (const std::string &inUnits, const std::string &outUnits)
Protected Attributes inherited from icedb::units::converter
Unithandler_p h
Detailed Description
Perform interconversions between frequency, wavelength and wavenumber (GHz, Hz, m, cm, um, cm^-1, m^-1)
Definition at line 56 of file units.hpp.
Constructor & Destructor Documentation
conv_spec()
icedb::units::conv_spec::conv_spec (const std::string & in, const std::string & out)
This works by providing a custom converter
Definition at line 64 of file units.cpp.
References icedb::units::implementations::_init(), icedb::units::implementations::spectralUnits::constructConverter(), icedb::registry::options::generate(), icedb::units::converter::h, ICEDB_log, and icedb::logging::ICEDB_LOG_DEBUG_2.
Referenced by generate().
             : converter()
         {
             implementations::_init(); // Static function that registers the builtin unit converters.
             ICEDB_log("units", icedb::logging::ICEDB_LOG_DEBUG_2,
                 "Creating spectrum converter for " << in << " to " << out);
             auto opts = registry::options::generate();
             opts->setVal<std::string>("inUnits", in);
             opts->setVal<std::string>("outUnits", out);
             h = implementations::spectralUnits::constructConverter(opts);
         }
Member Function Documentation
generate()
std::shared_ptr< const converter > icedb::units::conv_spec::generate (const std::string & inUnits, const std::string & outUnits) static
Definition at line 77 of file units.cpp.
References icedb::units::implementations::_queryBackend(), icedb::units::implementations::_registerBackend(), and conv_spec().
Referenced by icedb::refract::prepRefract().
{
             converter_p res;
             res = implementations::_queryBackend(inUnits, outUnits, "spec");
             if (!res) {
                 res = converter_p(new conv_spec(inUnits, outUnits));
                 implementations::_registerBackend(inUnits, outUnits, "spec", res);
             }
             return res;
         }
The documentation for this class was generated from the following files:
lib/icedb/units/units.hpp
lib/src/units.cpp