icedb: icedb::units::converter Class Reference
icedb::units::converter Class Reference
Base conversion class.
#include <units.hpp>
Public Member Functions
virtual ~converter ()
virtual double convert (double inVal) const
bool isValid () const
Is this conversion valid?
converter (const std::string &inUnits, const std::string &outUnits)
Static Public Member Functions
static bool canConvert (const std::string &inUnits, const std::string &outUnits)
Check if two units can be interconverted.
static std::shared_ptr< const converter > generate (const std::string &inUnits, const std::string &outUnits)
Protected Member Functions
converter ()
Static Protected Member Functions
static Unithandler_p getConverter (const std::string &inUnits, const std::string &outUnits)
Protected Attributes
Unithandler_p h
Friends
struct implementations::spectralUnits
struct implementations::simpleUnits
struct implementations::Unithandler
Detailed Description
Base conversion class.
Class is virtual. May be overridden with classes that do formulaic operations, such as converters to density in ppmv.
Now, with the appropriate DLL loaded, the udunits system will be used for most conversions. The derived classes still have a bit of code for when udunits is not installed.
Definition at line 26 of file units.hpp.
Constructor & Destructor Documentation
~converter()
icedb::units::converter::~converter () virtual
Definition at line 61 of file units.cpp.
 {}
converter() [1/2]
icedb::units::converter::converter (const std::string & inUnits, const std::string & outUnits)
Definition at line 23 of file units.cpp.
References getConverter(), and h.
         {
             h = getConverter(inUnits, outUnits);
         }
converter() [2/2]
icedb::units::converter::converter () protected
Definition at line 11 of file units.cpp.
References icedb::units::implementations::_init().
Referenced by generate().
 { implementations::_init(); }
Member Function Documentation
canConvert()
bool icedb::units::converter::canConvert (const std::string & inUnits, const std::string & outUnits) static
Check if two units can be interconverted.
Definition at line 28 of file units.cpp.
References icedb::units::implementations::_init(), icedb::registry::options::generate(), and icedb::units::implementations::getHooks().
Referenced by icedb::units::implementations::spectralUnits::canConvert(), and icedb::units::implementations::spectralUnits::constructConverter().
{
             implementations::_init(); // Static function that registers the builtin unit converters.
             //SDBR_log("units", scatdb::logging::ICEDB_LOG_NORMAL,
             //  "Creating converter for " << inUnits << " to " << outUnits);
             auto hooks = implementations::getHooks();
             //  hull_provider_registry, hull_provider<convexHull> >::getHooks();
             //std::cerr << hooks->size() << std::endl;
             auto opts = registry::options::generate();
             opts->setVal<std::string>("inUnits", inUnits);
             opts->setVal<std::string>("outUnits", outUnits);
             for (const auto &i : *(hooks.get()))
             {
                 if (!i->canConvert) continue;
                 if (!i->constructConverter) continue;
                 if (!i->canConvert(opts)) continue;
                 return true;
             }
             return false;
         }
convert()
double icedb::units::converter::convert (double inVal) const virtual
Convert to the output units
Exceptions
If the conversion is invalid
Definition at line 52 of file units.cpp.
References h, ICEDB_throw, isValid(), icedb::error::xBadInput, and icedb::error::xNullPointer.
Referenced by icedb::refract::implementations::mIceWarren().
{
             if (!h)
                 ICEDB_throw(icedb::error::error_types::xNullPointer)
                     .add<std::string>("Reason", "Converter handler is null. Probably incompatible units.");
             if (!isValid())
                 ICEDB_throw(icedb::error::error_types::xBadInput)
                 .add<std::string>("Reason", "Conversion between the two specified units is invalid.");
             return h->convert(in);
         }
generate()
std::shared_ptr< const converter > icedb::units::converter::generate (const std::string & inUnits, const std::string & outUnits) static
Create a converter to convert between two types of units.
Returns
nullptr if no valid converter can be created for these units.
Definition at line 13 of file units.cpp.
References icedb::units::implementations::_queryBackend(), icedb::units::implementations::_registerBackend(), and converter().
Referenced by icedb::refract::prepRefract().
{
             converter_p res;
             res = implementations::_queryBackend(inUnits, outUnits, "");
             if (!res) {
                 res = converter_p(new converter(inUnits, outUnits));
                 implementations::_registerBackend(inUnits, outUnits, "", res);
             }
             return res;
         }
getConverter()
std::shared_ptr< const implementations::Unithandler > icedb::units::converter::getConverter (const std::string & inUnits, const std::string & outUnits) static protected
Get a converter for these units.
Returns
nullptr if no valid converter can be created
Definition at line 69 of file unitsPlugins.cpp.
References icedb::units::implementations::_init(), icedb::registry::options::generate(), icedb::units::implementations::getHooks(), ICEDB_log, and icedb::logging::ICEDB_LOG_DEBUG_1.
Referenced by icedb::units::implementations::spectralUnits::constructConverter(), and converter().
{
             implementations::_init(); // Static function that registers the builtin unit converters.
             const auto &hooks = implementations::getHooks();
             //  hull_provider_registry, hull_provider<convexHull> >::getHooks();
             //std::cerr << hooks->size() << std::endl;
             auto opts = registry::options::generate();
             opts->setVal<std::string>("inUnits", inUnits);
             opts->setVal<std::string>("outUnits", outUnits);
             for (const auto &i : *(hooks.get()))
             {
                 if (!i->canConvert) continue;
                 if (!i->constructConverter) continue;
                 if (!i->canConvert(opts)) continue;
                 return i->constructConverter(opts);
             }
             // Only return nullptr if unable to find a usable hook.
             ICEDB_log("units", icedb::logging::ICEDB_LOG_DEBUG_1, "No handler for unit conversion found for "
                 "conversions between " << inUnits << " and " << outUnits << ".");
             // We don;t want to throw an error here. Only throw if a conversion is actually attempted.
             // Otherwise, we quash the purpose of isValid().
             //ICEDB_throw(icedb::error::error_types::xBadInput)
             //  .add<std::string>("Reason", "There is no code which can handle this unit conversion.")
             //  .add<std::string>("inUnits", inUnits)
             //  .add<std::string>("outUnits", outUnits)
             //  ;
             return nullptr;
         }
isValid()
bool icedb::units::converter::isValid () const
Is this conversion valid?
Definition at line 48 of file units.cpp.
References h.
Referenced by convert(), and main().
{
             if (h) return h->isValid();
             return false;
         }
Friends And Related Function Documentation
implementations::simpleUnits
friend struct implementations::simpleUnits friend
Definition at line 50 of file units.hpp.
implementations::spectralUnits
friend struct implementations::spectralUnits friend
Definition at line 49 of file units.hpp.
implementations::Unithandler
friend struct implementations::Unithandler friend
Definition at line 51 of file units.hpp.
Member Data Documentation
h
Unithandler_p icedb::units::converter::h protected
Definition at line 48 of file units.hpp.
Referenced by icedb::units::conv_spec::conv_spec(), convert(), converter(), and isValid().
The documentation for this class was generated from the following files:
lib/icedb/units/units.hpp
lib/src/units.cpp
lib/src/unitsPlugins.cpp