icedb: icedb::error::xError Class Reference
icedb::error::xError Class Reference
#include <error.hpp>
Public Member Functions
xError (error_types=error_types::xOtherError)
virtual ~xError ()
virtual const char * what () const noexcept
xError & push (::icedb::registry::options_ptr)
Insert a context of Errors.
xError & push ()
template<class T >
xError & add (const std::string &key, const T value)
template<>
DL_ICEDB xError & add (const std::string &key, char const *const value)
Protected Attributes
std::shared_ptr< error_options_inner > ep
Detailed Description
xError is the base class for icedb C++ exceptions. C code should use the C interface.
Definition at line 17 of file error.hpp.
Constructor & Destructor Documentation
xError()
icedb::error::xError::xError (error::error_types xe = error_types::xOtherError)
Definition at line 237 of file error.cpp.
{
             ep = std::shared_ptr<error_options_inner>(new error_options_inner);
             ep->et = xe;
         }
~xError()
icedb::error::xError::~xError () virtual
Definition at line 241 of file error.cpp.
 {}
Member Function Documentation
add() [1/2]
template<class T > xError & icedb::error::xError::add (const std::string & key, const T value)
Definition at line 271 of file error.cpp.
Referenced by icedb::Examples::Shapes::readDataset().
         {
             if (!ep->cur) push();
             this->ep->cur->add<T>(key, value);
             return *this;
         }
add() [2/2]
template<> DL_ICEDB xError& icedb::error::xError::add (const std::string & key, char const *const value)
Definition at line 284 of file error.cpp.
         {
             if (!ep->cur) push();
             this->ep->cur->add<std::string>(key, std::string(value));
             return *this;
         }
push() [1/2]
xError & icedb::error::xError::push (::icedb::registry::options_ptr op)
Insert a context of Errors.
Definition at line 257 of file error.cpp.
         {
             ep->stk.push_back(op);
             ep->cur = op;
             return *this;
         }
push() [2/2]
xError & icedb::error::xError::push ()
Definition at line 263 of file error.cpp.
References icedb::registry::options::generate().
         {
             ::icedb::registry::options_ptr op = ::icedb::registry::options::generate();
             ep->stk.push_back(op);
             ep->cur = op;
             return *this;
         }
what()
const char * icedb::error::xError::what () const virtual noexcept
Definition at line 242 of file error.cpp.
References icedb::error::stringify().
{
             //static const char* msg = "An unknown error has occurred.";
             //return msg;
             std::ostringstream o;
             o << "error: " << stringify(ep->et) << std::endl;
             // Pull from stack
             int i = 1;
             for (const auto &e : ep->stk) {
                 o << "Throw frame " << i << std::endl;
                 e->enumVals(o);
                 ++i;
             }
             ep->emessage = o.str();
             return ep->emessage.c_str();
         }
Member Data Documentation
ep
std::shared_ptr<error_options_inner> icedb::error::xError::ep protected
Definition at line 20 of file error.hpp.
The documentation for this class was generated from the following files:
lib/icedb/error.hpp
lib/src/error.cpp