icedb: icedb::Attributes::CanHaveAttributes Class Reference
icedb::Attributes::CanHaveAttributes Class Reference abstract
This is a virtual base class for objects that can have attributes. This includes tables, groups and HDF5 files.
#include <Attribute.hpp>
Public Member Functions
~CanHaveAttributes ()
bool doesAttributeExist (const std::string &attributeName) const
Does the object have an attribute with the given name?
std::type_index getAttributeTypeId (const std::string &attributeName) const
Returns the type of an attribute.
template<class Type >
bool isAttributeOfType (const std::string &attributeName) const
Is the type of the attribute "Type"?
std::set< std::string > getAttributeNames () const
List all attributes attached to this object.
void deleteAttribute (const std::string &attributeName)
Delete an attribute, by name, that is attached to this object.
template<class DataType >
void readAttributeData (const std::string &attributeName, std::vector< size_t > &dimensions, std::vector< DataType > &data) const
Function to read the data from an attribute using the provided input vectors.
template<class DataType >
void writeAttributeData (const std::string &attributeName, const std::vector< size_t > &dimensionas, const std::vector< DataType > &data)
Function to write an attribute to an object, with the provided raw data.
template<class DataType >
Attribute< DataType > readAttribute (const std::string &attributeName) const
Convenience function to read an attribute's data and return an Attribute object.
template<class DataType >
void writeAttribute (const Attribute< DataType > &attribute)
Convenience function to write an Attribute to an object.
template<class DataType >
void writeAttribute (const std::string &name, std::initializer_list< size_t > dims, std::initializer_list< DataType > data)
Convenience function to write a small Attribute to an object, using initializer lists.
Static Public Member Functions
static bool doesAttributeExist (gsl::not_null< const H5::H5Object *> parent, const std::string &attributeName)
Does an object (parent) have an attribute with the given name?
static std::type_index getAttributeTypeId (gsl::not_null< const H5::H5Object *> parent, const std::string &attributeName)
Returns the type of an attribute.
template<class DataType >
static void readAttributeData (gsl::not_null< const H5::H5Object *> parent, const std::string &attributeName, std::vector< size_t > &dimensions, std::vector< DataType > &data)
Function to read the data from an attribute.
template<class DataType >
static Attribute< DataType > readAttribute (gsl::not_null< const H5::H5Object *> obj, const std::string &attributeName)
Convenience function to read an attribute's data and return an Attribute object.
Protected Member Functions
CanHaveAttributes ()
virtual void _setAttributeParent (std::shared_ptr< H5::H5Object > obj)=0
virtual std::shared_ptr< H5::H5Object > _getAttributeParent () const =0
Private Member Functions
bool valid () const
Detailed Description
This is a virtual base class for objects that can have attributes. This includes tables, groups and HDF5 files.
Definition at line 61 of file Attribute.hpp.
Constructor & Destructor Documentation
CanHaveAttributes()
icedb::Attributes::CanHaveAttributes::CanHaveAttributes () protected
Definition at line 11 of file Attributes.cpp.
 {}
~CanHaveAttributes()
icedb::Attributes::CanHaveAttributes::~CanHaveAttributes ()
Definition at line 12 of file Attributes.cpp.
 {}
Member Function Documentation
_getAttributeParent()
virtual std::shared_ptr<H5::H5Object> icedb::Attributes::CanHaveAttributes::_getAttributeParent () const protected pure virtual
Implemented in icedb::Attributes::CanHaveAttributes_impl.
_setAttributeParent()
virtual void icedb::Attributes::CanHaveAttributes::_setAttributeParent (std::shared_ptr< H5::H5Object > obj) protected pure virtual
Implemented in icedb::Attributes::CanHaveAttributes_impl.
deleteAttribute()
void icedb::Attributes::CanHaveAttributes::deleteAttribute (const std::string & attributeName)
Delete an attribute, by name, that is attached to this object.
Exceptions
if the attribute does not exist.
Definition at line 55 of file Attributes.cpp.
References icedb::Attributes::CanHaveAttributes_impl::_getAttributeParent(), and valid().
Referenced by writeAttributeData().
         {
             Expects(valid());
             _getAttributeParent()->removeAttr(attributeName);
         }
doesAttributeExist() [1/2]
bool icedb::Attributes::CanHaveAttributes::doesAttributeExist (const std::string & attributeName) const
Does the object have an attribute with the given name?
Note
Despite the documentation in HDF5 1.8, the attrExists function does not, in fact, exist! Tested on HDF5 1.8.5-patch1 on CentOS6, GCC 7. Docs state that this is a method of H5Object.
Definition at line 61 of file Attributes.cpp.
References icedb::Attributes::CanHaveAttributes_impl::_getAttributeParent(), and valid().
Referenced by icedb::Shapes::Shape::isShape(), icedb::Shapes::Shape::isValid(), readAttributeData(), and writeAttributeData().
         {
             Expects(valid());
 #if ICEDB_H5_HASH5OBJECTATTREXISTS == 1
             return _getAttributeParent()->attrExists(attributeName);
 #else
             hid_t objid = _getAttributeParent()->getId();
             htri_t res = H5Aexists(objid, attributeName.c_str());
             if (res < 0) throw;
             return (res > 0) ? true : false;
 #endif
         }
doesAttributeExist() [2/2]
bool icedb::Attributes::CanHaveAttributes::doesAttributeExist (gsl::not_null< const H5::H5Object *> parent, const std::string & attributeName) static
Does an object (parent) have an attribute with the given name?
Note
Despite the documentation in HDF5 1.8, the attrExists function does not, in fact, exist! Tested on HDF5 1.8.5-patch1 on CentOS6, GCC 7. Docs state that this is a method of H5Object.
Definition at line 78 of file Attributes.cpp.
         {
 #if ICEDB_H5_HASH5OBJECTATTREXISTS == 1
             return parent->attrExists(attributeName);
 #else
             hid_t objid = parent->getId();
             htri_t res = H5Aexists(objid, attributeName.c_str());
             if (res < 0) throw;
             return (res > 0) ? true : false;
 #endif
         }
getAttributeNames()
std::set< std::string > icedb::Attributes::CanHaveAttributes::getAttributeNames () const
List all attributes attached to this object.
Definition at line 95 of file Attributes.cpp.
References icedb::Attributes::CanHaveAttributes_impl::_getAttributeParent(), and valid().
{
             Expects(valid());
             //icedb::fs::hdf5::
             std::set<std::string> anames;
             int numAttrs = _getAttributeParent()->getNumAttrs();
             for (int i = 0; i < numAttrs; ++i) {
                 H5::Attribute attr = _getAttributeParent()->openAttribute(i);
                 anames.insert(attr.getName());
             }
             return anames;
         }
getAttributeTypeId() [1/2]
std::type_index icedb::Attributes::CanHaveAttributes::getAttributeTypeId (const std::string & attributeName) const
Returns the type of an attribute.
Exceptions
if the attribute does not exist.
Definition at line 50 of file Attributes.cpp.
References icedb::Attributes::CanHaveAttributes_impl::_getAttributeParent(), and icedb::Attributes::CanHaveAttributes_impl::parent.
Referenced by icedb::Shapes::Shape::isShape(), and icedb::Shapes::Shape::isValid().
{
             auto parent = _getAttributeParent();
             return getAttributeTypeId(parent.get(), attributeName);
         }
getAttributeTypeId() [2/2]
std::type_index icedb::Attributes::CanHaveAttributes::getAttributeTypeId (gsl::not_null< const H5::H5Object *> parent, const std::string & attributeName) static
Returns the type of an attribute.
Exceptions
if the attribute does not exist.
Definition at line 34 of file Attributes.cpp.
{
             if (fs::hdf5::isType<uint64_t, H5::H5Object>(parent.get(), attributeName)) return (typeid(uint64_t));
             if (fs::hdf5::isType<int64_t, H5::H5Object>(parent.get(), attributeName)) return (typeid(int64_t));
             if (fs::hdf5::isType<uint32_t, H5::H5Object>(parent.get(), attributeName)) return (typeid(uint32_t));
             if (fs::hdf5::isType<int32_t, H5::H5Object>(parent.get(), attributeName)) return (typeid(int32_t));
             if (fs::hdf5::isType<uint16_t, H5::H5Object>(parent.get(), attributeName)) return (typeid(uint16_t));
             if (fs::hdf5::isType<int16_t, H5::H5Object>(parent.get(), attributeName)) return (typeid(int16_t));
             if (fs::hdf5::isType<uint8_t, H5::H5Object>(parent.get(), attributeName)) return (typeid(uint8_t));
             if (fs::hdf5::isType<int8_t, H5::H5Object>(parent.get(), attributeName)) return (typeid(int8_t));
             if (fs::hdf5::isType<double, H5::H5Object>(parent.get(), attributeName)) return (typeid(double));
             if (fs::hdf5::isType<float, H5::H5Object>(parent.get(), attributeName)) return (typeid(float));
             if (fs::hdf5::isType<char, H5::H5Object>(parent.get(), attributeName)) return (typeid(char));
             if (fs::hdf5::isType<std::string, H5::H5Object>(parent.get(), attributeName)) return (typeid(std::string));
             throw;
         }
isAttributeOfType()
template<class Type > bool icedb::Attributes::CanHaveAttributes::isAttributeOfType (const std::string & attributeName) const inline
Is the type of the attribute "Type"?
Exceptions
if the attribute does not exist.
Definition at line 81 of file Attribute.hpp.
References icedb::Attributes::Attribute< DataType >::data.
{
                 std::type_index atype = getAttributeTypeId(attributeName);
                 if (atype == typeid(Type)) return true;
                 return false;
             }
readAttribute() [1/2]
template<class DataType > static Attribute<DataType> icedb::Attributes::CanHaveAttributes::readAttribute (gsl::not_null< const H5::H5Object *> obj, const std::string & attributeName) inline static
Convenience function to read an attribute's data and return an Attribute object.
Exceptions
if the base object does not exist
if the attribute has a mismatched DataType
if the attribute does not exist
Parameters
obj is the containing object
DataType is the type of the data
attributeName is the name of the attribute
Definition at line 138 of file Attribute.hpp.
References icedb::Attributes::Attribute< DataType >::data, and icedb::Attributes::Attribute< DataType >::dimensionality.
             {
                 Attribute<DataType> res(attributeName);
                 readAttributeData(obj, attributeName, res.dimensionality, res.data);
                 return res;
             }
readAttribute() [2/2]
template<class DataType > Attribute<DataType> icedb::Attributes::CanHaveAttributes::readAttribute (const std::string & attributeName) const inline
Convenience function to read an attribute's data and return an Attribute object.
Exceptions
if the attribute has a mismatched DataType
if the attribute does not exist
Parameters
DataType is the type of the data
attributeName is the name of the attribute
Definition at line 150 of file Attribute.hpp.
References icedb::Attributes::Attribute< DataType >::data, and icedb::Attributes::Attribute< DataType >::dimensionality.
{
                 Attribute<DataType> res(attributeName);
                 readAttributeData(attributeName, res.dimensionality, res.data);
                 return res;
             }
readAttributeData() [1/2]
template<class DataType > void icedb::Attributes::CanHaveAttributes::readAttributeData (gsl::not_null< const H5::H5Object *> parent, const std::string & attributeName, std::vector< size_t > & dimensions, std::vector< DataType > & data) static
Function to read the data from an attribute.
Exceptions
if the attribute does not exist
if the parent is invalid
Parameters
DataType is the type of the data to be read
Exceptions
if there is a type mismatch between the actual data's type and the type expected in the function call.
Parameters
parent is the container of the attribute
attributeName is the name of the attribute
dimensions are the returned dimensions of the attribute.
data are the returned attribute data. The mapping of dimensions and data follows the regular C convention (in contrast to the Fortran one).
Definition at line 150 of file Attributes.cpp.
References doesAttributeExist().
         {
             Expects(doesAttributeExist(parent,attributeName));
             if (icedb::fs::hdf5::isType<DataType, H5::H5Object>(parent.get(), attributeName))
                 pullData<DataType>(attributeName, dims, data, parent.get());
             else throw(std::invalid_argument("Unhandled data type"));
         }
readAttributeData() [2/2]
template<class DataType > void icedb::Attributes::CanHaveAttributes::readAttributeData (const std::string & attributeName, std::vector< size_t > & dimensions, std::vector< DataType > & data) const
Function to read the data from an attribute using the provided input vectors.
Exceptions
if the attribute does not exist
Parameters
DataType is the type of the data to be read
Exceptions
if there is a type mismatch between the actual data's type and the type expected in the function call.
Parameters
attributeName is the name of the attribute
dimensions are the returned dimensions of the attribute.
data are the returned attribute data. The mapping of dimensions and data follows the regular C convention (in contrast to the Fortran one).
Definition at line 164 of file Attributes.cpp.
References icedb::Attributes::CanHaveAttributes_impl::_getAttributeParent(), doesAttributeExist(), icedb::Attributes::CanHaveAttributes_impl::parent, and valid().
         {
             Expects(valid());
             Expects(doesAttributeExist(attributeName));
             auto parent = _getAttributeParent();
             readAttributeData<DataType>(parent.get(), attributeName, dims, data);
         }
valid()
bool icedb::Attributes::CanHaveAttributes::valid () const private
Definition at line 19 of file Attributes.cpp.
References icedb::Attributes::CanHaveAttributes_impl::_getAttributeParent().
Referenced by deleteAttribute(), doesAttributeExist(), getAttributeNames(), readAttributeData(), and writeAttributeData().
{
             if (!_getAttributeParent()) return false;
             return true;
         }
writeAttribute() [1/2]
template<class DataType > void icedb::Attributes::CanHaveAttributes::writeAttribute (const Attribute< DataType > & attribute) inline
Convenience function to write an Attribute to an object.
Exceptions
if the attribute is somehow invalid (usually from not giving it a proper name).
Parameters
DataType is the type of the data
is an Attribute<DataType> object
Definition at line 160 of file Attribute.hpp.
References icedb::Attributes::Attribute< DataType >::data, icedb::Attributes::Attribute< DataType >::dimensionality, and icedb::Attributes::Attribute< DataType >::name.
{
                 size_t sz = 1;
                 for (const auto &d : attribute.dimensionality) sz *= d;
                 Expects(attribute.data.size() == sz);
                 writeAttributeData(attribute.name, attribute.dimensionality, attribute.data);
             }
writeAttribute() [2/2]
template<class DataType > void icedb::Attributes::CanHaveAttributes::writeAttribute (const std::string & name, std::initializer_list< size_t > dims, std::initializer_list< DataType > data) inline
Convenience function to write a small Attribute to an object, using initializer lists.
Example: grpTest1->writeAttribute<uint64_t>("TestInt5", {1}, {65536});
Parameters
name is the attribute's name
dims are the dimensions
data are the data
Exceptions
if the name is invalid
Definition at line 175 of file Attribute.hpp.
{
                 Attribute<DataType> attr(name, dims, data);
                 writeAttribute(attr);
             }
writeAttributeData()
template<class DataType > void icedb::Attributes::CanHaveAttributes::writeAttributeData (const std::string & attributeName, const std::vector< size_t > & dimensionas, const std::vector< DataType > & data)
Function to write an attribute to an object, with the provided raw data.
Exceptions
if the base object is read-only
Parameters
DataType is the type of the data to be read
attributeName is the name of the attribute
dimensions are the dimensions of the attribute.
data are the attribute data. The mapping of dimensions and data follows the regular C convention (in contrast to the Fortran one).
Definition at line 219 of file Attributes.cpp.
References icedb::Attributes::CanHaveAttributes_impl::_getAttributeParent(), deleteAttribute(), doesAttributeExist(), icedb::Attributes::CanHaveAttributes_impl::parent, and valid().
         {
             Expects(valid());
             if (doesAttributeExist(attributeName)) deleteAttribute(attributeName);
             auto parent = _getAttributeParent();
             // Need to copy from the variant structure into an array of the exact data type
             //if (icedb::fs::hdf5::isType<DataType, H5::H5Object>(parent.get(), attributeName))
                 //pullData<DataType>(attributeName, dims, data, parent.get());
             pushData<DataType, H5::H5Object>(attributeName, dimensionality, parent, data);
         }
The documentation for this class was generated from the following files:
lib/icedb/Attribute.hpp
lib/src/Attributes.cpp