icedb: lib/src/error.cpp File Reference
error.cpp File Reference
#include "../icedb/error.hpp"
#include "../private/options.hpp"
#include "../icedb/error_context.h"
#include "../icedb/error.h"
#include "../icedb/util.h"
#include <cstdio>
#include <cstring>
#include <vector>
#include <string>
#include <cwchar>
#include <complex>
#include <list>
#include <sstream>
Classes
class icedb::error::error_options_inner
Namespaces
icedb
icedb::error
Macros
#define DOTYPES(f)
#define IMPL_xError_ADD(T) template xError& xError::add<T>(const std::string&, const T);
Functions
ICEDB_BEGIN_DECL_C ICEDB_error_code error_context_to_code (const struct ICEDB_error_context *err)
size_t error_context_to_message_size (const struct ICEDB_error_context *err)
size_t error_context_to_message (const struct ICEDB_error_context *err, size_t buf_size, char *buf)
size_t error_context_to_stream (const struct ICEDB_error_context *err, FILE *fp)
ICEDB_error_code error_test ()
size_t error_code_to_message_size (ICEDB_error_code err)
size_t error_code_to_message (ICEDB_error_code err, size_t buf_size, char *buf)
size_t error_code_to_stream (ICEDB_error_code err, FILE *fp)
struct ICEDB_error_context * get_error_context_thread_local_c ()
void error_context_deallocate (struct ICEDB_error_context *c)
const char * error_getOSname ()
icedb::error::DOTYPES (IMPL_xError_ADD)
template<>
DL_ICEDB std::string icedb::error::stringify< std::string > (error_code_t err)
template<>
DL_ICEDB const char * icedb::error::stringify< const char * > (error_code_t err)
DL_ICEDB error_context_pt icedb::error::get_error_context_thread_local ()
DL_ICEDB void icedb::error::stringify (error_code_t err, std::string &res)
DL_ICEDB void icedb::error::stringify (error_code_t err, const char **res)
DL_ICEDB void icedb::error::stringify (const error_context_pt &err, std::string &res)
DL_ICEDB std::string icedb::error::stringify (const error_context_pt &err)
DL_ICEDB error_code_t icedb::error::error_context_to_code (const error_context_pt &err)
Variables
DL_ICEDB ICEDB_error_context_to_code_f ICEDB_error_context_to_code = error_context_to_code
DL_ICEDB ICEDB_error_context_to_message_size_f ICEDB_error_context_to_message_size = error_context_to_message_size
DL_ICEDB ICEDB_error_context_to_message_f ICEDB_error_context_to_message = error_context_to_message
DL_ICEDB ICEDB_error_context_to_stream_f ICEDB_error_context_to_stream = error_context_to_stream
DL_ICEDB ICEDB_error_test_f ICEDB_error_test = error_test
DL_ICEDB ICEDB_error_code_to_message_size_f ICEDB_error_code_to_message_size = error_code_to_message_size
DL_ICEDB ICEDB_error_code_to_message_f ICEDB_error_code_to_message = error_code_to_message
DL_ICEDB ICEDB_error_code_to_stream_f ICEDB_error_code_to_stream = error_code_to_stream
DL_ICEDB ICEDB_get_error_context_thread_local_f ICEDB_get_error_context_thread_local = get_error_context_thread_local_c
DL_ICEDB ICEDB_error_context_deallocate_f ICEDB_error_context_deallocate = error_context_deallocate
DL_ICEDB ICEDB_error_getOSname_f ICEDB_error_getOSname = error_getOSname
DL_ICEDB const struct ICEDB_error_container_ftable ICEDB_ct_error
Macro Definition Documentation
DOTYPES
#define DOTYPES (f)
Value:
f(int); f(float); f(double); f(long); f(long long); \
    f(unsigned int); f(unsigned long); f(unsigned long long); f(std::string); f(bool); f(std::complex<double>);
Definition at line 278 of file error.cpp.
IMPL_xError_ADD
#define IMPL_xError_ADD (T) template xError& xError::add<T>(const std::string&, const T);
Definition at line 281 of file error.cpp.
Function Documentation
error_code_to_message()
size_t error_code_to_message (ICEDB_error_code err, size_t buf_size, char * buf)
Definition at line 143 of file error.cpp.
References ICEDB_COMPAT_strncpy_s(), ICEDB_COMPAT_strnlen_s, ICEDB_DEBUG_RAISE_EXCEPTION, ICEDB_ERRORCODES_MAP, and ICEDB_ERRORCODES_TOTAL.
 {
     if (!buf) ICEDB_DEBUG_RAISE_EXCEPTION();
     if (err >= ICEDB_ERRORCODES_TOTAL) ICEDB_DEBUG_RAISE_EXCEPTION();
     uint16_t cnt = (uint16_t)ICEDB_COMPAT_strnlen_s(ICEDB_ERRORCODES_MAP[err],
         SIZE_MAX - 1) + 1; // -1,+1 because message_size includes the null character.
     size_t res = ICEDB_COMPAT_strncpy_s(buf, buf_size, ICEDB_ERRORCODES_MAP[err], cnt);
     return size_t((res>SIZE_MAX) ? SIZE_MAX : res);
 }
error_code_to_message_size()
size_t error_code_to_message_size (ICEDB_error_code err)
Definition at line 134 of file error.cpp.
References ICEDB_COMPAT_strnlen_s, ICEDB_DEBUG_RAISE_EXCEPTION, ICEDB_ERRORCODES_MAP, and ICEDB_ERRORCODES_TOTAL.
 {
     if (err >= ICEDB_ERRORCODES_TOTAL) ICEDB_DEBUG_RAISE_EXCEPTION();
     size_t res = (size_t)ICEDB_COMPAT_strnlen_s(ICEDB_ERRORCODES_MAP[err],
         1000) + 1; // -1,+1 because message_size includes the null character.
     return res;
 }
error_code_to_stream()
size_t error_code_to_stream (ICEDB_error_code err, FILE * fp)
Definition at line 154 of file error.cpp.
References ICEDB_COMPAT_fputs_s, ICEDB_DEBUG_RAISE_EXCEPTION, ICEDB_ERRORCODES_MAP, and ICEDB_ERRORCODES_TOTAL.
 {
     if (!fp) ICEDB_DEBUG_RAISE_EXCEPTION();
     if (err >= ICEDB_ERRORCODES_TOTAL) ICEDB_DEBUG_RAISE_EXCEPTION();
     size_t res = ICEDB_COMPAT_fputs_s(ICEDB_ERRORCODES_MAP[err], fp);
     return size_t(res);
 }
error_context_deallocate()
void error_context_deallocate (struct ICEDB_error_context * c)
Definition at line 170 of file error.cpp.
References ICEDB_DEBUG_RAISE_EXCEPTION, ICEDB_free(), ICEDB_error_context::message_text, ICEDB_error_context::num_var_fields, ICEDB_error_context_var_val::val, ICEDB_error_context::var_vals, and ICEDB_error_context_var_val::varname.
Referenced by icedb::error::get_error_context_thread_local().
 {
     if (!c) ICEDB_DEBUG_RAISE_EXCEPTION();
     if (c->message_text) ICEDB_free(c->message_text);
     if (c->var_vals) { // Should always exist, as the construction function automatically widens / allocates.
         for (int i = 0; i < c->num_var_fields; ++i) {
             ICEDB_free(c->var_vals[i].val);
             ICEDB_free(c->var_vals[i].varname);
         }
         ICEDB_free(c->var_vals);
     }
     ICEDB_free(c);
 }
error_context_to_code()
ICEDB_BEGIN_DECL_C ICEDB_error_code error_context_to_code (const struct ICEDB_error_context * err)
Definition at line 17 of file error.cpp.
References ICEDB_error_context::code, and ICEDB_DEBUG_RAISE_EXCEPTION.
{
     if (!err) ICEDB_DEBUG_RAISE_EXCEPTION();
     return err->code;
 }
error_context_to_message()
size_t error_context_to_message (const struct ICEDB_error_context * err, size_t buf_size, char * buf)
Definition at line 63 of file error.cpp.
References ICEDB_COMPAT_strncpy_s(), ICEDB_DEBUG_RAISE_EXCEPTION, ICEDB_free(), ICEDB_malloc(), ICEDB_error_context::message_size, ICEDB_error_context::message_text, ICEDB_error_context::num_var_fields, ICEDB_error_context_var_val::val, ICEDB_error_context::var_vals, and ICEDB_error_context_var_val::varname.
 {
     if (!err) ICEDB_DEBUG_RAISE_EXCEPTION();
     if (!buf) ICEDB_DEBUG_RAISE_EXCEPTION();
     size_t total = 0;
     if (err->message_text) {
         total = ICEDB_COMPAT_strncpy_s(buf, buf_size, err->message_text, err->message_size); // Reports the number of characters copied. Note lack of count of null.
     }
     // Write the error variables
     const char* sep = "\t%s\t=\t%s\n";
     const size_t seplen = strlen(sep);
 #ifdef ICEDB_USING_SECURE_STRINGS
     if (err->num_var_fields)
         for (int i = 0; i < err->num_var_fields; ++i)
             total += sprintf_s(buf + total, buf_size - total, sep, err->var_vals[i].varname, err->var_vals[i].val);
 #else
     size_t expectedSize = 0;
     if (err->num_var_fields) {
         for (int i = 0; i < err->num_var_fields; ++i) {
             // Manually size a temporary buffer, and then copy the data.
             expectedSize += seplen + strlen(err->var_vals[i].val) + strlen(err->var_vals[i].varname);
         }
     }
     char *tempbuf = (char*)ICEDB_malloc(sizeof(char)*expectedSize);
     size_t j = 0;
     if (err->num_var_fields) {
         for (int i = 0; i < err->num_var_fields; ++i) {
             j += sprintf(tempbuf + j, sep, err->var_vals[i].varname, err->var_vals[i].val);
         }
     }
     ICEDB_COMPAT_strncpy_s(buf + total, buf_size - total, tempbuf, j);
     total += j;
     ICEDB_free(tempbuf);
 #endif
     return size_t(total);
 }
error_context_to_message_size()
size_t error_context_to_message_size (const struct ICEDB_error_context * err)
Definition at line 23 of file error.cpp.
References ICEDB_COMPAT_strncpy_s(), ICEDB_DEBUG_RAISE_EXCEPTION, ICEDB_free(), ICEDB_malloc(), ICEDB_error_context::message_size, ICEDB_error_context::message_text, ICEDB_error_context::num_var_fields, ICEDB_error_context_var_val::val, ICEDB_error_context::var_vals, and ICEDB_error_context_var_val::varname.
{
     if (!err) ICEDB_DEBUG_RAISE_EXCEPTION();
     size_t total = 1;
     const size_t buf_size = 1000;
     char buf[buf_size];
     if (err->message_text) {
         total += ICEDB_COMPAT_strncpy_s(buf, buf_size, err->message_text, err->message_size); // Reports the number of characters copied. Note lack of count of null.
     }
     // Write the error variables
     const char* sep = "\t%s\t=\t%s\n";
     const size_t seplen = strlen(sep);
 #ifdef ICEDB_USING_SECURE_STRINGS
     if (err->num_var_fields)
         for (int i = 0; i < err->num_var_fields; ++i)
             total += sprintf_s(buf + total, buf_size - total, sep, err->var_vals[i].varname, err->var_vals[i].val);
 #else
     size_t expectedSize = 0;
     if (err->num_var_fields) {
         for (int i = 0; i < err->num_var_fields; ++i) {
             // Manually size a temporary buffer, and then copy the data.
             expectedSize += seplen + strlen(err->var_vals[i].val) + strlen(err->var_vals[i].varname);
         }
     }
     char *tempbuf = (char*)ICEDB_malloc(sizeof(char)*expectedSize);
     size_t j = 0;
     if (err->num_var_fields) {
         for (int i = 0; i < err->num_var_fields; ++i) {
             j += sprintf(tempbuf + j, sep, err->var_vals[i].varname, err->var_vals[i].val);
         }
     }
     ICEDB_COMPAT_strncpy_s(buf + total, buf_size - total, tempbuf, j);
     total += j;
     ICEDB_free(tempbuf);
 #endif
     return size_t(total);
 }
error_context_to_stream()
size_t error_context_to_stream (const struct ICEDB_error_context * err, FILE * fp)
Definition at line 103 of file error.cpp.
References ICEDB_COMPAT_fprintf_s, ICEDB_COMPAT_fputs_s, ICEDB_DEBUG_RAISE_EXCEPTION, ICEDB_error_context::message_text, ICEDB_error_context::num_var_fields, ICEDB_error_context_var_val::val, ICEDB_error_context::var_vals, and ICEDB_error_context_var_val::varname.
 {
     if (!err) ICEDB_DEBUG_RAISE_EXCEPTION();
     if (!fp) ICEDB_DEBUG_RAISE_EXCEPTION();
     int res = 0;
     if (err->message_text) {
         res = ICEDB_COMPAT_fputs_s(err->message_text, fp);
     }
     // Error validation
     if (res == EOF) {
         printf("Error in writing error context to stream. Error code is %d. Context text is: %s.\n",
             ferror(fp), err->message_text);
     }
     // Write the error variables
     if (err->num_var_fields) {
         for (int i = 0; i < err->num_var_fields; ++i)
             ICEDB_COMPAT_fprintf_s(fp, "\t%s\t=\t%s\n", err->var_vals[i].varname, err->var_vals[i].val);
     }
     return uint16_t(res);
 }
error_getOSname()
const char* error_getOSname ()
Definition at line 185 of file error.cpp.
{
     const char* name =
 #if defined(__FreeBSD__)
         "FreeBSD";
 #elif defined(__NetBSD__)
         "NetBSD";
 #elif defined(__OpenBSD__)
         "OpenBSD";
 #elif defined(__bsdi__)
         "bsdi";
 #elif defined(__DragonFly__)
         "DragonFly BSD";
 #elif defined (__APPLE__)
         "Apple";
 #elif defined(__linux__)
         "Linux";
 #elif defined(_WIN32)
         "Windows";
 #elif defined(__unix__)
         "Generic Unix";
 #else
         "UNKNOWN";
 #endif
     return name;
 }
error_test()
ICEDB_error_code error_test ()
Definition at line 126 of file error.cpp.
References ICEDB_error_context_append_str, ICEDB_error_context_create, and ICEDB_ERRORCODES_TODO.
 {
     ICEDB_error_context *cxt = ICEDB_error_context_create(ICEDB_ERRORCODES_TODO);
     ICEDB_error_context_append_str(cxt, "This is a test.\n");
     return ICEDB_ERRORCODES_TODO;
 }
get_error_context_thread_local_c()
struct ICEDB_error_context* get_error_context_thread_local_c ()
Definition at line 164 of file error.cpp.
References __ICEDB_LOCAL_THREAD_error_context.
Referenced by icedb::error::get_error_context_thread_local().
 {
     return __ICEDB_LOCAL_THREAD_error_context;
 }