icedb: lib/src/error_context.cpp File Reference
error_context.cpp File Reference
#include "../icedb/defs.h"
#include "../icedb/util.h"
#include <string.h>
#include <stdlib.h>
#include "../icedb/error_context.h"
Functions
struct ICEDB_error_context * error_context_create_impl (int code, const char *file, int line, const char *fsig)
struct ICEDB_error_context * error_context_copy (const struct ICEDB_error_context *c)
void error_context_append (struct ICEDB_error_context *c, size_t sz, const char *data)
void error_context_append_str (struct ICEDB_error_context *c, const char *data)
void error_context_add_string (struct ICEDB_error_context *c, size_t var_sz, const char *var_name, size_t val_sz, const char *var_val)
void error_context_add_string2 (struct ICEDB_error_context *c, const char *var_name, const char *var_val)
void error_context_widen (struct ICEDB_error_context *c, size_t numNewSpaces)
Variables
ICEDB_SYMBOL_PRIVATE ICEDB_THREAD_LOCAL ICEDB_error_context * __ICEDB_LOCAL_THREAD_error_context = NULL
DL_ICEDB ICEDB_error_context_create_impl_f ICEDB_error_context_create_impl = error_context_create_impl
DL_ICEDB ICEDB_error_context_copy_f ICEDB_error_context_copy = error_context_copy
DL_ICEDB ICEDB_error_context_appendA_f ICEDB_error_context_appendA = error_context_append
DL_ICEDB ICEDB_error_context_append_strA_f ICEDB_error_context_append_strA = error_context_append_str
DL_ICEDB ICEDB_error_context_add_stringA_f ICEDB_error_context_add_stringA = error_context_add_string
DL_ICEDB ICEDB_error_context_add_string2A_f ICEDB_error_context_add_string2A = error_context_add_string2
DL_ICEDB ICEDB_error_context_widen_f ICEDB_error_context_widen = error_context_widen
DL_ICEDB const struct ICEDB_error_context_container_ftable ICEDB_ct_error_context
Function Documentation
error_context_add_string()
void error_context_add_string (struct ICEDB_error_context * c, size_t var_sz, const char * var_name, size_t val_sz, const char * var_val)
Definition at line 87 of file error_context.cpp.
References ICEDB_COMPAT_strdup_s(), ICEDB_error_context_widen, ICEDB_error_context::max_num_var_fields, ICEDB_error_context::num_var_fields, ICEDB_error_context_var_val::val, ICEDB_error_context::var_vals, and ICEDB_error_context_var_val::varname.
 {
     if (c->num_var_fields == c->max_num_var_fields)
         ICEDB_error_context_widen(c, 30);
     c->var_vals[c->num_var_fields].varname = ICEDB_COMPAT_strdup_s(var_name, var_sz);
     c->var_vals[c->num_var_fields].val = ICEDB_COMPAT_strdup_s(var_val, val_sz);
     c->num_var_fields++;
 }
error_context_add_string2()
void error_context_add_string2 (struct ICEDB_error_context * c, const char * var_name, const char * var_val)
Definition at line 97 of file error_context.cpp.
References ICEDB_error_context_add_string.
 {
 #if defined(__STDC_LIB_EXT1__) || defined(__STDC_SECURE_LIB__)
     ICEDB_error_context_add_string(c, (size_t)strnlen_s(var_name, UINT16_MAX), var_name, (size_t)strnlen_s(var_val, UINT16_MAX), var_val);
 #else
     ICEDB_error_context_add_string(c, strnlen(var_name, UINT16_MAX), var_name, strnlen(var_val, UINT16_MAX), var_val);
 #endif
 }
error_context_append()
void error_context_append (struct ICEDB_error_context * c, size_t sz, const char * data)
Definition at line 57 of file error_context.cpp.
References ICEDB_COMPAT_strncpy_s(), ICEDB_COMPAT_strnlen_s, ICEDB_free(), ICEDB_malloc(), ICEDB_error_context::message_size, ICEDB_error_context::message_size_alloced, and ICEDB_error_context::message_text.
 {
     if (data[sz] != '\0' && data[sz + 1] == '\0') sz++; // Null character check
     const size_t min_alloc_size_inc = 256;
     if (c->message_size + sz >= c->message_size_alloced) {
         size_t newszinc = (sz> min_alloc_size_inc) ? sz : min_alloc_size_inc;
         size_t newsz = c->message_size_alloced + newszinc;
         char* newtext = (char*)ICEDB_malloc(newsz);
         if (c->message_text) {
             ICEDB_COMPAT_strncpy_s(newtext, newsz, c->message_text, c->message_size_alloced);
             ICEDB_free(c->message_text);
         }
         c->message_text = newtext;
         c->message_size_alloced = newsz;
     }
     ICEDB_COMPAT_strncpy_s(c->message_text+ c->message_size-1, //c->message_size always includes the null character
         c->message_size_alloced-c->message_size,
         data, sz);
     c->message_size = (size_t) ICEDB_COMPAT_strnlen_s(c->message_text,
         (c->message_size_alloced < UINT16_MAX-1) ? c->message_size_alloced : UINT16_MAX-1)+1; // -1,+1 because message_size includes the null character.
 }
error_context_append_str()
void error_context_append_str (struct ICEDB_error_context * c, const char * data)
Definition at line 80 of file error_context.cpp.
References ICEDB_error_context_append.
 {
     size_t sz = (size_t) strnlen(data, UINT16_MAX);
     ICEDB_error_context_append(c, sz+1, data);
 }
error_context_copy()
struct ICEDB_error_context* error_context_copy (const struct ICEDB_error_context * c)
Definition at line 40 of file error_context.cpp.
References ICEDB_error_context::code, ICEDB_COMPAT_strncpy_s(), ICEDB_error_context_add_string2, ICEDB_error_context_create, ICEDB_malloc(), ICEDB_error_context::message_size, ICEDB_error_context::message_size_alloced, ICEDB_error_context::message_text, ICEDB_error_context::num_var_fields, ICEDB_error_context_var_val::val, ICEDB_error_context::var_vals, and ICEDB_error_context_var_val::varname.
 {
     if (!c) return NULL;
     ICEDB_error_context* res = ICEDB_error_context_create(c->code);
     res->code = c->code;
     res->message_size = c->message_size;
     res->message_size_alloced = c->message_size_alloced;
     res->message_text = (char*)ICEDB_malloc(c->message_size_alloced);
     ICEDB_COMPAT_strncpy_s(res->message_text, c->message_size_alloced, c->message_text, c->message_size_alloced);
     for (int i = 0; i < c->num_var_fields; ++i)
         ICEDB_error_context_add_string2(res, c->var_vals[i].varname, c->var_vals[i].val);
     return res;
 }
error_context_create_impl()
struct ICEDB_error_context* error_context_create_impl (int code, const char * file, int line, const char * fsig)
Definition at line 10 of file error_context.cpp.
References __ICEDB_LOCAL_THREAD_error_context, ICEDB_error_context::code, ICEDB_COMPAT_strncpy_s(), ICEDB_COMPAT_strnlen_s, ICEDB_DEBUG_RAISE_EXCEPTION, ICEDB_error_context_add_string2, ICEDB_error_context_widen, ICEDB_ERRORCODES_MAP, ICEDB_free(), ICEDB_malloc(), ICEDB_error_context::max_num_var_fields, ICEDB_error_context::message_size, ICEDB_error_context::message_size_alloced, ICEDB_error_context::message_text, ICEDB_error_context::num_var_fields, and ICEDB_error_context::var_vals.
 {
     ICEDB_error_context* res = (ICEDB_error_context*) ICEDB_malloc(sizeof (ICEDB_error_context));
     if (!res) ICEDB_DEBUG_RAISE_EXCEPTION();
     res->code = code;
     res->message_size_alloced = (size_t) (sizeof(char)*(1 + ICEDB_COMPAT_strnlen_s(ICEDB_ERRORCODES_MAP[code],UINT16_MAX-1)));
     res->message_text = (char*)ICEDB_malloc(sizeof(char)*res->message_size_alloced);
     ICEDB_COMPAT_strncpy_s(res->message_text, res->message_size_alloced,
         ICEDB_ERRORCODES_MAP[code], (size_t)sizeof(char)*(1+ ICEDB_COMPAT_strnlen_s(ICEDB_ERRORCODES_MAP[code], UINT16_MAX - 1)));
     // Note that the null character is counted here, by my convention. message_size should NEVER equal zero.
     res->message_size = (size_t) (sizeof(char)*(1 + ICEDB_COMPAT_strnlen_s(res->message_text, UINT16_MAX - 1)));
     res->num_var_fields = 0;
     res->max_num_var_fields = 0;
     res->var_vals = NULL;
     ICEDB_error_context_widen(res, 30);
     ICEDB_error_context_add_string2(res, "file", file);
     ICEDB_error_context_add_string2(res, "fsig", fsig);
     const int slinesz = 50;
     char sline[slinesz];
     snprintf(sline, slinesz, "%d", line);
     ICEDB_error_context_add_string2(res, "line", sline);
     if (__ICEDB_LOCAL_THREAD_error_context) ICEDB_free(__ICEDB_LOCAL_THREAD_error_context);
     __ICEDB_LOCAL_THREAD_error_context = res;
     return res;
 }
error_context_widen()
void error_context_widen (struct ICEDB_error_context * c, size_t numNewSpaces)
Definition at line 107 of file error_context.cpp.
References ICEDB_COMPAT_strncpy_s(), ICEDB_free(), ICEDB_malloc(), ICEDB_error_context::max_num_var_fields, ICEDB_error_context_var_val::val, ICEDB_error_context::var_vals, and ICEDB_error_context_var_val::varname.
 {
     ICEDB_error_context_var_val* newvals = (ICEDB_error_context_var_val*)ICEDB_malloc(
         (numNewSpaces + c->max_num_var_fields) * (sizeof (ICEDB_error_context)));
     for (size_t i = 0; i < numNewSpaces; ++i) {
         newvals[i + c->max_num_var_fields].val = NULL;
         newvals[i + c->max_num_var_fields].varname = NULL;
     }
     if (c->var_vals) {
         for (size_t i = 0; i < c->max_num_var_fields; ++i) {
             size_t szval = sizeof(char) * strlen(c->var_vals[i].val);
             newvals[i].val = (char*)ICEDB_malloc(szval);
             ICEDB_COMPAT_strncpy_s(newvals[i].val, szval, c->var_vals[i].val, szval);
             size_t szname = sizeof(char) * strlen(c->var_vals[i].varname);
             newvals[i].varname = (char*)ICEDB_malloc(szname);
             ICEDB_COMPAT_strncpy_s(newvals[i].varname, szname, c->var_vals[i].varname, szname);
         }
         ICEDB_free(c->var_vals);
     }
     c->var_vals = newvals;
     c->max_num_var_fields += numNewSpaces;
 }