icedb: icedb::error Namespace Reference
icedb::error Namespace Reference
Classes
class error_options_inner
class xError
Typedefs
typedef std::shared_ptr< xError > xError_ptr
typedef ICEDB_error_code error_code_t
typedef std::shared_ptr< ICEDB_error_context > error_context_pt
typedef ICEDB_ERRORCODES error_codes
Enumerations
enum error_types {
error_types::xDivByZero, error_types::xInvalidRange, error_types::xAssert, error_types::xBadInput,
error_types::xNullPointer, error_types::xModelOutOfRange, error_types::xMissingFrequency, error_types::xEmptyInputFile,
error_types::xMissingFolder, error_types::xMissingFile, error_types::xMissingVariable, error_types::xMissingConfigurationFile,
error_types::xFileExists, error_types::xPathExistsWrongType, error_types::xTypeMismatch, error_types::xUnknownFileFormat,
error_types::xMissingKey, error_types::xMissingHash, error_types::xKeyExists, error_types::xUnimplementedFunction,
error_types::xFallbackTemplate, error_types::xArrayOutOfBounds, error_types::xDimensionMismatch, error_types::xSingular,
error_types::xDLLversionMismatch, error_types::xDuplicateHook, error_types::xHandleInUse, error_types::xHandleNotOpen,
error_types::xSymbolNotFound, error_types::xBadFunctionMap, error_types::xBadFunctionReturn, error_types::xBlockedHookLoad,
error_types::xBlockedHookUnload, error_types::xDLLerror, error_types::xUpcast, error_types::xCannotFindReference,
error_types::xOtherError, error_types::xUnsupportedIOaction
}
Functions
DOTYPES (IMPL_xError_ADD)
template<>
DL_ICEDB std::string stringify< std::string > (error_code_t err)
template<>
DL_ICEDB const char * stringify< const char * > (error_code_t err)
DL_ICEDB error_context_pt get_error_context_thread_local ()
DL_ICEDB void stringify (error_code_t err, std::string &res)
DL_ICEDB void stringify (error_code_t err, const char **res)
DL_ICEDB void stringify (const error_context_pt &err, std::string &res)
DL_ICEDB std::string stringify (const error_context_pt &err)
DL_ICEDB error_code_t error_context_to_code (const error_context_pt &err)
const char * stringify (error_types et)
template<class StringType >
StringType stringify (error_code_t err)
template<>
DL_ICEDB std::string stringify (error_code_t err)
template<>
DL_ICEDB const char * stringify (error_code_t err)
Typedef Documentation
error_code_t
typedef ICEDB_error_code icedb::error::error_code_t
Defines an error condition. This is an integer. Zero (0) indicates that there is no error.
Definition at line 42 of file error.hpp.
error_codes
typedef ICEDB_ERRORCODES icedb::error::error_codes
Definition at line 12 of file errorCodes.hpp.
error_context_pt
typedef std::shared_ptr<ICEDB_error_context> icedb::error::error_context_pt
Defines an error context. This structure contains both an error code (for fast lookups) and any ancillary information to determine why / how the error occurred. The library keeps an internal buffer of these objects, and copies them when the program requests them. It is then the programmer's job to free all instances that are thus marshalled.
Definition at line 56 of file error.hpp.
xError_ptr
typedef std::shared_ptr<xError> icedb::error::xError_ptr
Definition at line 13 of file error.hpp.
Enumeration Type Documentation
error_types
enum icedb::error::error_types strong
Enumerator
xDivByZero
xInvalidRange
xAssert
xBadInput
xNullPointer
xModelOutOfRange
xMissingFrequency
xEmptyInputFile
xMissingFolder
xMissingFile
xMissingVariable
xMissingConfigurationFile
xFileExists
xPathExistsWrongType
xTypeMismatch
xUnknownFileFormat
xMissingKey
xMissingHash
xKeyExists
xUnimplementedFunction
xFallbackTemplate
xArrayOutOfBounds
xDimensionMismatch
xSingular
xDLLversionMismatch
xDuplicateHook
xHandleInUse
xHandleNotOpen
xSymbolNotFound
xBadFunctionMap
xBadFunctionReturn
xBlockedHookLoad
xBlockedHookUnload
xDLLerror
xUpcast
xCannotFindReference
xOtherError
xUnsupportedIOaction
Definition at line 5 of file errorTypes.hpp.
{
             xDivByZero,
             xInvalidRange,
             xAssert,
             xBadInput,
             xNullPointer,
             xModelOutOfRange,
             xMissingFrequency,
             xEmptyInputFile,
             xMissingFolder,
             xMissingFile,
             xMissingVariable,
             xMissingConfigurationFile,
             xFileExists,
             xPathExistsWrongType,
             xTypeMismatch,
             xUnknownFileFormat,
             xMissingKey,
             xMissingHash,
             xKeyExists,
             xUnimplementedFunction,
             xFallbackTemplate,
             xArrayOutOfBounds,
             xDimensionMismatch,
             xSingular,
             xDLLversionMismatch,
             xDuplicateHook,
             xHandleInUse,
             xHandleNotOpen,
             xSymbolNotFound,
             xBadFunctionMap,
             xBadFunctionReturn,
             xBlockedHookLoad,
             xBlockedHookUnload,
             xDLLerror,
             xUpcast,
             xCannotFindReference,
             xOtherError,
             xUnsupportedIOaction
         };
Function Documentation
DOTYPES()
icedb::error::DOTYPES (IMPL_xError_ADD)
error_context_to_code()
DL_ICEDB error_code_t icedb::error::error_context_to_code (const error_context_pt &)
Get the error code from the context. Shouldn't be necessary.
Definition at line 327 of file error.cpp.
References ICEDB_error_context_to_code.
 { return ICEDB_error_context_to_code(err.get()); }
get_error_context_thread_local()
DL_ICEDB error_context_pt icedb::error::get_error_context_thread_local ()
Copy the last error context raised within the active thread. The resulting object should be freed once no longer needed. Returns NULL if no context exists.
Definition at line 303 of file error.cpp.
References error_context_deallocate(), and get_error_context_thread_local_c().
{
             return error_context_pt(get_error_context_thread_local_c(), error_context_deallocate);
         }
stringify() [1/8]
const char * icedb::error::stringify (error_types et)
Definition at line 4 of file errorTypes.cpp.
References xArrayOutOfBounds, xAssert, xBadFunctionMap, xBadFunctionReturn, xBadInput, xBlockedHookLoad, xBlockedHookUnload, xCannotFindReference, xDimensionMismatch, xDivByZero, xDLLerror, xDLLversionMismatch, xDuplicateHook, xEmptyInputFile, xFallbackTemplate, xFileExists, xHandleInUse, xHandleNotOpen, xInvalidRange, xKeyExists, xMissingConfigurationFile, xMissingFile, xMissingFolder, xMissingFrequency, xMissingHash, xMissingKey, xMissingVariable, xModelOutOfRange, xNullPointer, xOtherError, xPathExistsWrongType, xSingular, xSymbolNotFound, xTypeMismatch, xUnimplementedFunction, xUnknownFileFormat, xUnsupportedIOaction, and xUpcast.
{
             if (et == error_types::xDivByZero) return "Division by zero.";
             else if (et == error_types::xInvalidRange) return "Invalid range.";
             else if (et == error_types::xAssert) return "Assertion failed.";
             else if (et == error_types::xBadInput) return "Bad or nonsensical input.";
             else if (et == error_types::xNullPointer) return "An unexpected null pointer was encountered.";
             else if (et == error_types::xModelOutOfRange) return "Model out of range.";
             else if (et == error_types::xMissingFrequency) return "Missing data for this frequency.";
             else if (et == error_types::xEmptyInputFile) return "Input file is empty.";
             else if (et == error_types::xMissingFolder) return "Missing folder in path.";
             else if (et == error_types::xMissingFile) return "Missing file.";
             else if (et == error_types::xMissingVariable) return "Missing variable in a saved structure.";
             else if (et == error_types::xMissingConfigurationFile) return "Cannot find an appropriate configuration file.";
             else if (et == error_types::xFileExists) return "File to be opened for writing already exists.";
             else if (et == error_types::xPathExistsWrongType) return "Path exists, but wrong type (i.e. file vs. directory).";
             else if (et == error_types::xTypeMismatch) return "Variable does not have the correct type.";
             else if (et == error_types::xUnknownFileFormat) return "Unknown file format.";
             else if (et == error_types::xMissingKey) return "Key not found in map.";
             else if (et == error_types::xMissingHash) return "Cannot find hash to load.";
             else if (et == error_types::xKeyExists) return "Key already exists in map.";
             else if (et == error_types::xUnimplementedFunction) return "Unimplemented function.";
             else if (et == error_types::xFallbackTemplate) return "Reached point in code that is the fallback template. Missing the appropriate template specialization.";
             else if (et == error_types::xArrayOutOfBounds) return "An array went out of bounds.";
             else if (et == error_types::xDimensionMismatch) return "An array went out of bounds.";
             else if (et == error_types::xSingular) return "Singular matrix detected.";
             else if (et == error_types::xDLLversionMismatch) return "Attempting to load a DLL that is compiled against an incompatible library version.";
             else if (et == error_types::xDuplicateHook) return "Attempting to load same DLL twice.";
             else if (et == error_types::xHandleInUse) return "DLL handle is currently in use, but the code wants to overwrite it.";
             else if (et == error_types::xHandleNotOpen) return "Attempting to access unopened DLL handle.";
             else if (et == error_types::xSymbolNotFound) return "Cannot find symbol in DLL.";
             else if (et == error_types::xBadFunctionMap) return "DLL symbol function map table is invalid.";
             else if (et == error_types::xBadFunctionReturn) return "DLL symbol map table is invalid.";
             else if (et == error_types::xBlockedHookLoad) return "Another hook blocked the load operation (for DLLs).";
             else if (et == error_types::xBlockedHookUnload) return "Another DLL depends on the one that you are unloading.";
             else if (et == error_types::xDLLerror) return "Unspecified DLL ICEDB_LOG_ERROR.";
             else if (et == error_types::xUpcast) return "Plugin failure: cannot cast base upwards to a derived class provided by a plugin. Usually means that no matching plugin can be found.";
             else if (et == error_types::xCannotFindReference) return "Cannot find reference in file.";
             else if (et == error_types::xOtherError) return "Nonspecific ICEDB_LOG_ERROR.";
             else if (et == error_types::xUnsupportedIOaction) return "Unsupported IO action.";
             else return "INVALID - stringify does not have the appropriate ICEDB_LOG_ERROR type!";
         }
stringify() [2/8]
template<class StringType > StringType icedb::error::stringify (error_code_t err)
Definition at line 46 of file error.hpp.
References DL_ICEDB, and stringify().
 { return StringType(); }
stringify() [3/8]
template<> DL_ICEDB std::string icedb::error::stringify (error_code_t err)
Definition at line 46 of file error.hpp.
 { return StringType(); }
stringify() [4/8]
template<> DL_ICEDB const char* icedb::error::stringify (error_code_t err)
Definition at line 46 of file error.hpp.
References DL_ICEDB, and stringify().
 { return StringType(); }
stringify() [5/8]
DL_ICEDB void icedb::error::stringify (error_code_t err, std::string & res)
Definition at line 307 of file error.cpp.
References ICEDB_ERRORCODES_MAP.
Referenced by stringify(), stringify< std::string >(), and icedb::error::xError::what().
{
             res = std::string(ICEDB_ERRORCODES_MAP[err]);
         }
stringify() [6/8]
DL_ICEDB void icedb::error::stringify (error_code_t err, const char ** res)
Definition at line 310 of file error.cpp.
References ICEDB_ERRORCODES_MAP.
{
             *res = ICEDB_ERRORCODES_MAP[err];
         }
stringify() [7/8]
DL_ICEDB void icedb::error::stringify (const error_context_pt & err, std::string & res)
Definition at line 313 of file error.cpp.
References ICEDB_error_context_to_message, and ICEDB_error_context_to_message_size.
{
             // A few memory copies occur here. Inefficient, but errors should not occur much in properly running code.
             size_t sz = ICEDB_error_context_to_message_size(err.get());
             //std::unique_ptr<char[]> buf(new char[sz]);
             std::vector<char> buf(sz);
             ICEDB_error_context_to_message(err.get(), sz, buf.data());
             res = std::string(buf.data());
         }
stringify() [8/8]
DL_ICEDB std::string icedb::error::stringify (const error_context_pt & err)
Definition at line 321 of file error.cpp.
References stringify().
{
             std::string res;
             stringify(err, res);
             return res;
         }
stringify< const char * >()
template<> DL_ICEDB const char* icedb::error::stringify< const char *> (error_code_t err)
Definition at line 298 of file error.cpp.
References ICEDB_ERRORCODES_MAP.
{
             return ICEDB_ERRORCODES_MAP[err];
         }
stringify< std::string >()
template<> DL_ICEDB std::string icedb::error::stringify< std::string > (error_code_t err)
Definition at line 293 of file error.cpp.
References stringify().
{
             std::string res;
             stringify(err, res);
             return res;
         }