icedb: icedb::os_functions Namespace Reference
icedb::os_functions Namespace Reference
Namespaces
unix
vars
win
Functions
bool populateOSstrings ()
bool pidExists (int pid)
int getPID ()
int getPPID (int pid)
void libEntry (int argc, char **argv)
void waitOnExit (bool val)
bool waitOnExit ()
const char * getUserName ()
const char * getHostName ()
const char * getAppConfigDir ()
const char * getHomeDir ()
const char * getLibDir ()
const char * getAppDir ()
const char * getPluginDir ()
const char * getLibPath ()
const char * getAppPath ()
const char * getCWD ()
Function Documentation
getAppConfigDir()
DL_ICEDB const char * icedb::os_functions::getAppConfigDir ()
See also
ICEDB_getAppConfigDir
Definition at line 946 of file os_functions.cpp.
References ICEDB_getAppConfigDir().
 { return ICEDB_getAppConfigDir(); }
getAppDir()
DL_ICEDB const char * icedb::os_functions::getAppDir ()
Definition at line 949 of file os_functions.cpp.
References icedb::os_functions::vars::appDir, and ICEDB_getAppDirI().
 { ICEDB_getAppDirI(); return appDir.c_str(); }
getAppPath()
DL_ICEDB const char * icedb::os_functions::getAppPath ()
Definition at line 952 of file os_functions.cpp.
References icedb::os_functions::vars::appPath, and ICEDB_getAppDirI().
 { ICEDB_getAppDirI(); return appPath.c_str(); }
getCWD()
DL_ICEDB const char * icedb::os_functions::getCWD ()
Definition at line 953 of file os_functions.cpp.
References icedb::os_functions::vars::CWD, and ICEDB_getCWDI().
 { ICEDB_getCWDI(); return CWD.c_str(); }
getHomeDir()
DL_ICEDB const char * icedb::os_functions::getHomeDir ()
See also
ICEDB_getHomeDir
Definition at line 947 of file os_functions.cpp.
References ICEDB_getHomeDir().
 { return ICEDB_getHomeDir(); }
getHostName()
DL_ICEDB const char * icedb::os_functions::getHostName ()
See also
ICEDB_getHostName
Definition at line 945 of file os_functions.cpp.
References ICEDB_getHostName().
 { return ICEDB_getHostName(); }
getLibDir()
DL_ICEDB const char * icedb::os_functions::getLibDir ()
Definition at line 948 of file os_functions.cpp.
References ICEDB_getLibDirI(), and icedb::os_functions::vars::libDir.
 { ICEDB_getLibDirI(); return libDir.c_str(); }
getLibPath()
DL_ICEDB const char * icedb::os_functions::getLibPath ()
Definition at line 951 of file os_functions.cpp.
References ICEDB_getLibDirI(), and icedb::os_functions::vars::libPath.
 { ICEDB_getLibDirI(); return libPath.c_str(); }
getPID()
DL_ICEDB int icedb::os_functions::getPID ()
See also
ICEDB_getPID
Definition at line 939 of file os_functions.cpp.
References ICEDB_getPID().
Referenced by ICEDB_enumModules().
 { return ICEDB_getPID(); }
getPluginDir()
DL_ICEDB const char * icedb::os_functions::getPluginDir ()
Definition at line 950 of file os_functions.cpp.
References ICEDB_getPluginDirI(), and icedb::os_functions::vars::pluginDir.
 { ICEDB_getPluginDirI(); return pluginDir.c_str(); }
getPPID()
DL_ICEDB int icedb::os_functions::getPPID (int pid)
See also
ICEDB_getPPID
Definition at line 940 of file os_functions.cpp.
References ICEDB_getPPID().
 { return ICEDB_getPPID(pid); }
getUserName()
DL_ICEDB const char * icedb::os_functions::getUserName ()
See also
ICEDB_getUserName
Definition at line 944 of file os_functions.cpp.
References ICEDB_getUserName().
 { return ICEDB_getUserName(); }
libEntry()
DL_ICEDB void icedb::os_functions::libEntry (int argc, char ** argv)
See also
ICEDB_libEntry
Definition at line 941 of file os_functions.cpp.
References ICEDB_libEntry().
 { ICEDB_libEntry(argc, argv); }
pidExists()
DL_ICEDB bool icedb::os_functions::pidExists (int pid)
See also
ICEDB_pidExists
Definition at line 938 of file os_functions.cpp.
References ICEDB_pidExists().
 { bool res = false; ICEDB_pidExists(pid, res); return res; }
populateOSstrings()
bool icedb::os_functions::populateOSstrings ()
Definition at line 265 of file os_functions.cpp.
References icedb::os_functions::vars::appConfigDir, icedb::os_functions::vars::homeDir, icedb::os_functions::vars::hostname, ICEDB_error_context_add_string2, ICEDB_error_context_create, ICEDB_error_getOSname, ICEDB_ERRORCODES_OS, ICEDB_ERRORCODES_UNIMPLEMENTED, ICEDB_free(), ICEDB_malloc(), icedb::os_functions::vars::m_sys_names, and icedb::os_functions::vars::username.
Referenced by ICEDB_getAppConfigDir(), ICEDB_getHomeDir(), ICEDB_getHostName(), and ICEDB_getUserName().
{
             using namespace icedb::os_functions::vars;
             std::lock_guard<std::mutex> lock(m_sys_names);
             // Because of the mutex lock, all of the getlogin functions are safe.
             if (username.size()) return true;
             // Username
 #if defined(ICEDB_OS_WINDOWS)
             BOOL res = false;
             const DWORD clen = 256;
             DWORD len = clen;
             TCHAR hname[clen];
             res = GetUserName(hname, &len);
             if (res) username = win::convertStr(hname);
             else goto funcErrorOS;
             res = GetComputerName(hname, &len);
             if (res) hostname = win::convertStr(hname);
             else goto funcErrorOS;
             HRESULT resl = false;
             wchar_t* happname = nullptr;
             res = SHGetKnownFolderPath(FOLDERID_LocalAppData, 0, NULL, &happname);
             if (resl == S_OK) appConfigDir = win::convertStr(happname);
             else goto funcErrorOS;
             wchar_t* hhomename = nullptr;
             res = SHGetKnownFolderPath(FOLDERID_Profile, 0, NULL, &hhomename);
             if (resl == S_OK) homeDir = win::convertStr(hhomename);
             else goto funcErrorOS;
             goto done;
             funcErrorOS:
                 DWORD errn = GetLastError();
                 auto err = ICEDB_error_context_create(ICEDB_ERRORCODES_OS);
                 const char* osname = ICEDB_error_getOSname();
                 ICEDB_error_context_add_string2(err, "OS_id", osname);
                 char errns[50];
                 snprintf(errns, 50, "%d", errn);
                 ICEDB_error_context_add_string2(err, "OS_errno", errns);
                 if (!username.size()) ICEDB_error_context_add_string2(err, "OS_func", "GetUserName");
                 else if (!hostname.size()) ICEDB_error_context_add_string2(err, "OS_func", "GetComputerName");
                 else if (!appConfigDir.size()) ICEDB_error_context_add_string2(err, "OS_func", "SHGetKnownFolderPath app config dir");
                 else if (!homeDir.size()) ICEDB_error_context_add_string2(err, "OS_func", "SHGetKnownFolderPath profile dir");
             done:
                 if (happname) CoTaskMemFree(static_cast<void*>(happname));
                 if (hhomename) CoTaskMemFree(static_cast<void*>(hhomename));
 #elif defined(__unix__) || defined(__APPLE__)
             const size_t len = 65536;
             char hname[len];
             int res = 0;
             char* envres = NULL;
             if ((envres = getenv("USER"))) username = std::string(envres);
             else if ((envres = getenv("LOGNAME"))) username = std::string(envres);
             if (!username.size()) {
 #if defined(_POSIX_C_SOURCE)
 #if _POSIX_C_SOURCE >= 199506L
                 res = getlogin_r(hname, len); // getlogin and getlogin_r have problems. Avoid.
                 if (!res) username = std::string(hname);
 #else
                 if ((envres = getlogin())) username = std::string(envres);
 #endif
                 // Has getpwuid_r
                 if (!username.size()) {
                     uid_t uid = geteuid();
                     struct passwd* ps = (passwd*) ICEDB_malloc(sizeof(passwd));
                     struct passwd** pres; // A pointer to the result (or NULL on failure) is stored here.
                     res = getpwuid_r(uid, ps, hname, len, pres);
                     if ((res == 0) && pres) {
                         username = std::string(ps->pw_name);
                     }
                     ICEDB_free(ps);
                 }
 #else
                 // May have getpwuid
                 uid_t uid = geteuid();
                 struct passwd* ps = getpwuid(uid);
                 if (ps) username = std::string(ps->pw_name);
 #endif
             }
             // Hostname
             res = gethostname(hname, len); // May be empty
             if (hname[0]) hostname = std::string(hname);
             // Home dir
             if ((envres = getenv("HOME"))) homeDir = std::string(envres);
             if (!homeDir.size())
             {
 #if defined(_POSIX_C_SOURCE) || defined(_BSD_SOURCE) || defined(_SVID_SOURCE)
                 struct passwd pw, *pwp;
                 int res = getpwuid_r(geteuid(), &pw, hname, len, &pwp);
                 if (res == 0) {
                     const char *homedir = pw.pw_dir;
                     homeDir = std::string(homedir);
                 }
 #else
                 struct passwd* ps = getpwuid(geteuid());
                 if (ps) homeDir = std::string(ps->pw_dir);
 #endif
             }
             if (!homeDir.size()) goto funcErrorOS;
             // App config dir
             if ((envres = getenv("XDG_CONFIG_HOME"))) appConfigDir = std::string(envres);
             else {
                 appConfigDir = homeDir;
                 appConfigDir.append("/.config");
             }
             goto done;
         funcErrorOS:
             {
                 auto err = ICEDB_error_context_create(ICEDB_ERRORCODES_OS);
                 const char* osname = ICEDB_error_getOSname();
                 ICEDB_error_context_add_string2(err, "OS_id", osname);
                 if (!username.size()) ICEDB_error_context_add_string2(err, "OS_func", "getlogin_r");
                 else if (!hostname.size()) ICEDB_error_context_add_string2(err, "OS_func", "gethostname");
                 else if (!appConfigDir.size()) ICEDB_error_context_add_string2(err, "OS_func", "getEnviron app config dir");
                 else if (!homeDir.size()) ICEDB_error_context_add_string2(err, "OS_func", "getEnviron profile dir");
             }
         done:
 #endif
             auto ctxerr = ICEDB_error_context_create(ICEDB_ERRORCODES_UNIMPLEMENTED);
             const char* cosname = ICEDB_error_getOSname();
             ICEDB_error_context_add_string2(ctxerr, "OS_id", cosname);
             return false;
         }
waitOnExit() [1/2]
DL_ICEDB void icedb::os_functions::waitOnExit (bool val)
See also
ICEDB_waitOnExitSet
Definition at line 942 of file os_functions.cpp.
References ICEDB_waitOnExitSet().
 { ICEDB_waitOnExitSet(val); }
waitOnExit() [2/2]
DL_ICEDB bool icedb::os_functions::waitOnExit ()
See also
ICEDB_waitOnExitGet
Definition at line 943 of file os_functions.cpp.
References ICEDB_waitOnExitGet().
 { return ICEDB_waitOnExitGet(); }