icedb: scatdb::plugins::builtin::shape Namespace Reference
scatdb::plugins::builtin::shape Namespace Reference
Classes
struct shape_text_handle
Functions
std::shared_ptr< IOhandler > export_raw (std::shared_ptr< IOhandler > sh, std::shared_ptr< options > opts, const std::shared_ptr< const ::scatdb::shape::shapeIO > s)
std::shared_ptr< IOhandler > export_ddscat (std::shared_ptr< IOhandler > sh, std::shared_ptr< options > opts, const std::shared_ptr< const ::scatdb::shape::shapeIO > s)
void register_shape_text ()
std::shared_ptr<::scatdb::shape::shape > readDDSCAT (const char *in)
std::shared_ptr<::scatdb::shape::shape > readTextRaw (const char *iin)
Simple file assuming one substance, with 3-column rows, each representing a single point.
void readHeader (const char *in, std::string &desc, size_t &np, std::shared_ptr<::scatdb::shape::shapeHeaderStorage_t > hdr, size_t &headerEnd)
void readTextContents (const char *iin, size_t headerEnd, std::shared_ptr<::scatdb::shape::shapeStorage_t > data)
std::shared_ptr<::scatdb::shape::shape > readTextFile (const std::string &filename)
void writeDDSCAT (const std::string &filename, ::scatdb::shape::shape_ptr)
void writeTextRaw (const std::string &filename, ::scatdb::shape::shape_ptr)
Function Documentation
export_ddscat()
std::shared_ptr<IOhandler> scatdb::plugins::builtin::shape::export_ddscat (std::shared_ptr< IOhandler > sh, std::shared_ptr< options > opts, const std::shared_ptr< const ::scatdb::shape::shapeIO > s)
Definition at line 88 of file shapeIOtext.cpp.
Referenced by scatdb::registry::write_file_type_multi<::scatdb::shape::shapeIO >().
{
                     auto h = prepHandle<shape_text_handle>(sh, opts, std::string(PLUGINID));
                     if (!h->out) SDBR_throw(scatdb::error::error_types::xOtherError)
                         .add<std::string>("Reason", "Output stream not set. Wrong handle opening io type!");
                     using namespace scatdb::shape::backends;
                     for (const auto &i : s->shapes) {
                         // Write header
                         *(h->out.get()) << i->getDescription() << std::endl;
                         const int fw = 7;
                         auto hrd = i->getHeader();
                         *(h->out.get()) << std::left << std::setw(fw) << i->numPoints() << " = NAT" << std::endl
                             << std::left << std::setw(fw) << (*(hrd.get()))(0, A1) << " "
                             << std::left << std::setw(fw) << (*(hrd.get()))(1, A1) << " "
                             << std::left << std::setw(fw) << (*(hrd.get()))(2, A1) << " = target vector a1 (in TF)\n"
                             << std::left << std::setw(fw) << (*(hrd.get()))(0, A2) << " "
                             << std::left << std::setw(fw) << (*(hrd.get()))(1, A2) << " "
                             << std::left << std::setw(fw) << (*(hrd.get()))(2, A2) << " = target vector a2 (in TF)\n"
                             << std::left << std::setw(fw) << (*(hrd.get()))(0, D) << " "
                             << std::left << std::setw(fw) << (*(hrd.get()))(1, D) << " "
                             << std::left << std::setw(fw) << (*(hrd.get()))(2, D) << " = d_x/d d_y/d d_z/d (normally 1 1 1)\n"
                             << std::left << std::setw(fw) << (*(hrd.get()))(0, X0) << " "
                             << std::left << std::setw(fw) << (*(hrd.get()))(1, X0) << " "
                             << std::left << std::setw(fw) << (*(hrd.get()))(2, X0) << " = X0(1-3) = location of lattice of \"target origin\"\n"
                             << "J       JX      JY      JZ  ICOMP,X ICOMP,Y ICOMP,Z\n";
                         // Write points
                         auto pts = i->getPoints();
                         size_t numPts = i->numPoints();
                         const long linesz = 200;
                         const long sz = (long)numPts * linesz;
                         std::unique_ptr<char[]> buf(new char[sz]);
                         long srem = sz;
                         char* cur = buf.get();
                         // Using the printf-based functions, since they are faster.
                         for (int i = 0; i < (int)numPts; ++i) {
                             const auto &b = pts->block<1, scatdb::shape::backends::NUM_SHAPECOLS>(i, 0);
                             long sl = sprintf_s(cur, srem, "%*d%*d%*d%*d%*d%*d%*d\n",
                                 -8, (int)b(0), -5, (int)b(1), -5, (int)b(2), -5, (int)b(3),
                                 -5, (int)b(4), -5, (int)b(5), -5, (int)b(6));
                             srem -= sl;
                             cur += sl;
                         }
                         *(h->out.get()) << buf.get();
                     }
                     return h;
                 }
export_raw()
std::shared_ptr<IOhandler> scatdb::plugins::builtin::shape::export_raw (std::shared_ptr< IOhandler > sh, std::shared_ptr< options > opts, const std::shared_ptr< const ::scatdb::shape::shapeIO > s)
Definition at line 55 of file shapeIOtext.cpp.
Referenced by scatdb::registry::write_file_type_multi<::scatdb::shape::shapeIO >().
{
                     auto h = prepHandle<shape_text_handle>(sh, opts, std::string(PLUGINID));
                     if (!h->out) SDBR_throw(scatdb::error::error_types::xOtherError)
                         .add<std::string>("Reason", "Output stream not set. Wrong handle opening io type!");
                     std::string delim = opts->getVal<std::string>("delimiter", "\t");
                     for (const auto &i : s->shapes) {
                         // Write header
                         *(h->out.get()) << i->hash().string() << "\nID" << delim << "x" << delim << "y" << delim <<"z"
                             << delim << "IX" << delim << "IY" << delim << "IZ\n";
                         // Write points
                         auto pts = i->getPoints();
                         size_t numPts = i->numPoints();
                         const long linesz = 200;
                         const long sz = (long) numPts * linesz;
                         std::unique_ptr<char[]> buf(new char[sz]);
                         long srem = sz;
                         const char* d = delim.c_str();
                         char* cur = buf.get();
                         // Using the printf-based functions, since they are faster.
                         for (int i = 0; i < (int)numPts; ++i) {
                             const auto &b = pts->block<1, scatdb::shape::backends::NUM_SHAPECOLS>(i, 0);
                             long sl = sprintf_s(cur, srem, "%d%s%d%s%d%s%d%s%d%s%d%s%d\n",
                                 (int)b(0), d, (int)b(1), d, (int)b(2), d, (int)b(3), d,
                                 (int)b(4), d, (int)b(5), d, (int)b(6));
                             srem -= sl;
                             cur += sl;
                         }
                         *(h->out.get()) << buf.get();
                     }
                     return h;
                 }
readDDSCAT()
std::shared_ptr<::scatdb::shape::shape> scatdb::plugins::builtin::shape::readDDSCAT (const char * in)
Todo:
Change ingest to show absolute path
Definition at line 107 of file shapeIOtextParsers.cpp.
References icedb::Examples::Shapes::readHeader(), and icedb::Examples::Shapes::readTextContents().
Referenced by icedb::Examples::Shapes::m_atoi(), scatdb::registry::read_file_type_multi<::scatdb::shape::shapeIO >(), icedb::Examples::Shapes::readDDSCATtextContents(), icedb::Examples::Shapes::readRawText(), and icedb::Examples::Shapes::readTextFile().
             {
                 std::shared_ptr<::scatdb::shape::shape> s = ::scatdb::shape::shape::generate();
                 std::string str(in);
                 std::string desc;
                 std::shared_ptr<::scatdb::shape::shapeStorage_t> data(
                     new ::scatdb::shape::shapeStorage_t);
                 std::shared_ptr<::scatdb::shape::shapeHeaderStorage_t> hdr
                 (new ::scatdb::shape::shapeHeaderStorage_t);
                 size_t headerEnd = 0, numPoints = 0;
                 readHeader(str.c_str(), desc, numPoints, hdr, headerEnd);
                 data->resize((int)numPoints, ::scatdb::shape::backends::NUM_SHAPECOLS);
                 readTextContents(str.c_str(), headerEnd, data);
                 //auto ing = scatdb::generateIngest();
                 //ing->sources.push_back(opts->getVal<std::string>("filename", "Unknown file"));
                 //s->setIngestInformation(ing);
                 s->setDescription(desc);
                 s->setHeader(hdr);
                 s->setPoints(data);
                 return s;
             }
readHeader()
void scatdb::plugins::builtin::shape::readHeader (const char * in, std::string & desc, size_t & np, std::shared_ptr<::scatdb::shape::shapeHeaderStorage_t > hdr, size_t & headerEnd)
Definition at line 129 of file shapeIOtextParsers.cpp.
Referenced by icedb::Examples::Shapes::m_atoi(), icedb::Examples::Shapes::readDDSCAT(), and icedb::Examples::Shapes::readDDSCATtextContents().
             {
                 using namespace std;
                 // Do header processing using istreams.
                 // The previous method used strings, but this didn't work with compressed reads.
                 //size_t &pend = headerEnd;
                 const char* pend = in;
                 const char* pstart = in;
                 // The header is seven lines long
                 for (size_t i = 0; i < 7; i++)
                 {
                     pstart = pend;
                     pend = strchr(pend, '\n');
                     pend++; // Get rid of the newline
                             //pend = in.find_first_of("\n", pend+1);
                     string lin(pstart, pend - pstart - 1);
                     if (*(lin.rbegin()) == '\r') lin.pop_back();
                     //std::getline(in,lin);
                     size_t posa = 0, posb = 0;
                     Eigen::Array3f *v = nullptr;
                     switch (i)
                     {
                     case 0: // Title line
                         desc = lin;
                         break;
                     case 1: // Number of dipoles
                     {
                         // Seek to first nonspace character
                         posa = lin.find_first_not_of(" \t\n", posb);
                         // Find first space after this position
                         posb = lin.find_first_of(" \t\n", posa);
                         size_t len = posb - posa;
                         string s = lin.substr(posa, len);
                         np = boost::lexical_cast<size_t>(s);
                         //np = macros::m_atoi<size_t>(&(lin.data()[posa]), len);
                     }
                     break;
                     case 6: // Junk line
                     default:
                         break;
                     case 2: // a1
                     case 3: // a2
                     case 4: // d
                     case 5: // x0
                             // These all have the same structure. Read in three doubles, then assign.
                     {
                         Eigen::Array3f v;
                         for (size_t j = 0; j < 3; j++)
{
                             // Seek to first nonspace character
                             posa = lin.find_first_not_of(" \t\n,", posb);
                             // Find first space after this position
                             posb = lin.find_first_of(" \t\n,", posa);
                             size_t len = posb - posa;
                             string s = lin.substr(posa, len);
                             v(j) = boost::lexical_cast<float>(s);
                             //v(j) = macros::m_atof<float>(&(lin.data()[posa]), len);
                         }
                         hdr->block<3, 1>(0, i - 2) = v;
                     }
                     break;
                     }
                 }
                 headerEnd = (pend - in) / sizeof(char);
             }
readTextContents()
void scatdb::plugins::builtin::shape::readTextContents (const char * iin, size_t headerEnd, std::shared_ptr<::scatdb::shape::shapeStorage_t > data)
Definition at line 201 of file shapeIOtextParsers.cpp.
References anonymous_namespace{shapeIOtextParsers.cpp}::parse_shapefile_entries().
Referenced by icedb::Examples::Shapes::readDDSCAT().
             {
                 using namespace std;
                 //Eigen::Vector3f crdsm, crdsi; // point location and diel entries
                 const char* pa = &iin[headerEnd];
                 const char* pb = strchr(pa + 1, '\0');
                 std::vector<long> parser_vals; //(numPoints*8);
                 size_t numPoints = (size_t)data->rows();
                 parser_vals.reserve(numPoints * 8);
                 parse_shapefile_entries(pa, pb, parser_vals);
                 if (numPoints == 0) SDBR_throw(error::error_types::xBadInput)
                     .add<std::string>("Reason", "Header indicates no dipoles.");
                 if (parser_vals.size() == 0) SDBR_throw(error::error_types::xBadInput)
                     .add<std::string>("Reason", "Unable to parse dipoles.");
                 if (parser_vals.size() < (size_t)((data->rows() - 1) * 7))
                     SDBR_throw(error::error_types::xBadInput)
                     .add<std::string>("Reason", "When reading shapefile, "
                         "header dipoles do not match the number in the file.");
                 for (size_t i = 0; i < numPoints; ++i)
                 {
                     // First field truly is a dummy variable. No correclation with point ordering at all.
                     //size_t pIndex = parser_vals[index].at(7 * i) - 1;
                     size_t pIndex = 7 * i;
                     auto crdsm = data->block<1, scatdb::shape::backends::NUM_SHAPECOLS>(i, 0);
                     for (size_t j = 0; j < 7; j++) // TODO: rewrite using eigen?
                     {
                         float val = (float)parser_vals.at(pIndex + j);
                         crdsm(j) = val;
                     }
                 }
             }
readTextFile()
std::shared_ptr<::scatdb::shape::shape> scatdb::plugins::builtin::shape::readTextFile (const std::string & filename)
Definition at line 343 of file shapeIOtextParsers.cpp.
References icedb::Examples::Shapes::readDDSCAT(), and icedb::Examples::Shapes::readTextRaw().
Referenced by icedb::Examples::Shapes::m_atoi(), icedb::Examples::Shapes::readRawText(), and readtask().
{
                 // Open the file and copy to a string. Check the first few lines to see if any
                 // alphanumeric characters are present. If there are, treat it as a DDSCAT file.
                 // Otherwise, treat as a raw text file.
                 std::ifstream in(filename.c_str());
                 std::ostringstream so;
                 boost::iostreams::copy(in, so);
                 std::string s = so.str();
                 auto end = s.find_first_of("\n\0");
                 if (std::string::npos == s.find_first_not_of("0123456789. \t\n", 0, end)) {
                     return readDDSCAT(s.c_str());
                 }
                 else {
                     return readTextRaw(s.c_str());
                 }
             }
readTextRaw()
std::shared_ptr<::scatdb::shape::shape> scatdb::plugins::builtin::shape::readTextRaw (const char * iin)
Simple file assuming one substance, with 3-column rows, each representing a single point.
Definition at line 287 of file shapeIOtextParsers.cpp.
References anonymous_namespace{shapeIOtextParsers.cpp}::parse_shapefile_entries(), icedb::Examples::Shapes::ShapeRequiredData::particle_constituent_number, icedb::Examples::Shapes::ShapeRequiredData::particle_id, icedb::Examples::Shapes::ShapeRequiredData::particle_scattering_element_composition, icedb::Examples::Shapes::ShapeRequiredData::particle_scattering_element_coordinates, icedb::Examples::Shapes::ShapeRequiredData::particle_scattering_element_number, and icedb::Examples::Shapes::ShapeDataBasic::required.
Referenced by icedb::Examples::Shapes::readTextFile().
             {
                 using namespace std;
                 ShapeDataBasic res;
                 //Eigen::Vector3f crdsm, crdsi; // point location and diel entries
                 const char* pa = iin;
                 const char* pb = strchr(pa + 1, '\0');
                 const char* firstLineEnd = strchr(pa + 1, '\n');
                 // Attempt to guess the number of points based on the number of lines in the file.
                 int guessNumPoints = std::count(pa, pb, '\n');
                 std::vector<long> parser_vals, firstLineVals; //(numPoints*8);
                 parser_vals.reserve(guessNumPoints * 8);
                 parse_shapefile_entries(pa, pb, parser_vals);
                 parse_shapefile_entries(pa, firstLineEnd, firstLineVals);
                 size_t numCols = firstLineVals.size();
                 bool good = false;
                 if (numCols == 3) good = true;
                 if (!good) throw (std::invalid_argument("Bad read"));
                 if (parser_vals.size() == 0) throw (std::invalid_argument("Bad read"));
                 size_t actualNumPoints = parser_vals.size() / numCols;
                 assert(actualNumPoints == guessNumPoints);
                 // Just copy parser_vals into the point array
                 res.required.particle_scattering_element_coordinates.resize(parser_vals.size());
                 for (size_t i = 0; i < parser_vals.size(); ++i)
                     res.required.particle_scattering_element_coordinates[i] = static_cast<float>(parser_vals[i]);
                 // Just one dielectric
                 res.required.particle_scattering_element_number.resize(actualNumPoints);
                 res.required.particle_scattering_element_composition.resize(actualNumPoints);
                 for (size_t i = 1; i <= actualNumPoints; ++i) {
                     res.required.particle_scattering_element_number[i] = static_cast<uint64_t>(i);
                     res.required.particle_scattering_element_composition[i] = 1;
                 }
                 res.required.particle_constituent_number.resize(1);
                 res.required.particle_constituent_number[0] = 1;
                 res.required.particle_id = "";
                 return res;
             }
register_shape_text()
void scatdb::plugins::builtin::shape::register_shape_text ()
writeDDSCAT()
void scatdb::plugins::builtin::shape::writeDDSCAT (const std::string & filename, ::scatdb::shape::shape_ptr)
writeTextRaw()
void scatdb::plugins::builtin::shape::writeTextRaw (const std::string & filename, ::scatdb::shape::shape_ptr)