icedb: icedb::fs::hdf5 Namespace Reference
icedb::fs::hdf5 Namespace Reference
Namespaces
zlib
Typedefs
typedef std::unique_ptr< H5::Group > HDFgroup_t
typedef std::unique_ptr< H5::AtomType > MatchAttributeTypeType
typedef std::unique_ptr< H5::DataSet > HDFdataset_t
Enumerations
enum DataContainerType {
DataContainerType::BASIC, DataContainerType::ARRAY, DataContainerType::COMPOUND, DataContainerType::ENUM,
DataContainerType::OPAQUE, DataContainerType::VLEN, DataContainerType::STRING, DataContainerType::UNKNOWN
}
Functions
int useZLIB ()
void useZLIB (int val)
template<>
MatchAttributeTypeType MatchAttributeType< std::string > ()
template<>
MatchAttributeTypeType MatchAttributeType< const char * > ()
template<>
MatchAttributeTypeType MatchAttributeType< char > ()
template<>
MatchAttributeTypeType MatchAttributeType< uint8_t > ()
template<>
MatchAttributeTypeType MatchAttributeType< uint16_t > ()
template<>
MatchAttributeTypeType MatchAttributeType< uint32_t > ()
template<>
MatchAttributeTypeType MatchAttributeType< uint64_t > ()
template<>
MatchAttributeTypeType MatchAttributeType< int8_t > ()
template<>
MatchAttributeTypeType MatchAttributeType< int16_t > ()
template<>
MatchAttributeTypeType MatchAttributeType< int32_t > ()
template<>
MatchAttributeTypeType MatchAttributeType< int64_t > ()
template<>
MatchAttributeTypeType MatchAttributeType< float > ()
template<>
MatchAttributeTypeType MatchAttributeType< double > ()
template<>
bool isStrType< std::string > ()
template<>
bool isStrType< const char * > ()
template<>
void insertAttr< std::string > (const H5::Attribute &attr, gsl::not_null< H5::AtomType *> vls_type, const std::string &value)
template<>
void loadAttr< std::string > (const H5::Attribute &attr, gsl::not_null< H5::AtomType *> vls_type, std::string &value)
HDFgroup_t openOrCreateGroup (gsl::not_null< ICEDB_H5_GROUP_OWNER_PTR > base, gsl::not_null< const char *> name)
HDFgroup_t openGroup (gsl::not_null< ICEDB_H5_GROUP_OWNER_PTR > base, gsl::not_null< const char *> name)
bool attrExists (gsl::not_null< H5::H5Object *> base, gsl::not_null< const char *> name)
bool groupExists (gsl::not_null< ICEDB_H5_GROUP_OWNER_PTR > base, gsl::not_null< const char *> name)
std::pair< bool, bool > symLinkExists (gsl::not_null< ICEDB_H5_GROUP_OWNER_PTR > base, gsl::not_null< const char *> name)
bool datasetExists (gsl::not_null< ICEDB_H5_GROUP_OWNER_PTR > base, gsl::not_null< const char * > name)
Convenience function to check if a given dataset exists.
std::shared_ptr< H5::DSetCreatPropList > make_plist (size_t rows, size_t cols, bool compress=true)
Creates a property list with the compression + chunking as specified.
std::set< std::string > getGroupMembers (const ICEDB_H5_GETNUMOBJS_OWNER &base)
std::map< std::string, H5G_obj_t > getGroupMembersTypes (const ICEDB_H5_GETNUMOBJS_OWNER &base)
std::vector< std::string > explode (std::string const &s, char delim)
std::vector< std::string > explodeHDF5groupPath (const std::string &s)
H5::Group createGroupStructure (const std::string &groupName, ICEDB_H5_GROUP_OWNER &base)
H5::Group createGroupStructure (const std::vector< std::string > &groups, ICEDB_H5_GROUP_OWNER &base)
unsigned int getHDF5IOflags (fs::IOopenFlags flags)
template<>
bool isType< uint64_t > (hid_t type_id)
template<>
bool isType< int64_t > (hid_t type_id)
template<>
bool isType< uint32_t > (hid_t type_id)
template<>
bool isType< int32_t > (hid_t type_id)
template<>
bool isType< uint16_t > (hid_t type_id)
template<>
bool isType< int16_t > (hid_t type_id)
template<>
bool isType< uint8_t > (hid_t type_id)
template<>
bool isType< int8_t > (hid_t type_id)
template<>
bool isType< float > (hid_t type_id)
template<>
bool isType< double > (hid_t type_id)
template<>
bool isType< char > (hid_t type_id)
template<>
bool isType< std::string > (hid_t type_id)
void readDatasetDimensions (gsl::not_null< H5::DataSet *> dataset, std::vector< size_t > &dims)
size_t readDatasetNumDimensions (gsl::not_null< H5::DataSet *> dataset)
template<class DataType >
MatchAttributeTypeType MatchAttributeType ()
template<>
MatchAttributeTypeType MatchAttributeType< const char * > ()
template<class DataType >
bool isStrType ()
Check to see if output type is for a string.
template<>
bool isStrType< const char * > ()
template<class DataType >
void insertAttr (const H5::Attribute &attr, gsl::not_null< H5::AtomType *> vls_type, const DataType &value)
Handles proper insertion of strings versus other data types.
template<class DataType , class Container >
void addAttr (gsl::not_null< Container *> obj, gsl::not_null< const char *> attname, const DataType &value)
Convenient template to add an attribute of a variable type to a group or dataset.
template<class DataType , class Container >
void addAttrArray (gsl::not_null< Container *> obj, gsl::not_null< const char *> attname, const std::vector< size_t > &dimensionality, const std::vector< DataType > &value)
Writes an array of objects.
template<class DataType , class Container >
void addAttrVector (gsl::not_null< Container *> obj, gsl::not_null< const char *> attname, const std::vector< DataType > &data)
Writes a vector of objects.
template<class DataType >
void loadAttr (const H5::Attribute &attr, gsl::not_null< H5::AtomType *> vls_type, DataType &value)
Handles proper insertion of strings versus other data types.
template<class DataType , class Container >
void readAttr (gsl::not_null< Container *> obj, gsl::not_null< const char *> attname, DataType &value)
Convenient template to read an attribute of a variable.
template<class DataType , class Container >
void readAttrArray (gsl::not_null< Container *> obj, gsl::not_null< const char *> attname, std::vector< size_t > &dims, std::vector< DataType > &value)
Reads an array (or vector) of objects.
template<class DataType , class Container >
void readAttrVector (gsl::not_null< Container *> obj, gsl::not_null< const char *> attname, std::vector< DataType > &value)
Reads an array (or vector) of objects.
template<class Container >
DataContainerType getAttributeGroupingType (gsl::not_null< Container *> obj, gsl::not_null< const char *> attname)
template<class Container >
std::vector< hsize_t > getAttrArrayDimensionality (gsl::not_null< Container *> obj, gsl::not_null< const char *> attname)
template<class DataType , class Container >
HDFdataset_t addDatasetArray (gsl::not_null< Container *> obj, gsl::not_null< const char *> name, size_t rows, size_t cols, gsl::not_null< const DataType *> values, std::shared_ptr< H5::DSetCreatPropList > iplist=nullptr)
template<class DataType , class Container >
HDFdataset_t addDatasetArray (gsl::not_null< Container *> obj, gsl::not_null< const char *> name, size_t rows, gsl::not_null< const DataType *> values, std::shared_ptr< H5::DSetCreatPropList > iplist=nullptr)
template<class DataType , class Container >
gsl::not_null< H5::DataSet * > writeDatasetArray (const std::vector< size_t > &dimensions, gsl::not_null< H5::DataSet *> dset, gsl::not_null< const DataType *> values)
template<class DataType , class Container >
HDFdataset_t createDatasetRaw (gsl::not_null< Container *> parent, gsl::not_null< const char *> name, const std::vector< size_t > &dims, std::shared_ptr< H5::DSetCreatPropList > iplist=nullptr)
template<class Container >
HDFdataset_t readDatasetDimensions (gsl::not_null< Container *> obj, gsl::not_null< const char *> name, std::vector< size_t > &out)
template<class DataType , class Container >
HDFdataset_t readDatasetArray (gsl::not_null< Container *> obj, gsl::not_null< const char *> name, gsl::not_null< DataType *> values)
template<class DataType , class Container >
gsl::not_null< Container * > readDatasetArray (gsl::not_null< Container *> dataset, gsl::not_null< DataType *> values)
template<class Container >
void addNames (gsl::not_null< Container *> obj, const std::string &prefix, size_t num, const std::function< std::string(int)> &s, size_t stride=0, size_t mCols=0)
Add column names to table.
template<class Container >
void addColNames (gsl::not_null< Container *> obj, size_t num, const std::function< std::string(int)> &s, size_t stride=0, size_t mCols=0)
Add column names to table.
template<class DataType >
bool isType (hid_t)
Functions to detect the type of data.
template<class DataType , class Container >
bool isType (gsl::not_null< const Container *> obj, const std::string &attributeName)
template<class DataType , class Container >
bool isType (gsl::not_null< const Container *> obj)
Typedef Documentation
HDFdataset_t
typedef std::unique_ptr<H5::DataSet > icedb::fs::hdf5::HDFdataset_t
Definition at line 268 of file hdf5_supplemental.hpp.
HDFgroup_t
typedef std::unique_ptr<H5::Group > icedb::fs::hdf5::HDFgroup_t
Definition at line 44 of file hdf5_supplemental.hpp.
MatchAttributeTypeType
typedef std::unique_ptr<H5::AtomType> icedb::fs::hdf5::MatchAttributeTypeType
Parameters
std::shared_ptr<H5::AtomType> is a pointer to a newly-constructed matching type
Returns
A pair of (the matching type, a flag indicating passing by pointer or reference)
Definition at line 53 of file hdf5_supplemental.hpp.
Enumeration Type Documentation
DataContainerType
enum icedb::fs::hdf5::DataContainerType strong
Enumerator
BASIC
ARRAY
COMPOUND
ENUM
OPAQUE
VLEN
STRING
UNKNOWN
Definition at line 207 of file hdf5_supplemental.hpp.
{
                 BASIC,
                 ARRAY,
                 COMPOUND,
                 ENUM,
                 OPAQUE,
                 VLEN,
                 STRING,
                 UNKNOWN
             };
Function Documentation
addAttr()
template<class DataType , class Container > void icedb::fs::hdf5::addAttr (gsl::not_null< Container *> obj, gsl::not_null< const char *> attname, const DataType & value)
Convenient template to add an attribute of a variable type to a group or dataset.
Definition at line 89 of file hdf5_supplemental.hpp.
             {
                 auto vls_type = MatchAttributeType<DataType>();
                 //H5::DataSpace att_space(H5S_SCALAR); // Will not work with older NetCDF versions
                 //H5::DataSpace att_space(H5S_SIMPLE);
                 hsize_t dsize = 1; //static_cast<hsize_t>(data.size());
                 H5::DataSpace att_space(1, &dsize);
                 H5::Attribute attr = obj->createAttribute(attname, *vls_type, att_space);
                 insertAttr<DataType>(attr, vls_type.get(), value);
             }
addAttrArray()
template<class DataType , class Container > void icedb::fs::hdf5::addAttrArray (gsl::not_null< Container *> obj, gsl::not_null< const char *> attname, const std::vector< size_t > & dimensionality, const std::vector< DataType > & value)
Writes an array of objects.
Definition at line 102 of file hdf5_supplemental.hpp.
             {
                 auto ftype = MatchAttributeType<DataType>();
                 std::vector<hsize_t> hdims;
                 for (const auto &d : dimensionality)
                     hdims.push_back(static_cast<hsize_t>(d));
                 // This newer form can be read by old NetCDF versions (like 4.1.1, 01/2014)
                 // The older form could only be read by newer NetCDF versions
                 // Of course, NC can only ever read singular-dimension attributes.
                 H5::DataSpace att_space(static_cast<int>(dimensionality.size()), hdims.data());
                 H5::Attribute attr = obj->createAttribute(attname, *(ftype.get()), att_space);
                 attr.write(*ftype, value.data());
                 // Older form cannot be read by older versions of NetCDF.
                 //H5::ArrayType vls_type(*ftype, static_cast<int>(dimensionality.size()), (hdims.data()));
                 //H5::DataSpace att_space(H5S_SCALAR); // Will not work with older NetCDF versions.
                 //H5::Attribute attr = obj->createAttribute(attname, vls_type, att_space);
                 //attr.write(vls_type, value.data());
             }
addAttrVector()
template<class DataType , class Container > void icedb::fs::hdf5::addAttrVector (gsl::not_null< Container *> obj, gsl::not_null< const char *> attname, const std::vector< DataType > & data)
Writes a vector of objects.
Definition at line 129 of file hdf5_supplemental.hpp.
             {
                 auto ftype = MatchAttributeType<DataType>();
                 hsize_t dsize = static_cast<hsize_t>(data.size());
                 H5::DataSpace att_space(1, &dsize);
                 H5::Attribute attr = obj->createAttribute(attname, *(ftype.get()), att_space);
                 attr.write(*ftype, data.data());
             }
addColNames()
template<class Container > void icedb::fs::hdf5::addColNames (gsl::not_null< Container *> obj, size_t num, const std::function< std::string(int)> & s, size_t stride = 0, size_t mCols = 0)
Add column names to table.
Parameters
num is the number of columns
stride allows name duplication (for vectors)
Definition at line 456 of file hdf5_supplemental.hpp.
References createGroupStructure(), explode(), explodeHDF5groupPath(), getHDF5IOflags(), and make_plist().
             {
                 size_t nstride = stride;
                 if (!nstride) nstride = 1;
                 for (size_t i = 0; i < num; ++i)
                 {
                     size_t j = i / nstride;
                     std::string lbl = s((int)j);
                     std::ostringstream fldname;
                     fldname << "COLUMN_";
                     fldname.width(2);
                     fldname.fill('0');
                     fldname << std::right << i << "_NAME";
                     std::string sfldname = fldname.str();
                     if (stride)
                     {
                         size_t k = i % nstride;
                         if (!mCols) {
                             if (k == 0) lbl.append("_X");
                             if (k == 1) lbl.append("_Y");
                             if (k == 2) lbl.append("_Z");
                             if (k == 3) lbl.append("_R");
                         }
                         else {
                             size_t row = k / mCols;
                             size_t col = k % mCols;
                             std::ostringstream iappend;
                             iappend << "_" << row << "_" << col;
                             lbl.append(iappend.str());
                         }
                     }
                     addAttr<std::string, Container>(obj, sfldname.c_str(), lbl);
                 }
             }
addDatasetArray() [1/2]
template<class DataType , class Container > HDFdataset_t icedb::fs::hdf5::addDatasetArray (gsl::not_null< Container *> obj, gsl::not_null< const char *> name, size_t rows, size_t cols, gsl::not_null< const DataType *> values, std::shared_ptr< H5::DSetCreatPropList > iplist = nullptr)
Definition at line 272 of file hdf5_supplemental.hpp.
References useZLIB().
Referenced by addDatasetArray().
             {
                 using namespace H5;
                 std::vector<hsize_t> sz{ (hsize_t)rows, (hsize_t)cols };
                 int dimensionality = 2;
                 if (cols == 1) dimensionality = 1;
                 H5::DataSpace fspace(dimensionality, sz.data());
                 auto ftype = MatchAttributeType<DataType>();
                 std::shared_ptr<DSetCreatPropList> plist;
                 if (iplist) plist = iplist;
                 else
                 {
                     plist = std::shared_ptr<DSetCreatPropList>(new DSetCreatPropList);
                     if (!isStrType<DataType>())
                     {
                         int fillvalue = -1;
                         plist->setFillValue(PredType::NATIVE_INT, &fillvalue);
                         if (useZLIB()) {
                             plist->setChunk(static_cast<int>(sz.size()), sz.data());
                             plist->setDeflate(useZLIB());
                         }
                     }
                 }
                 HDFdataset_t dataset(new DataSet(obj->createDataSet(name, *(ftype.get()),
                     fspace, *(plist.get()))));
                 dataset->write(values, *(ftype.get()));
                 return dataset;
             }
addDatasetArray() [2/2]
template<class DataType , class Container > HDFdataset_t icedb::fs::hdf5::addDatasetArray (gsl::not_null< Container *> obj, gsl::not_null< const char *> name, size_t rows, gsl::not_null< const DataType *> values, std::shared_ptr< H5::DSetCreatPropList > iplist = nullptr)
Definition at line 305 of file hdf5_supplemental.hpp.
References addDatasetArray().
             {
                 return std::move(addDatasetArray(obj, name, rows, 1, values, iplist));
             }
addNames()
template<class Container > void icedb::fs::hdf5::addNames (gsl::not_null< Container *> obj, const std::string & prefix, size_t num, const std::function< std::string(int)> & s, size_t stride = 0, size_t mCols = 0)
Add column names to table.
Parameters
num is the number of columns
stride allows name duplication (for vectors)
Definition at line 429 of file hdf5_supplemental.hpp.
             {
                 size_t nstride = stride;
                 if (!nstride) nstride = 1;
                 for (size_t i = 0; i < num; ++i)
                 {
                     size_t j = i / nstride;
                     std::string lbl = s((int)j);
                     std::ostringstream fldname;
                     fldname << std::string(prefix);
                     fldname.width(2);
                     fldname.fill('0');
                     fldname << std::right << i << "_NAME";
                     std::string sfldname = fldname.str();
                     addAttr<std::string, Container>(obj, sfldname.c_str(), lbl);
                 }
             }
attrExists()
bool icedb::fs::hdf5::attrExists (gsl::not_null< H5::H5Object *> base, gsl::not_null< const char *> name)
Definition at line 88 of file export-hdf5.cpp.
Referenced by getAttrArrayDimensionality().
             {
                 try {
                     H5::Attribute(base->openAttribute(name));
                     return true;
                 }
                 catch (H5::AttributeIException not_found_error) {
                     return false;
                 }
                 catch (H5::FileIException not_found_error) {
                     return false;
                 }
                 catch (H5::GroupIException not_found_error) {
                     return false;
                 }
             }
createDatasetRaw()
template<class DataType , class Container > HDFdataset_t icedb::fs::hdf5::createDatasetRaw (gsl::not_null< Container *> parent, gsl::not_null< const char *> name, const std::vector< size_t > & dims, std::shared_ptr< H5::DSetCreatPropList > iplist = nullptr)
Definition at line 330 of file hdf5_supplemental.hpp.
References useZLIB().
             {
                 using namespace H5;
                 std::vector<hsize_t> sz(dims.size());
                 for (size_t i = 0; i < sz.size(); ++i)
                     sz[i] = static_cast<hsize_t>(dims[i]);
                 DataSpace fspace(static_cast<int>(sz.size()), sz.data());
                 auto ftype = MatchAttributeType<DataType>();
                 std::shared_ptr<DSetCreatPropList> plist;
                 if (iplist) plist = iplist;
                 else
                 {
                     plist = std::shared_ptr<DSetCreatPropList>(new DSetCreatPropList);
                     if (!isStrType<DataType>())
                     {
                         int fillvalue = -1;
                         plist->setFillValue(PredType::NATIVE_INT, &fillvalue);
                         if (useZLIB()) {
                             plist->setChunk(static_cast<int>(sz.size()), sz.data());
                             plist->setDeflate(useZLIB());
                         }
                     }
                 }
                 HDFdataset_t dataset(new DataSet(parent->createDataSet(name, *(ftype.get()),
                     fspace, *(plist.get()))));
                 return dataset;
             }
createGroupStructure() [1/2]
H5::Group icedb::fs::hdf5::createGroupStructure (const std::string & groupName, ICEDB_H5_GROUP_OWNER & base)
Definition at line 205 of file export-hdf5.cpp.
References explode().
Referenced by addColNames(), icedb::Databases::Database_impl::createGroupStructure(), icedb::Databases::Database::indexDatabase(), and icedb::Databases::Database::openDatabase().
{
                 // Using the '/' specifier, pop off the group names and
                 // create groups if necessary in the tree. Return the final group.
                 Expects(groupName.size() > 0);
                 std::string mountStr = groupName;
                 std::replace(mountStr.begin(), mountStr.end(), '\\', '/');
                 std::vector<std::string> groups = explode(mountStr, '/');
                 return std::move(createGroupStructure(groups, base));
             }
createGroupStructure() [2/2]
H5::Group icedb::fs::hdf5::createGroupStructure (const std::vector< std::string > & groups, ICEDB_H5_GROUP_OWNER & base)
Note
This is really awkwardly stated because of an MSVC2017 bug. The HDF5 group copy constructor fails to update its id field, even though the hid_t is a uint64 and the copy is trivial. These 'relocatable references' allow me to avoid these copies through liberal use of std::move.
Definition at line 216 of file export-hdf5.cpp.
References getGroupMembers().
{
                 std::shared_ptr<ICEDB_H5_GROUP_OWNER> current(&base, [](ICEDB_H5_GROUP_OWNER*) {});
                 std::vector<H5::Group> vgrps;
                 //vgrps.push_back(current);
                 //H5::Group current(base);
                 for (const auto &grpname : groups) {
                     if (!grpname.size()) continue; // Skip any empty entries
                     std::set<std::string> members = getGroupMembers(*(current.get()));
                     if (!members.count(grpname)) {
                         vgrps.push_back(std::move(current->createGroup(grpname)));
                         current = std::shared_ptr<H5::Group>(&(*(vgrps.rbegin())), [](H5::Group*) {});
                     }
                     else {
                         //H5::Group newcur = current->openGroup(grpname);
                         //current = newcur;
                         vgrps.push_back(std::move(current->openGroup(grpname)));
                         current = std::shared_ptr<H5::Group>(&(*(vgrps.rbegin())), [](H5::Group*) {});
                     }
                 }
                 return std::move((*(vgrps.rbegin())));
             }
datasetExists()
bool icedb::fs::hdf5::datasetExists (gsl::not_null< ICEDB_H5_GROUP_OWNER_PTR > base, gsl::not_null< const char *> name)
Convenience function to check if a given dataset exists.
Definition at line 137 of file export-hdf5.cpp.
Referenced by getAttrArrayDimensionality().
             {
                 try {
                     H5::DataSet(base->openDataSet(name));
                     return true;
                 }
                 catch (H5::GroupIException not_found_error) {
                     return false;
                 }
                 catch (H5::FileIException not_found_error) {
                     return false;
                 }
             }
explode()
std::vector< std::string > icedb::fs::hdf5::explode (std::string const & s, char delim)
Definition at line 185 of file export-hdf5.cpp.
Referenced by addColNames(), createGroupStructure(), and explodeHDF5groupPath().
             {
                 std::vector<std::string> result;
                 std::istringstream iss(s);
                 for (std::string token; std::getline(iss, token, delim); )
                 {
                     if (token.size())
                         result.push_back(std::move(token));
                 }
                 return result;
             }
explodeHDF5groupPath()
std::vector< std::string > icedb::fs::hdf5::explodeHDF5groupPath (const std::string & s)
Definition at line 199 of file export-hdf5.cpp.
References explode().
Referenced by addColNames(), and icedb::Databases::Database::indexDatabase().
{
                 std::string mountStr = s;
                 std::replace(mountStr.begin(), mountStr.end(), '\\', '/');
                 return explode(mountStr, '/');
             }
getAttrArrayDimensionality()
template<class Container > std::vector<hsize_t> icedb::fs::hdf5::getAttrArrayDimensionality (gsl::not_null< Container *> obj, gsl::not_null< const char *> attname)
Definition at line 241 of file hdf5_supplemental.hpp.
References attrExists(), datasetExists(), and symLinkExists().
             {
                 std::vector<hsize_t> dims;
                 H5::Attribute attr = obj->openAttribute(attname);
                 int dimensionality = attr.getArrayType().getArrayNDims();
                 dims.resize(dimensionality);
                 attr.getArrayType().getArrayDims(dims.data());
                 return dims;
             }
getAttributeGroupingType()
template<class Container > DataContainerType icedb::fs::hdf5::getAttributeGroupingType (gsl::not_null< Container *> obj, gsl::not_null< const char *> attname)
Definition at line 219 of file hdf5_supplemental.hpp.
References ARRAY, BASIC, COMPOUND, ENUM, OPAQUE, STRING, UNKNOWN, and VLEN.
Referenced by icedb::Attributes::pullData().
             {
                 H5::Attribute attr = obj->openAttribute(attname);
                 //const hid_t attrid = attr.getId();
                 H5::DataType dtype = attr.getDataType();
                 //const hid_t dtypeid = dtype.getId();
                 //const H5T_class_t class_type = H5Tget_class(dtypeid);
                 H5T_class_t class_type = dtype.getClass();
                 // I could also use the H5::DataType::detectClass method here...
                 if (class_type == H5T_class_t::H5T_ARRAY) return DataContainerType::ARRAY;
                 else if (class_type == H5T_class_t::H5T_COMPOUND) return DataContainerType::COMPOUND;
                 else if (class_type == H5T_class_t::H5T_ENUM) return DataContainerType::ENUM;
                 else if (class_type == H5T_class_t::H5T_OPAQUE) return DataContainerType::OPAQUE;
                 else if (class_type == H5T_class_t::H5T_INTEGER) return DataContainerType::BASIC;
                 else if (class_type == H5T_class_t::H5T_FLOAT) return DataContainerType::BASIC;
                 else if (class_type == H5T_class_t::H5T_VLEN) return DataContainerType::VLEN;
                 else if (class_type == H5T_class_t::H5T_STRING) return DataContainerType::STRING;
                 return DataContainerType::UNKNOWN;
             }
getGroupMembers()
std::set< std::string > icedb::fs::hdf5::getGroupMembers (const ICEDB_H5_GETNUMOBJS_OWNER & base)
Definition at line 162 of file export-hdf5.cpp.
Referenced by createGroupStructure().
{
                 std::set<std::string> res;
                 const hsize_t numObjs = base.getNumObjs();
                 for (hsize_t i = 0; i < numObjs; ++i)
                 {
                     std::string name = base.getObjnameByIdx(i);
                     res.insert(name);
                 }
                 return res;
             }
getGroupMembersTypes()
std::map< std::string, H5G_obj_t > icedb::fs::hdf5::getGroupMembersTypes (const ICEDB_H5_GETNUMOBJS_OWNER & base)
Definition at line 173 of file export-hdf5.cpp.
Referenced by icedb::Groups::Group_impl::getGroupNames(), and icedb::Tables::CanHaveTables::getTableNames().
{
                 std::map<std::string, H5G_obj_t> res;
                 const hsize_t numObjs = base.getNumObjs();
                 for (hsize_t i = 0; i < numObjs; ++i)
                 {
                     std::string name = base.getObjnameByIdx(i);
                     H5G_obj_t gtype = base.getObjTypeByIdx(i);
                     res[name] = gtype;
                 }
                 return res;
             }
getHDF5IOflags()
unsigned int icedb::fs::hdf5::getHDF5IOflags (fs::IOopenFlags flags)
Todo:
Candidate for constexpr inlining
Definition at line 246 of file export-hdf5.cpp.
References icedb::fs::CREATE, icedb::fs::READ_ONLY, icedb::fs::READ_WRITE, and icedb::fs::TRUNCATE.
Referenced by addColNames(), icedb::Databases::Database::createSampleDatabase(), icedb::Databases::Database::createSingleFileDatabase(), icedb::Databases::Database_impl::makeDatabaseFileStandard(), and icedb::Databases::Database::openDatabase().
{
                 unsigned int Hflags = 0; // HDF5 flags
                 if (flags == fs::IOopenFlags::READ_ONLY) Hflags = H5F_ACC_RDONLY;
                 else if (flags == fs::IOopenFlags::READ_WRITE) Hflags = H5F_ACC_RDWR;
                 else if (flags == fs::IOopenFlags::TRUNCATE) Hflags = H5F_ACC_TRUNC;
                 else if (flags == fs::IOopenFlags::CREATE) Hflags = H5F_ACC_CREAT;
                 return Hflags;
             }
groupExists()
bool icedb::fs::hdf5::groupExists (gsl::not_null< ICEDB_H5_GROUP_OWNER_PTR > base, gsl::not_null< const char *> name)
Definition at line 105 of file export-hdf5.cpp.
             {
                 try {
                     H5::Group( base->openGroup( name ));
                     return true;
                 } catch( H5::GroupIException not_found_error ) {
                     return false;
                 }
                 catch (H5::FileIException not_found_error) {
                     return false;
                 }
             }
insertAttr()
template<class DataType > void icedb::fs::hdf5::insertAttr (const H5::Attribute & attr, gsl::not_null< H5::AtomType *> vls_type, const DataType & value)
Handles proper insertion of strings versus other data types.
Definition at line 81 of file hdf5_supplemental.hpp.
             {
                 attr.write(*vls_type, &value);
             }
insertAttr< std::string >()
template<> void icedb::fs::hdf5::insertAttr< std::string > (const H5::Attribute & attr, gsl::not_null< H5::AtomType *> vls_type, const std::string & value)
Definition at line 44 of file export-hdf5.cpp.
             {
                 attr.write(*vls_type, value);
             }
isStrType()
template<class DataType > bool icedb::fs::hdf5::isStrType ()
Check to see if output type is for a string.
Definition at line 75 of file hdf5_supplemental.hpp.
 { return false; }
isStrType< const char * >() [1/2]
template<> bool icedb::fs::hdf5::isStrType< const char *> ()
Definition at line 42 of file export-hdf5.cpp.
 { return true; }
isStrType< const char * >() [2/2]
template<> bool icedb::fs::hdf5::isStrType< const char *> ()
Definition at line 42 of file export-hdf5.cpp.
 { return true; }
isStrType< std::string >()
template<> bool icedb::fs::hdf5::isStrType< std::string > ()
Definition at line 41 of file export-hdf5.cpp.
 { return true; }
isType() [1/3]
template<class DataType > bool icedb::fs::hdf5::isType (hid_t)
Functions to detect the type of data.
Definition at line 506 of file hdf5_supplemental.hpp.
 { throw(std::invalid_argument("Unsupported type. (icedb::fs::hdf5::isType(hid_t))")); return false; }
isType() [2/3]
template<class DataType , class Container > bool icedb::fs::hdf5::isType (gsl::not_null< const Container *> obj, const std::string & attributeName)
Definition at line 509 of file hdf5_supplemental.hpp.
{
                 H5::Attribute attr = obj->openAttribute(attributeName);
                 return isType<DataType>(attr.getDataType().getId());
             }
isType() [3/3]
template<class DataType , class Container > bool icedb::fs::hdf5::isType (gsl::not_null< const Container *> obj)
Definition at line 514 of file hdf5_supplemental.hpp.
References isType< char >(), isType< double >(), isType< float >(), isType< int16_t >(), isType< int32_t >(), isType< int64_t >(), isType< int8_t >(), isType< uint16_t >(), isType< uint32_t >(), isType< uint64_t >(), and isType< uint8_t >().
{
                 return isType<DataType>(obj->getDataType().getId());
             }
isType< char >()
template<> bool icedb::fs::hdf5::isType< char > (hid_t type_id)
Definition at line 266 of file export-hdf5.cpp.
Referenced by isType().
 { return (H5Tequal(type_id, H5T_NATIVE_CHAR) > 0) ? true : false; }
isType< double >()
template<> bool icedb::fs::hdf5::isType< double > (hid_t type_id)
Definition at line 265 of file export-hdf5.cpp.
Referenced by isType().
 { return (H5Tequal(type_id, H5T_NATIVE_DOUBLE) > 0) ? true : false; }
isType< float >()
template<> bool icedb::fs::hdf5::isType< float > (hid_t type_id)
Definition at line 264 of file export-hdf5.cpp.
Referenced by isType().
 { return (H5Tequal(type_id, H5T_NATIVE_FLOAT) > 0) ? true : false; }
isType< int16_t >()
template<> bool icedb::fs::hdf5::isType< int16_t > (hid_t type_id)
Definition at line 261 of file export-hdf5.cpp.
Referenced by isType().
 { return (H5Tequal(type_id, H5T_NATIVE_INT16) > 0) ? true : false; }
isType< int32_t >()
template<> bool icedb::fs::hdf5::isType< int32_t > (hid_t type_id)
Definition at line 259 of file export-hdf5.cpp.
Referenced by isType().
 { return (H5Tequal(type_id, H5T_NATIVE_INT32) > 0) ? true : false; }
isType< int64_t >()
template<> bool icedb::fs::hdf5::isType< int64_t > (hid_t type_id)
Definition at line 257 of file export-hdf5.cpp.
Referenced by isType().
 { return (H5Tequal(type_id, H5T_NATIVE_INT64) > 0) ? true : false; }
isType< int8_t >()
template<> bool icedb::fs::hdf5::isType< int8_t > (hid_t type_id)
Definition at line 263 of file export-hdf5.cpp.
Referenced by isType().
 { return (H5Tequal(type_id, H5T_NATIVE_INT8) > 0) ? true : false; }
isType< std::string >()
template<> bool icedb::fs::hdf5::isType< std::string > (hid_t type_id)
Definition at line 267 of file export-hdf5.cpp.
{
                 std::shared_ptr<H5::AtomType> a = std::make_shared<H5::StrType>(0, H5T_VARIABLE);
                 return (H5Tequal(type_id, a->getId()) > 0) ? true : false;
             }
isType< uint16_t >()
template<> bool icedb::fs::hdf5::isType< uint16_t > (hid_t type_id)
Definition at line 260 of file export-hdf5.cpp.
Referenced by isType().
 { return (H5Tequal(type_id, H5T_NATIVE_UINT16) > 0) ? true : false; }
isType< uint32_t >()
template<> bool icedb::fs::hdf5::isType< uint32_t > (hid_t type_id)
Definition at line 258 of file export-hdf5.cpp.
Referenced by isType().
 { return (H5Tequal(type_id, H5T_NATIVE_UINT32) > 0) ? true : false; }
isType< uint64_t >()
template<> bool icedb::fs::hdf5::isType< uint64_t > (hid_t type_id)
Definition at line 256 of file export-hdf5.cpp.
Referenced by isType().
 { return (H5Tequal(type_id, H5T_NATIVE_UINT64) > 0) ? true : false; }
isType< uint8_t >()
template<> bool icedb::fs::hdf5::isType< uint8_t > (hid_t type_id)
Definition at line 262 of file export-hdf5.cpp.
Referenced by isType().
 { return (H5Tequal(type_id, H5T_NATIVE_UINT8) > 0) ? true : false; }
loadAttr()
template<class DataType > void icedb::fs::hdf5::loadAttr (const H5::Attribute & attr, gsl::not_null< H5::AtomType *> vls_type, DataType & value)
Handles proper insertion of strings versus other data types.
Definition at line 143 of file hdf5_supplemental.hpp.
             {
                 attr.read(*vls_type, &value);
             }
loadAttr< std::string >()
template<> void icedb::fs::hdf5::loadAttr< std::string > (const H5::Attribute & attr, gsl::not_null< H5::AtomType *> vls_type, std::string & value)
Definition at line 48 of file export-hdf5.cpp.
             {
                 attr.read(*vls_type, value);
                 //attr.write(*vls_type, value);
             }
make_plist()
std::shared_ptr< H5::DSetCreatPropList > icedb::fs::hdf5::make_plist (size_t rows, size_t cols, bool compress)
Creates a property list with the compression + chunking as specified.
Definition at line 151 of file export-hdf5.cpp.
Referenced by addColNames().
             {
                 using namespace H5;
                 const hsize_t chunk[2] = { static_cast<hsize_t>(rows), static_cast<hsize_t>(cols) };
                 auto plist = std::make_shared<H5::DSetCreatPropList>();
                 plist->setChunk(2, chunk);
                 if (compress)
                     plist->setDeflate(6);
                 return plist;
             }
MatchAttributeType()
template<class DataType > MatchAttributeTypeType icedb::fs::hdf5::MatchAttributeType ()
Definition at line 55 of file hdf5_supplemental.hpp.
References MatchAttributeType< char >(), MatchAttributeType< double >(), MatchAttributeType< float >(), MatchAttributeType< int16_t >(), MatchAttributeType< int32_t >(), MatchAttributeType< int64_t >(), MatchAttributeType< int8_t >(), MatchAttributeType< uint16_t >(), MatchAttributeType< uint32_t >(), MatchAttributeType< uint64_t >(), and MatchAttributeType< uint8_t >().
             {
                 throw(std::invalid_argument("Unsupported type during attribute conversion in rtmath::plugins::hdf5::MatchAttributeType."));
             }
MatchAttributeType< char >()
template<> MatchAttributeTypeType icedb::fs::hdf5::MatchAttributeType< char > ()
Definition at line 24 of file export-hdf5.cpp.
Referenced by MatchAttributeType().
 { return std::make_unique<H5::StrType>(0, 1); }
MatchAttributeType< const char * >() [1/2]
template<> MatchAttributeTypeType icedb::fs::hdf5::MatchAttributeType< const char *> ()
Definition at line 23 of file export-hdf5.cpp.
 { return std::make_unique<H5::StrType>(0, H5T_VARIABLE); }
MatchAttributeType< const char * >() [2/2]
template<> MatchAttributeTypeType icedb::fs::hdf5::MatchAttributeType< const char *> ()
Definition at line 23 of file export-hdf5.cpp.
 { return std::make_unique<H5::StrType>(0, H5T_VARIABLE); }
MatchAttributeType< double >()
template<> MatchAttributeTypeType icedb::fs::hdf5::MatchAttributeType< double > ()
Definition at line 37 of file export-hdf5.cpp.
Referenced by MatchAttributeType().
 { return std::make_unique<H5::IntType>(H5::PredType::NATIVE_DOUBLE); }
MatchAttributeType< float >()
template<> MatchAttributeTypeType icedb::fs::hdf5::MatchAttributeType< float > ()
Definition at line 36 of file export-hdf5.cpp.
Referenced by MatchAttributeType().
 { return std::make_unique<H5::IntType>(H5::PredType::NATIVE_FLOAT); }
MatchAttributeType< int16_t >()
template<> MatchAttributeTypeType icedb::fs::hdf5::MatchAttributeType< int16_t > ()
Definition at line 31 of file export-hdf5.cpp.
Referenced by MatchAttributeType().
 { return std::make_unique<H5::IntType>(H5::PredType::NATIVE_INT16); }
MatchAttributeType< int32_t >()
template<> MatchAttributeTypeType icedb::fs::hdf5::MatchAttributeType< int32_t > ()
Definition at line 32 of file export-hdf5.cpp.
Referenced by MatchAttributeType().
 { return std::make_unique<H5::IntType>(H5::PredType::NATIVE_INT32); }
MatchAttributeType< int64_t >()
template<> MatchAttributeTypeType icedb::fs::hdf5::MatchAttributeType< int64_t > ()
Definition at line 33 of file export-hdf5.cpp.
Referenced by MatchAttributeType().
 { return std::make_unique<H5::IntType>(H5::PredType::NATIVE_INT64); }
MatchAttributeType< int8_t >()
template<> MatchAttributeTypeType icedb::fs::hdf5::MatchAttributeType< int8_t > ()
Definition at line 30 of file export-hdf5.cpp.
Referenced by MatchAttributeType().
 { return std::make_unique<H5::IntType>(H5::PredType::NATIVE_INT8); }
MatchAttributeType< std::string >()
template<> MatchAttributeTypeType icedb::fs::hdf5::MatchAttributeType< std::string > ()
Definition at line 22 of file export-hdf5.cpp.
 { return std::make_unique<H5::StrType>(0, H5T_VARIABLE); }
MatchAttributeType< uint16_t >()
template<> MatchAttributeTypeType icedb::fs::hdf5::MatchAttributeType< uint16_t > ()
Definition at line 27 of file export-hdf5.cpp.
Referenced by MatchAttributeType().
 { return std::make_unique<H5::IntType>(H5::PredType::NATIVE_UINT16); }
MatchAttributeType< uint32_t >()
template<> MatchAttributeTypeType icedb::fs::hdf5::MatchAttributeType< uint32_t > ()
Definition at line 28 of file export-hdf5.cpp.
Referenced by MatchAttributeType().
 { return std::make_unique<H5::IntType>(H5::PredType::NATIVE_UINT32); }
MatchAttributeType< uint64_t >()
template<> MatchAttributeTypeType icedb::fs::hdf5::MatchAttributeType< uint64_t > ()
Definition at line 29 of file export-hdf5.cpp.
Referenced by MatchAttributeType().
 { return std::make_unique<H5::IntType>(H5::PredType::NATIVE_UINT64); }
MatchAttributeType< uint8_t >()
template<> MatchAttributeTypeType icedb::fs::hdf5::MatchAttributeType< uint8_t > ()
Definition at line 26 of file export-hdf5.cpp.
Referenced by MatchAttributeType().
 { return std::make_unique<H5::IntType>(H5::PredType::NATIVE_UINT8); }
openGroup()
HDFgroup_t icedb::fs::hdf5::openGroup (gsl::not_null< ICEDB_H5_GROUP_OWNER_PTR > base, gsl::not_null< const char *> name)
Definition at line 75 of file export-hdf5.cpp.
Referenced by icedb::Groups::Group_impl::Group_impl().
             {
                 HDFgroup_t res;
                 try {
                     res=(std::make_unique<H5::Group>(base->openGroup( name )));
                 } catch( H5::GroupIException not_found_error ) {
                     return nullptr;
                 } catch( H5::FileIException not_found_error ) {
                     return nullptr;
                 }
                 return res;
             }
openOrCreateGroup()
HDFgroup_t icedb::fs::hdf5::openOrCreateGroup (gsl::not_null< ICEDB_H5_GROUP_OWNER_PTR > base, gsl::not_null< const char *> name)
Definition at line 62 of file export-hdf5.cpp.
             {
                 HDFgroup_t res;
                 try {
                     res=std::make_unique<H5::Group>( base->openGroup( name ));
                 } catch( H5::GroupIException not_found_error ) {
                     res=std::make_unique<H5::Group>(base->createGroup( name ));
                 } catch( H5::FileIException not_found_error ) {
                     res=std::make_unique<H5::Group>(base->createGroup( name ));
                 }
                 return res;
             }
readAttr()
template<class DataType , class Container > void icedb::fs::hdf5::readAttr (gsl::not_null< Container *> obj, gsl::not_null< const char *> attname, DataType & value)
Convenient template to read an attribute of a variable.
Definition at line 151 of file hdf5_supplemental.hpp.
Referenced by icedb::Attributes::pullData().
             {
                 auto vls_type = MatchAttributeType<DataType>();
                 H5::DataSpace att_space(H5S_SCALAR);
                 H5::Attribute attr = obj->openAttribute(attname); //, *vls_type, att_space);
                 loadAttr<DataType>(attr, vls_type.get(), value);
             }
readAttrArray()
template<class DataType , class Container > void icedb::fs::hdf5::readAttrArray (gsl::not_null< Container *> obj, gsl::not_null< const char *> attname, std::vector< size_t > & dims, std::vector< DataType > & value)
Reads an array (or vector) of objects.
Definition at line 161 of file hdf5_supplemental.hpp.
Referenced by icedb::Attributes::pullData().
             {
                 H5::Attribute attr = obj->openAttribute(attname);
                 int dimensionality = attr.getArrayType().getArrayNDims();
                 Expects(dimensionality > 0);
                 std::vector<hsize_t> sz(static_cast<size_t>(dimensionality));
                 attr.getArrayType().getArrayDims(sz.data());
                 dims.resize(static_cast<size_t>(dimensionality));
                 size_t numElems = 1;
                 for (size_t i = 0; i < dimensionality; ++i) {
                     dims[i] = static_cast<size_t>(sz[i]);
                     numElems *= dims[i];
                 }
                 value.resize(numElems);
                 auto ftype = MatchAttributeType<DataType>();
                 //H5::IntType ftype(H5::PredType::NATIVE_FLOAT);
                 H5::ArrayType vls_type(*ftype, dimensionality, sz.data());
                 //H5::DataSpace att_space(H5S_SCALAR);
                 //H5::Attribute attr = obj->createAttribute(attname, vls_type, att_space);
                 attr.read(vls_type, value.data());
             }
readAttrVector()
template<class DataType , class Container > void icedb::fs::hdf5::readAttrVector (gsl::not_null< Container *> obj, gsl::not_null< const char *> attname, std::vector< DataType > & value)
Reads an array (or vector) of objects.
Definition at line 190 of file hdf5_supplemental.hpp.
Referenced by icedb::Attributes::pullData().
             {
                 /*
                 std::shared_ptr<H5::AtomType> ftype = MatchAttributeType<DataType>();
                 hsize_t dsize = (hsize_t) data.size();
                 H5::DataSpace att_space(1, &dsize);
                 H5::Attribute attr = obj->createAttribute(attname, *(ftype.get()), att_space);
                 attr.write(*ftype, data.data());
                 */
                 H5::Attribute attr = obj->openAttribute(attname);
                 auto ftype = MatchAttributeType<DataType>();
                 H5::DataSpace dspace = attr.getSpace();
                 value.resize(dspace.getSimpleExtentNdims());
                 attr.read(*(ftype.get()), value.data());
             }
readDatasetArray() [1/2]
template<class DataType , class Container > HDFdataset_t icedb::fs::hdf5::readDatasetArray (gsl::not_null< Container *> obj, gsl::not_null< const char *> name, gsl::not_null< DataType *> values)
Definition at line 391 of file hdf5_supplemental.hpp.
             {
                 using namespace H5;
                 HDFdataset_t dataset(new H5::DataSet(obj->openDataSet(name)));
                 H5T_class_t type_class = dataset->getTypeClass();
                 DataSpace fspace = dataset->getSpace();
                 //DataSpace fspace(dimensionality, sz);
                 auto ftype = MatchAttributeType<DataType>();
                 dataset->read(values, *(ftype.get()));
                 return std::move(dataset);
             }
readDatasetArray() [2/2]
template<class DataType , class Container > gsl::not_null<Container*> icedb::fs::hdf5::readDatasetArray (gsl::not_null< Container *> dataset, gsl::not_null< DataType *> values)
Definition at line 409 of file hdf5_supplemental.hpp.
             {
                 using namespace H5;
                 H5T_class_t type_class = dataset->getTypeClass();
                 DataSpace fspace = dataset->getSpace();
                 //DataSpace fspace(dimensionality, sz);
                 auto ftype = MatchAttributeType<DataType>();
                 dataset->read(values, *(ftype.get()));
                 return dataset;
             }
readDatasetDimensions() [1/2]
void icedb::fs::hdf5::readDatasetDimensions (gsl::not_null< H5::DataSet *> dataset, std::vector< size_t > & dims)
Definition at line 273 of file export-hdf5.cpp.
Referenced by icedb::Tables::Table::getDimensions(), icedb::Tables::Table::readAll(), and readDatasetDimensions().
{
                 using namespace H5;
                 const H5T_class_t type_class = dataset->getTypeClass();
                 DataSpace fspace = dataset->getSpace();
                 int rank = fspace.getSimpleExtentNdims();
                 assert(rank >= 0);
                 std::vector<hsize_t> sz(rank);
                 const int dimensionality = fspace.getSimpleExtentDims(sz.data(), NULL);
                 for (size_t i = 0; i < rank; ++i)
                     dims.push_back((size_t)sz[i]);
             }
readDatasetDimensions() [2/2]
template<class Container > HDFdataset_t icedb::fs::hdf5::readDatasetDimensions (gsl::not_null< Container *> obj, gsl::not_null< const char *> name, std::vector< size_t > & out)
Definition at line 366 of file hdf5_supplemental.hpp.
References readDatasetDimensions(), and readDatasetNumDimensions().
             {
                 using namespace H5;
                 HDFdataset_t dataset(new H5::DataSet(obj->openDataSet(name)));
                 H5T_class_t type_class = dataset->getTypeClass();
                 DataSpace fspace = dataset->getSpace();
                 int rank = fspace.getSimpleExtentNdims();
                 std::vector<hsize_t> sz(rank);
                 int dimensionality = fspace.getSimpleExtentDims( sz.data(), NULL);
                 for (size_t i = 0; i < rank; ++i)
                     out.push_back(sz[i]);
                 return dataset;
             }
readDatasetNumDimensions()
size_t icedb::fs::hdf5::readDatasetNumDimensions (gsl::not_null< H5::DataSet *> dataset)
Definition at line 285 of file export-hdf5.cpp.
Referenced by icedb::Tables::Table::getNumDimensions(), and readDatasetDimensions().
{
                 using namespace H5;
                 const H5T_class_t type_class = dataset->getTypeClass();
                 DataSpace fspace = dataset->getSpace();
                 int rank = fspace.getSimpleExtentNdims();
                 assert(rank >= 0);
                 return (size_t)rank;
             }
symLinkExists()
std::pair< bool, bool > icedb::fs::hdf5::symLinkExists (gsl::not_null< ICEDB_H5_GROUP_OWNER_PTR > base, gsl::not_null< const char * > name)
Convenience function to check if a symbolic link exists, and if the object being pointed to also exists.
Returns
std::pair<bool,bool> refers to, respectively, if a symbolic link is found and if the symbolic link is good.
Definition at line 118 of file export-hdf5.cpp.
Referenced by getAttrArrayDimensionality().
             {
                 bool linkexists = false;
                 bool linkgood = false;
                 std::string lloc;
                 try {
                     H5G_stat_t stats;
                     base->getObjinfo(name, false, stats);
                     linkexists = true;
                     //lloc = base->getLinkval(name);
                     base->getObjinfo(name, true, stats);
                     linkgood = true;
                 } catch( H5::GroupIException not_found_error ) {
                 } catch( H5::FileIException not_found_error) {
                 }
                 return std::pair<bool,bool>(linkexists,linkgood);
             }
useZLIB() [1/2]
int icedb::fs::hdf5::useZLIB ()
Definition at line 17 of file export-hdf5.cpp.
References icedb::fs::hdf5::zlib::cval.
Referenced by icedb::Tables::CanHaveTables::_createTable(), addDatasetArray(), createDatasetRaw(), and main().
 { return zlib::cval; }
useZLIB() [2/2]
void icedb::fs::hdf5::useZLIB (int val)
Definition at line 18 of file export-hdf5.cpp.
References icedb::fs::hdf5::zlib::cval.
 { zlib::cval = val; }
writeDatasetArray()
template<class DataType , class Container > gsl::not_null<H5::DataSet*> icedb::fs::hdf5::writeDatasetArray (const std::vector< size_t > & dimensions, gsl::not_null< H5::DataSet *> dset, gsl::not_null< const DataType *> values)
Definition at line 313 of file hdf5_supplemental.hpp.
             {
                 using namespace H5;
                 std::vector<hsize_t> sz(dimensions.size());
                 for (size_t i = 0; i < sz.size(); ++i)
                     sz[i] = static_cast<hsize_t>(dimensions[i]);
                 //DataSpace fspace(static_cast<int>(sz.size()), sz);
                 auto ftype = MatchAttributeType<DataType>();
                 dset->write(values, *(ftype.get()));
                 return dset;
             }