icedb: icedb::versioning Namespace Reference
icedb::versioning Namespace Reference
Namespaces
internal
Classes
struct versionInfo
Typedefs
typedef std::shared_ptr< const versionInfo > versionInfo_p
Functions
ICEDB_ver_match compareVersions (const versionInfo_p a, const versionInfo_p b)
void getLibVersionInfo (versionInfo &out)
versionInfo_p getLibVersionInfo ()
void genVersionInfo (versionInfo &out)
Calculates version string based on compile-time version of external code.
versionInfo_p genVersionInfo ()
void debug_preamble (const versionInfo &v, std::ostream &out=std::cerr)
Provides information about the build environment during compilation.
void debug_preamble (std::ostream &out=std::cerr)
Typedef Documentation
versionInfo_p
typedef std::shared_ptr<const versionInfo> icedb::versioning::versionInfo_p
Definition at line 43 of file versioningForwards.hpp.
Function Documentation
compareVersions()
DL_ICEDB ICEDB_ver_match icedb::versioning::compareVersions (const versionInfo_p a, const versionInfo_p b)
Definition at line 9 of file versioning.cpp.
References ICEDB_VER_COMPATIBLE_1, ICEDB_VER_COMPATIBLE_2, ICEDB_VER_COMPATIBLE_3, ICEDB_VER_EXACT_MATCH, ICEDB_VER_INCOMPATIBLE, tryBool, tryNum, tryNumB, and tryStr.
Referenced by ICEDB_CompareVersions().
         {
             ICEDB_ver_match res = ICEDB_VER_INCOMPATIBLE;
             if (!a || !b) return res;
 #define tryNum(x) if (a->vn[versionInfo:: x] != b->vn[versionInfo:: x]) return res;
 #define tryBool(x) if (a->vb[versionInfo:: x] != b->vb[versionInfo:: x]) return res;
 #define tryStr(x) if (std::strncmp(a-> x, b-> x, versionInfo::charmax ) != 0) return res;
 #define tryNumB(x) if ((a->vn[versionInfo:: x] != b->vn[versionInfo:: x]) && a->vn[versionInfo:: x]) return res;
             // First filter the incompatible stuff
             tryNum(V_VERSIONINFO);
             tryStr(vassembly);
             tryNum(V_MAJOR);
             tryNum(V_MINOR);
             tryBool(V_AMD64);
             tryBool(V_X64);
             tryBool(V_UNIX);
             tryBool(V_APPLE);
             tryBool(V_WIN32);
             tryStr(vboost);
             tryNum(V_MSCVER);
             res = ICEDB_VER_COMPATIBLE_1;
             tryNumB(V_GNUC_MAJ);
             tryNumB(V_MINGW_MAJ);
             tryNumB(V_SUNPRO);
             tryNumB(V_PATHCC_MAJ);
             tryNumB(V_CLANG_MAJ);
             tryNumB(V_INTEL);
             res = ICEDB_VER_COMPATIBLE_2;
             tryNumB(V_GNUC_MIN);
             tryNumB(V_MINGW_MIN);
             tryNumB(V_PATHCC_MIN);
             tryNumB(V_CLANG_MIN);
             tryNum(V_REVISION);
             res = ICEDB_VER_COMPATIBLE_3;
             tryBool(V_OPENMP);
             tryNum(V_SVNREVISION);
             tryStr(vgithash);
             res = ICEDB_VER_EXACT_MATCH;
             return res;
 #undef tryNum
 #undef tryBool
 #undef tryStr
 #undef tryNumB
         }
debug_preamble() [1/2]
void icedb::versioning::debug_preamble (const versionInfo & v, std::ostream & out = std::cerr) inline
Provides information about the build environment during compilation.
This function is designed to provide information on a compiler's build environment. It is a header function because it is designed to reflect the compiler variables of an external project's code.
Parameters
out The output stream that receives the information.
Definition at line 116 of file versioning.hpp.
References icedb::versioning::versionInfo::vb, icedb::versioning::versionInfo::vboost, icedb::versioning::versionInfo::vdate, icedb::versioning::versionInfo::vgitbranch, icedb::versioning::versionInfo::vgithash, icedb::versioning::versionInfo::vn, icedb::versioning::versionInfo::vsdate, icedb::versioning::versionInfo::vssource, icedb::versioning::versionInfo::vsuuid, and icedb::versioning::versionInfo::vtime.
Referenced by ICEDB_WriteLibVersionInfoCC().
         {
             out << "Compiled on " << v.vdate << " at " << v.vtime << std::endl;
             out << "Version " << v.vn[versionInfo::V_MAJOR] << "." << v.vn[versionInfo::V_MINOR]
                 << "." << v.vn[versionInfo::V_REVISION] << std::endl;
             if (v.vgitbranch[0] != '\0') out << "GIT Branch " << v.vgitbranch << std::endl;
             if (v.vgithash[0] != '\0') out << "GIT Hash " << v.vgithash << std::endl;
             if (v.vn[versionInfo::V_SVNREVISION]) out << "SVN Revision " << v.vn[versionInfo::V_SVNREVISION] << std::endl;
             if (v.vsdate[0] != '\0') out << "SVN Revision Date: " << v.vsdate << std::endl;
             if (v.vssource[0] != '\0') out << "SVN Source: " << v.vssource << std::endl;
             if (v.vsuuid[0] != '\0') out << "SVN UUID: " << v.vsuuid << std::endl;
             if (v.vb[versionInfo::V_DEBUG]) out << "Debug Version" << std::endl;
             else out << "Release Version" << std::endl;
             if (v.vb[versionInfo::V_OPENMP]) out << "OpenMP enabled in Compiler" << std::endl;
             else out << "OpenMP disabled in Compiler" << std::endl;
             if (v.vb[versionInfo::V_AMD64] || v.vb[versionInfo::V_X64]) out << "64-bit build" << std::endl;
             if (v.vb[versionInfo::V_UNIX]) out << "Unix / Linux Compile" << std::endl;
             if (v.vb[versionInfo::V_APPLE]) out << "Mac Os X Compile" << std::endl;
             if (v.vb[versionInfo::V_WIN32]) out << "Windows Compile" << std::endl;
             if (v.vn[versionInfo::V_GNUC_MAJ])
                 out << "GNU Compiler Suite " << v.vn[versionInfo::V_GNUC_MAJ] << "."
                 << v.vn[versionInfo::V_GNUC_MIN] << "." << v.vn[versionInfo::V_GNUC_PATCH] << std::endl;
             if (v.vn[versionInfo::V_MINGW_MAJ])
                 out << "MinGW Compiler Suite " << v.vn[versionInfo::V_MINGW_MAJ] << "."
                 << v.vn[versionInfo::V_MINGW_MIN] << std::endl;
             if (v.vn[versionInfo::V_SUNPRO])
                 out << "Sun Studio Compiler Suite " << v.vn[versionInfo::V_SUNPRO] << std::endl;
             if (v.vn[versionInfo::V_PATHCC_MAJ])
                 out << "EKOPath Compiler " << v.vn[versionInfo::V_PATHCC_MAJ] << "."
                 << v.vn[versionInfo::V_PATHCC_MIN] << "." << v.vn[versionInfo::V_PATHCC_PATCH] << std::endl;
             if (v.vb[versionInfo::V_LLVM]) out << "LLVM Compiler Suite" << std::endl;
             if (v.vn[versionInfo::V_CLANG_MAJ])
                 out << "clang compiler " << v.vn[versionInfo::V_CLANG_MAJ] << "."
                 << v.vn[versionInfo::V_CLANG_MIN] << "." << v.vn[versionInfo::V_CLANG_PATCH] << std::endl;
             if (v.vn[versionInfo::V_INTEL])
                 out << "Intel Suite " << v.vn[versionInfo::V_INTEL]
                 << " Date " << v.vn[versionInfo::V_INTEL_DATE] << std::endl;
             if (v.vn[versionInfo::V_MSCVER])
                 out << "Microsoft Visual Studio Compiler Version " << v.vn[versionInfo::V_MSCVER] << std::endl;
             if (v.vboost[0]) out << "Boost version " << v.vboost << std::endl;
             out << std::endl;
             out << std::endl;
         }
debug_preamble() [2/2]
void icedb::versioning::debug_preamble (std::ostream & out = std::cerr) inline
Definition at line 163 of file versioning.hpp.
References genVersionInfo().
         {
             versionInfo v;
             genVersionInfo(v);
             debug_preamble(v, out);
         }
genVersionInfo() [1/2]
void icedb::versioning::genVersionInfo (versionInfo & out) inline
Calculates version string based on compile-time version of external code.
Definition at line 27 of file versioning.hpp.
References ICEDB_COMPAT_strncpy_s(), icedb::versioning::versionInfo::vassembly, icedb::versioning::versionInfo::vb, icedb::versioning::versionInfo::vboost, icedb::versioning::versionInfo::vdate, icedb::versioning::versionInfo::vgitbranch, icedb::versioning::versionInfo::vgithash, icedb::versioning::versionInfo::vn, icedb::versioning::versionInfo::vsdate, icedb::versioning::versionInfo::vssource, icedb::versioning::versionInfo::vsuuid, and icedb::versioning::versionInfo::vtime.
Referenced by getLibVersionInfo().
         {
             for (size_t i = 0; i < versionInfo::V_MAX_INTS; ++i) out.vn[i] = 0;
             for (size_t i = 0; i < versionInfo::V_MAX_BOOLS; ++i) out.vb[i] = false;
             out.vn[versionInfo::V_VERSIONINFO] = 1; // Change this if the structure is modified. Differences are ALWAYS incompatible.
             out.vsdate[0] = '\0'; out.vssource[0] = '\0'; out.vsuuid[0] = '\0';
             out.vboost[0] = '\0'; out.vassembly[0] = '\0';
             ICEDB_COMPAT_strncpy_s(out.vdate, versionInfo::charmax, __DATE__, versionInfo::charmax);
             ICEDB_COMPAT_strncpy_s(out.vtime, versionInfo::charmax, __TIME__, versionInfo::charmax);
             ICEDB_COMPAT_strncpy_s(out.vgithash, versionInfo::charmax, libicedb_GitHash, versionInfo::charmax);
             ICEDB_COMPAT_strncpy_s(out.vgitbranch, versionInfo::charmax, libicedb_GitBranch, versionInfo::charmax);
             out.vn[versionInfo::V_MAJOR] = libicedb_MAJOR;
             out.vn[versionInfo::V_MINOR] = libicedb_MINOR;
             out.vn[versionInfo::V_REVISION] = libicedb_REVISION;
 #ifdef __GNUC__
             out.vn[versionInfo::V_GNUC_MAJ] = __GNUC__;
             out.vn[versionInfo::V_GNUC_MIN] = __GNUC_MINOR__;
             out.vn[versionInfo::V_GNUC_PATCH] = __GNUC_PATCHLEVEL__;
 #endif
 #ifdef __MINGW32__
             out.vn[versionInfo::V_MINGW_MAJ] = __MINGW32_MAJOR_VERSION;
             out.vn[versionInfo::V_MINGW_MIN] = __MINGW32_MINOR_VERSION;
 #endif
 #ifdef __SUNPRO_CC
             out.vn[versionInfo::V_SUNPRO] = __SUNPRO_CC;
 #endif
 #ifdef __PATHCC__
             out.vn[versionInfo::V_PATHCC_MAJ] = __PATHCC__;
             out.vn[versionInfo::V_PATHCC_MIN] = __PATHCC_MINOR__;
             out.vn[versionInfo::V_PATHCC_PATCH] = __PATHCC_PATCHLEVEL__;
 #endif
 #ifdef __llvm__
             out.vb[versionInfo::V_LLVM] = true;
 #endif
 #ifdef __clang__
             out.vn[versionInfo::V_CLANG_MAJ] = __clang_major__;
             out.vn[versionInfo::V_CLANG_MIN] = __clang_minor__;
             out.vn[versionInfo::V_CLANG_PATCH] = __clang_patchlevel__;
 #endif
 #ifdef __INTEL_COMPILER
             out.vn[versionInfo::V_INTEL] = __INTEL_COMPILER;
             out.vn[versionInfo::V_INTEL_DATE] = __INTEL_COMPILER_BUILD_DATE;
 #endif
 #ifdef _MSC_FULL_VER
             out.vn[versionInfo::V_MSCVER] = _MSC_FULL_VER;
 #endif
 #ifdef BOOST_LIB_VERSION
             inline_strncpy_s(out.vboost, versionInfo::charmax, BOOST_LIB_VERSION, versionInfo::charmax);
 #endif
 #ifdef _DEBUG
             out.vb[versionInfo::V_DEBUG] = true;
 #endif
 #ifdef _OPENMP
             out.vb[versionInfo::V_OPENMP] = true;
 #endif
 #ifdef __amd64
             out.vb[versionInfo::V_AMD64] = true;
 #endif
 #ifdef _M_X64
             out.vb[versionInfo::V_X64] = true;
 #endif
 #ifdef __unix__
             out.vb[versionInfo::V_UNIX] = true;
 #endif
 #ifdef __APPLE__
             out.vb[versionInfo::V_APPLE] = true;
 #endif
 #ifdef _WIN32
             out.vb[versionInfo::V_WIN32] = true;
 #endif
         }
genVersionInfo() [2/2]
versionInfo_p icedb::versioning::genVersionInfo () inline
Definition at line 101 of file versioning.hpp.
Referenced by debug_preamble().
{
             std::shared_ptr<versionInfo> res(new versionInfo);
             genVersionInfo(*(res.get()));
             versionInfo_p r(res);
             return r;
         }
getLibVersionInfo() [1/2]
void icedb::versioning::getLibVersionInfo (versionInfo & out)
Definition at line 59 of file versioning.cpp.
References genVersionInfo().
Referenced by getLibVersionInfo(), and ICEDB_getLibVersionInfo().
         {
             genVersionInfo(out);
         }
getLibVersionInfo() [2/2]
DL_ICEDB versionInfo_p icedb::versioning::getLibVersionInfo ()
Definition at line 64 of file versioning.cpp.
References getLibVersionInfo(), ICEDB_BEGIN_DECL_C, and icedb::versioning::internal::ver_int.
         {
             if (internal::ver_int) return internal::ver_int;
             std::shared_ptr<versionInfo> vi(new versionInfo);
             getLibVersionInfo(*(vi.get()));
             internal::ver_int = vi;
             return internal::ver_int;
         }