icedb: icedb Namespace Reference
icedb Namespace Reference
Namespaces
Attributes
Contains everything concerning attributes.
Data_Types
Functions to detect the type of stored data.
Databases
Everything related to opening and manipulating icedb databases.
error
Examples
fs
Groups
All stuff related to Groups.
logging
mem
os_functions
refract
registry
Shapes
All facilities to manipulate particle shapes.
splitSet
Tables
Everything to do with Tables is located in this namespace.
units
Provides convenient runtime conversion functions for converting different units.
versioning
zeros
Typedefs
typedef std::map< std::string, fs::ObjectTypes > ObjectIdPathSet_Type
Functions
ICEDB_SYMBOL_SHARED void * _malloc (size_t numBytes)
ICEDB_SYMBOL_SHARED void _free (void *obj)
template<class T >
T * malloc (size_t numBytes)
template<class T >
void free (T *obj)
Typedef Documentation
ObjectIdPathSet_Type
typedef std::map<std::string, fs::ObjectTypes> icedb::ObjectIdPathSet_Type
Definition at line 41 of file Database.hpp.
Function Documentation
_free()
DL_ICEDB void icedb::_free (void * obj)
Free memory region. Should not be double-freed.
Definition at line 130 of file util.cpp.
References ICEDB_END_DECL, and ICEDB_free().
Referenced by free(), and malloc().
 { return ICEDB_free(obj); }
_malloc()
DL_ICEDB void * icedb::_malloc (size_t numBytes)
Allocate memory in bytes. Generally this is just malloced, but a custom allocator may be substituted.
Definition at line 129 of file util.cpp.
References ICEDB_malloc().
Referenced by malloc().
 { return ICEDB_malloc(numBytes); }
free()
template<class T > void icedb::free (T * obj)
Definition at line 21 of file util.hpp.
References _free().
Referenced by ICEDB_enumModules(), ICEDB_free(), and ICEDB_getAppDirI().
                       {
         _free(static_cast<void*>(obj));
     }
malloc()
template<class T > T* icedb::malloc (size_t numBytes)
Definition at line 13 of file util.hpp.
References _free(), _malloc(), and DL_ICEDB.
Referenced by ICEDB_malloc().
{
         T* res = static_cast<T*>(_malloc(numBytes));
         return res;
     }