icedb: icedb::units::implementations Namespace Reference
icedb::units::implementations Namespace Reference
Classes
class converter_provider_registry
class Converter_registry_provider
struct simpleUnits
struct spectralUnits
struct Unithandler
Opaque object provided to perform unit manipulations.
Typedefs
typedef std::shared_ptr< const Converter_registry_provider > conv_prov_cp
typedef std::shared_ptr< const std::vector< conv_prov_cp > > conv_hooks_t
Functions
std::string _mangle_string (const std::string &inUnits, const std::string &outUnits, const std::string &family)
void _registerBackend (const std::string &inUnits, const std::string &outUnits, const std::string &family, converter_p p)
converter_p _queryBackend (const std::string &inUnits, const std::string &outUnits, const std::string &family)
void _init ()
conv_hooks_t getHooks ()
Variables
std::mutex m_backends
std::map< std::string, converter_p > _backends
std::shared_ptr< std::vector< conv_prov_cp > > _providers
Typedef Documentation
conv_hooks_t
typedef std::shared_ptr<const std::vector<conv_prov_cp> > icedb::units::implementations::conv_hooks_t
Definition at line 27 of file unitsPlugins.hpp.
conv_prov_cp
typedef std::shared_ptr<const Converter_registry_provider> icedb::units::implementations::conv_prov_cp
Definition at line 26 of file unitsPlugins.hpp.
Function Documentation
_init()
void icedb::units::implementations::_init ()
Definition at line 49 of file unitsPlugins.cpp.
References icedb::units::implementations::simpleUnits::canConvert(), and icedb::units::implementations::simpleUnits::constructConverter().
Referenced by icedb::units::converter::canConvert(), icedb::units::conv_spec::conv_spec(), icedb::units::converter::converter(), and icedb::units::converter::getConverter().
{
                 static bool inited = false;
                 if (inited) return;
                 inited = true;
                 //template <class base, class reg, class obj>
                 //  void doRegisterHook(const obj& res)
                 std::shared_ptr<implementations::Converter_registry_provider> res(
                     new implementations::Converter_registry_provider);
                 res->canConvert = simpleUnits::canConvert;
                 res->constructConverter = simpleUnits::constructConverter;
                 static const char* name = "1simple";
                 res->name = name;
                 _providers = std::shared_ptr<std::vector<conv_prov_cp > >(new std::vector<conv_prov_cp >);
                 _providers->push_back(res);
             }
_mangle_string()
std::string icedb::units::implementations::_mangle_string (const std::string & inUnits, const std::string & outUnits, const std::string & family) inline
Definition at line 24 of file unitsPlugins.cpp.
Referenced by _queryBackend(), and _registerBackend().
{
                 std::string res(family);
                 res.append("___");
                 res.append(inUnits);
                 res.append("___");
                 res.append(outUnits);
                 return res;
             }
_queryBackend()
converter_p icedb::units::implementations::_queryBackend (const std::string & inUnits, const std::string & outUnits, const std::string & family)
Definition at line 40 of file unitsPlugins.cpp.
References _mangle_string().
Referenced by icedb::units::converter::generate(), and icedb::units::conv_spec::generate().
{
                 std::string h = _mangle_string(inUnits, outUnits, family);
                 std::lock_guard<std::mutex> mlock(m_backends);
                 converter_p res;
                 if (_backends.count(h)) res = _backends.at(h);
                 return res;
             }
_registerBackend()
void icedb::units::implementations::_registerBackend (const std::string & inUnits, const std::string & outUnits, const std::string & family, converter_p p)
Definition at line 34 of file unitsPlugins.cpp.
References _mangle_string().
Referenced by icedb::units::converter::generate(), and icedb::units::conv_spec::generate().
{
                 std::lock_guard<std::mutex> mlock(m_backends);
                 std::string h = _mangle_string(inUnits, outUnits, family);
                 _backends.emplace(std::pair<std::string, converter_p>(h, p));
             }
getHooks()
conv_hooks_t icedb::units::implementations::getHooks ()
Definition at line 64 of file unitsPlugins.cpp.
References _providers.
Referenced by icedb::units::converter::canConvert(), and icedb::units::converter::getConverter().
{
                 return _providers;
             }
Variable Documentation
_backends
std::map<std::string, converter_p> icedb::units::implementations::_backends
Definition at line 21 of file unitsPlugins.cpp.
_providers
std::shared_ptr<std::vector<conv_prov_cp > > icedb::units::implementations::_providers
Definition at line 22 of file unitsPlugins.cpp.
Referenced by getHooks().
m_backends
std::mutex icedb::units::implementations::m_backends
Definition at line 20 of file unitsPlugins.cpp.