icedb: icedb::Examples::Shapes Namespace Reference
icedb::Examples::Shapes Namespace Reference
Namespaces
ScopedHandles
This makes it much easier to automatically close HDF5 handles that are no longer used.
Classes
struct ShapeCommonOptionalData
struct ShapeDataBasic
struct ShapeRequiredData
Typedefs
typedef std::vector< uint64_t > IntData_t
typedef std::vector< uint8_t > Int8Data_t
typedef std::vector< float > FloatData_t
typedef std::vector< std::string > StringData_t
typedef hid_t MatchType_t
Functions
ShapeDataBasic readTextFile (const std::string &filename)
void readHeader (const char *in, std::string &desc, size_t &np, size_t &headerEnd)
void readDDSCATtextContents (const char *iin, size_t numExpectedPoints, size_t headerEnd, ShapeDataBasic &p)
Read ddscat text contents.
ShapeDataBasic readDDSCAT (const char *in)
void writeDDSCAT (const std::string &filename, const ShapeDataBasic &p)
ShapeDataBasic readRawText (const char *iin)
void writeTextRaw (const std::string &filename, const ShapeDataBasic &p)
size_t strints_array_to_floats (const char *in, const size_t inlen, float *out, const size_t outlen, float &max_element)
size_t array_to_floats (const char *in, const size_t inlen, float *out, const size_t outlen)
template<class T >
T m_atof (const char *x, size_t len)
template<class T >
T m_atoi (const char *x, size_t len)
template<class DataType >
MatchType_t MatchType ()
template<>
MatchType_t MatchType< int32_t > ()
template<>
MatchType_t MatchType< float > ()
template<typename T >
void readDataset (hid_t file_id, const char *dataset_name, std::vector< T > &outdata)
ShapeDataBasic readPSUfile (const std::string &filename)
Reads a Penn State-style geometry file.
Typedef Documentation
FloatData_t
typedef std::vector< float > icedb::Examples::Shapes::FloatData_t
Definition at line 13 of file shape.hpp.
Int8Data_t
typedef std::vector< uint8_t > icedb::Examples::Shapes::Int8Data_t
Definition at line 12 of file shape.hpp.
IntData_t
typedef std::vector< uint64_t > icedb::Examples::Shapes::IntData_t
Definition at line 11 of file shape.hpp.
MatchType_t
typedef hid_t icedb::Examples::Shapes::MatchType_t
Definition at line 75 of file shapeIOpsu.cpp.
StringData_t
typedef std::vector< std::string > icedb::Examples::Shapes::StringData_t
Definition at line 14 of file shape.hpp.
Function Documentation
array_to_floats()
size_t icedb::Examples::Shapes::array_to_floats (const char * in, const size_t inlen, float * out, const size_t outlen)
Definition at line 47 of file shapeIOtextParsers2.cpp.
             {
                 size_t curout = 0;
                 // Accepts numbers of the form: (+- )[0-9]*.[0-9]*(eE)(+- )[0-9]*.[0-9]*
                 bool isNegative = false;
                 bool inExponent = false;
                 bool expIsNeg = false;
                 bool pastDecimal = false;
                 uint64_t numerator, numeratorExp;
                 uint64_t digits_denom, digits_denom_Exp;
                 auto resetNum = [&]()
                     {numerator = 0; digits_denom = 0;
                     numeratorExp = 0; digits_denom_Exp = 0;
                     isNegative = false; inExponent = false;
                     expIsNeg = false; pastDecimal = false; };
                 resetNum();
                 const char* cur = in;
                 const char* end = in + inlen;
                 // Advance to the start of a number
                 assert(cur);
                 const char* numbers = "0123456789-+.eE";
                 const char* whitespace = " \t\n";
                 const char* numEnd = nullptr;
                 auto isNumber = [](char c) -> bool {
                     if (c >= '0' && c <= '9') return true;
                     if (c == '-' || c == '+' || c == '.' || c == 'e' || c == 'E') return true;
                     return false;
                 };
                 auto isControl = [](char c) -> bool {
                     if (c == '-' || c == '+' || c == '.' || c == 'e' || c == 'E') return true;
                     return false;
                 };
                 auto advanceToNumber = [](const char* in, const char* end) -> const char* {
                     while (in < end) {
                         if (*in >= '0' && *in <= '9') return in;
                         else if (*in == '-' || *in == '+' || *in == '.' || *in == 'e' || *in == 'E') return in;
                         else ++in;
                     }
                     return in;
                 };
                 while ((cur < end) && (curout < outlen)) {
                     //cur = strpbrk(cur, numbers);
                     cur = advanceToNumber(cur, end);
                     while (isNumber(*cur)) {
                         if (!isControl(*cur)) {
                             if (!inExponent) {
                                 numerator *= 10;
                                 numerator += (*cur - '0');
                                 if (pastDecimal) digits_denom++;
                             } else {
                                 numeratorExp *= 10;
                                 numeratorExp += (*cur - '0');
                                 if (pastDecimal) digits_denom_Exp++;
                             }
                         } else {
                             if (*cur == '.') pastDecimal = true;
                             if (*cur == '-' && !inExponent) isNegative = true;
                             if (*cur == '-' && inExponent) expIsNeg = true;
                             if (*cur == 'e' || *cur == 'E') {
                                 inExponent = true; pastDecimal = false; isNegative = false;
                             }
                         }
                         ++cur;
                     }
                     if (!numerator) continue;
                     // Number is loaded. Assign and advance.
                     float exponent = 0;
                     if (numeratorExp) {
                         exponent = static_cast<float>(numeratorExp);
                         if (digits_denom_Exp) exponent /= powf(10.f, static_cast<float>(digits_denom_Exp));
                         if (expIsNeg) exponent *= -1;
                     }
                     float num = 0;
                     num = static_cast<float>(numerator);
                     if (digits_denom) num /= powf(10.f, static_cast<float>(digits_denom));
                     if (isNegative) num *= -1;
                     float fnum = num;
                     if (numeratorExp) fnum *= powf(10.f, exponent);
                     out[curout] = fnum;
                     resetNum();
                     curout++;
                     ++cur;
                 }
                 return curout;
             }
m_atof()
template<class T > T icedb::Examples::Shapes::m_atof (const char * x, size_t len)
Definition at line 142 of file shapeIOtextParsers2.cpp.
             {
                 T res = 0;
                 unsigned int remainder = 0;
                 unsigned int rembase = 1;
                 unsigned int digit = 0;
                 // Sign false indicates positive. True is negative
                 bool sign = false;
                 bool expsign = false;
                 unsigned int expi = 0;
                 const char* p = x; // Set pointer to beginning of character stream
                 bool exponent = false;
                 bool decimal = false;
                 size_t i = 0;
                 while (*p != '\0' && ((len) ? i<len : true))
                 {
                     // Do digit checks here (no calls to isdigit)
                     // Ignore whitespace
                     if (*p == 'e' || *p == 'E')
                     {
                         exponent = true;
                     }
                     else if (*p == '.') {
                         decimal = true;
                     }
                     else if (*p == '-') {
                         if (!exponent)
{
                             sign = true;
                         }
                         else {
                             expsign = true;
                         }
                     }
                     else if (*p == '+') {
                         if (!exponent)
{
                             sign = false;
                         }
                         else {
                             expsign = false;
                         }
                     }
                     else if (*p == ' ' || *p == '\t') {
                         // Ignore whitespace (but disallow endlines)
                     }
                     else {
                         // It's a digit!
                         switch (*p)
{
                         case '0':
                             digit = 0;
                             break;
                         case '1':
                             digit = 1;
                             break;
                         case '2':
                             digit = 2;
                             break;
                         case '3':
                             digit = 3;
                             break;
                         case '4':
                             digit = 4;
                             break;
                         case '5':
                             digit = 5;
                             break;
                         case '6':
                             digit = 6;
                             break;
                         case '7':
                             digit = 7;
                             break;
                         case '8':
                             digit = 8;
                             break;
                         case '9':
                             digit = 9;
                             break;
                         default:
                             // Invalid input
                             p++;
                             continue;
                             break;
                         }
                         // Digit is set. Next, see what to do with it
                         if (!decimal && !exponent)
{
                             res *= 10;
                             res += digit;
                         }
                         else if (decimal && !exponent) {
                             remainder *= 10;
                             rembase *= 10;
                             remainder += digit;
                         }
                         else if (exponent) {
                             expi *= 10;
                             expi += digit;
                         }
                     }
                     p++;
                     i++;
                 }
                 // Iterated through the string
                 // Now, to combine the elements into my double
                 res += (T)remainder / (T)rembase;
                 if (sign) res *= -1;
                 if (exponent)
                 {
                     if (!expsign)
                     {
                         res *= (T)std::pow(10, (T)expi);
                     }
                     else {
                         res *= (T)std::pow(10, -1.0 * (T)expi);
                     }
                 }
                 return res;
             }
m_atoi()
template<class T > T icedb::Examples::Shapes::m_atoi (const char * x, size_t len)
Definition at line 266 of file shapeIOtextParsers2.cpp.
References icedb::Examples::Shapes::ShapeCommonOptionalData::hint_max_scattering_element_dimension, icedb::Examples::Shapes::ShapeRequiredData::number_of_particle_constituents, icedb::Examples::Shapes::ShapeRequiredData::number_of_particle_scattering_elements, icedb::Examples::Shapes::ShapeDataBasic::optional, icedb::Examples::Shapes::ShapeCommonOptionalData::particle_constituent_number, icedb::Examples::Shapes::ShapeRequiredData::particle_id, icedb::Examples::Shapes::ShapeCommonOptionalData::particle_scattering_element_composition_whole, icedb::Examples::Shapes::ShapeRequiredData::particle_scattering_element_coordinates, icedb::Examples::Shapes::ShapeRequiredData::particle_scattering_element_coordinates_are_integral, icedb::Examples::Shapes::ShapeCommonOptionalData::particle_scattering_element_number, readDDSCAT(), readDDSCATtextContents(), readHeader(), readRawText(), readTextFile(), icedb::Examples::Shapes::ShapeDataBasic::required, and strints_array_to_floats().
             {
                 T res = 0;
                 int digit = 0;
                 bool sign = false; // false is pos, true is neg
                 bool done = false;
                 size_t i = 0;
                 const char* p = x; // Set pointer to beginning of character stream
                 while (*p != '\0' && done == false && ((len) ? i<len : true))
                 {
                     if (*p == '-') {
                         sign = true;
                     }
                     else if (*p == '+') {
                         sign = false;
                     }
                     else if (*p == ' ' || *p == '\t') {
                         // Ignore whitespace (but disallow endlines)
                     }
                     else {
                         // It's a digit!
                         switch (*p)
{
                         case '0':
                             digit = 0;
                             break;
                         case '1':
                             digit = 1;
                             break;
                         case '2':
                             digit = 2;
                             break;
                         case '3':
                             digit = 3;
                             break;
                         case '4':
                             digit = 4;
                             break;
                         case '5':
                             digit = 5;
                             break;
                         case '6':
                             digit = 6;
                             break;
                         case '7':
                             digit = 7;
                             break;
                         case '8':
                             digit = 8;
                             break;
                         case '9':
                             digit = 9;
                             break;
                         default:
                             // Invalid input
                             done = true;
                             break;
                         }
                         // Digit is set. Next, see what to do with it
                         if (done) break;
                         res *= 10;
                         res += digit;
                     }
                     p++;
                     i++;
                 }
                 // Return the value
                 if (sign) res *= -1;
                 return res;
             }
MatchType()
template<class DataType > MatchType_t icedb::Examples::Shapes::MatchType ()
Definition at line 77 of file shapeIOpsu.cpp.
References ICEDB_throw, and icedb::error::xUnimplementedFunction.
             {
                 ICEDB_throw(icedb::error::error_types::xUnimplementedFunction)
                     .add("Reason", "Unsupported type during conversion.");
             }
MatchType< float >()
template<> MatchType_t icedb::Examples::Shapes::MatchType< float > ()
Definition at line 85 of file shapeIOpsu.cpp.
{
                 return H5T_NATIVE_FLOAT;
             }
MatchType< int32_t >()
template<> MatchType_t icedb::Examples::Shapes::MatchType< int32_t > ()
Definition at line 82 of file shapeIOpsu.cpp.
{
                 return H5T_NATIVE_INT32;
             }
readDataset()
template<typename T > void icedb::Examples::Shapes::readDataset (hid_t file_id, const char * dataset_name, std::vector< T > & outdata)
Definition at line 90 of file shapeIOpsu.cpp.
References icedb::error::xError::add(), icedb::Examples::Shapes::ScopedHandles::ScopedHandle< HandleType, InvalidValueClass, CloseMethod >::h, ICEDB_throw, icedb::Examples::Shapes::ScopedHandles::ScopedHandle< HandleType, InvalidValueClass, CloseMethod >::valid(), and icedb::error::xBadInput.
Referenced by readPSUfile().
             {
                 try {
                     ScopedHandles::H5D_handle hData(H5Dopen(file_id, dataset_name, H5P_DEFAULT));
                     if (!hData.valid()) ICEDB_throw(icedb::error::error_types::xBadInput);
                     // Get dimensionality
                     ScopedHandles::H5DS_handle hSpace(H5Dget_space(hData.h));
                     if (!hSpace.valid()) ICEDB_throw(icedb::error::error_types::xBadInput);
                     int rank = H5Sget_simple_extent_ndims(hSpace.h);
                     if (rank == 0 || rank > 2) ICEDB_throw(icedb::error::error_types::xBadInput);
                     hssize_t numElems = H5Sget_simple_extent_npoints(hSpace.h);
                     // Verify that the dataset has the expected type
                     ScopedHandles::H5T_handle hDatatype(H5Dget_type(hData.h));
                     MatchType_t funcDataType = MatchType<T>();
                     if (H5Tequal(funcDataType, hDatatype.h) <= 0) ICEDB_throw(icedb::error::error_types::xBadInput);
                     // If this conversion fails, then either we are trying to open a dataset with
                     // the wrong data type (i.e. float vs int32 vs int16), or the architecture
                     // between the systems used to store and read the data are _very_ different,
                     // which is highly unlikely.
                     // Resize output vector
                     outdata.resize(numElems);
                     // Read the data
                     if (H5Dread(
                         hData.h, // dataset
                         hDatatype.h, // in-memory data type
                         H5S_ALL, // memory data space; reading the entire dataset
                         H5S_ALL, // file data space; reading the entire dataset
                         H5P_DEFAULT, // default transfer properties
                         (void*)outdata.data()) // the output buffer (pre-sized)
                         < 0) ICEDB_throw(icedb::error::error_types::xBadInput);
                 }
                 catch (icedb::error::xError &err) {
                     err
                         .add("Reason", "Cannot open an HDF5 dataspace.")
                         .add("Dataset", dataset_name);
                     throw err; // rethrow
                 }
             }
readDDSCAT()
ShapeDataBasic icedb::Examples::Shapes::readDDSCAT (const char * in)
Definition at line 238 of file shapeIOtextParsers.cpp.
References readDDSCATtextContents(), and readHeader().
Referenced by m_atoi(), and readTextFile().
             {
                 using namespace std;
                 ShapeDataBasic res;
                 std::string str(in);
                 std::string desc; // Currently unused
                 size_t headerEnd = 0, numPoints = 0;
                 readHeader(str.c_str(), desc, numPoints, headerEnd);
                 //res.required.particle_id = desc;
                 //data->resize((int)numPoints, ::scatdb::shape::backends::NUM_SHAPECOLS);
                 readDDSCATtextContents(str.c_str(), numPoints, headerEnd, res);
                 return res;
             }
readDDSCATtextContents()
void icedb::Examples::Shapes::readDDSCATtextContents (const char * iin, size_t numExpectedPoints, size_t headerEnd, ShapeDataBasic & p)
Read ddscat text contents.
Read ddscat text contents - the stuff after the header.
Definition at line 187 of file shapeIOtextParsers.cpp.
References icedb::Examples::Shapes::ShapeRequiredData::number_of_particle_constituents, icedb::Examples::Shapes::ShapeRequiredData::number_of_particle_scattering_elements, icedb::Examples::Shapes::ShapeDataBasic::optional, anonymous_namespace{shapeIOtextParsers.cpp}::parse_shapefile_entries(), icedb::Examples::Shapes::ShapeCommonOptionalData::particle_constituent_number, icedb::Examples::Shapes::ShapeCommonOptionalData::particle_scattering_element_composition_whole, icedb::Examples::Shapes::ShapeRequiredData::particle_scattering_element_coordinates, icedb::Examples::Shapes::ShapeRequiredData::particle_scattering_element_coordinates_are_integral, icedb::Examples::Shapes::ShapeCommonOptionalData::particle_scattering_element_number, and icedb::Examples::Shapes::ShapeDataBasic::required.
Referenced by m_atoi(), and readDDSCAT().
             {
                 using namespace std;
                 //Eigen::Vector3f crdsm, crdsi; // point location and diel entries
                 const char* pa = &iin[headerEnd];
                 const char* pb = strchr(pa + 1, '\0');
                 std::vector<float> parser_vals; //(numPoints*8);
                 parser_vals.reserve(7 * numExpectedPoints);
                 parse_shapefile_entries(pa, pb, parser_vals);
                 assert(parser_vals.size() % 7 == 0);
                 size_t &numPoints = p.required.number_of_particle_scattering_elements;
                 numPoints = parser_vals.size() / 7;
                 assert(numPoints == numExpectedPoints);
                 p.optional.particle_scattering_element_number.resize(numPoints);
                 p.required.particle_scattering_element_coordinates.resize(numPoints * 3);
                 std::set<uint8_t> constituents;
                 for (size_t i = 0; i < numPoints; ++i)
                 {
                     size_t pIndex = 7 * i;
                     p.optional.particle_scattering_element_number[i] = static_cast<uint64_t>(parser_vals[pIndex]);
                     p.required.particle_scattering_element_coordinates[3*i] = parser_vals[pIndex+1];
                     p.required.particle_scattering_element_coordinates[(3 * i)+1] = parser_vals[pIndex + 2];
                     p.required.particle_scattering_element_coordinates[(3 * i)+2] = parser_vals[pIndex + 3];
                     constituents.emplace(static_cast<uint8_t>(parser_vals[pIndex + 4]));
                     //p.required.particle_scattering_element_composition[i] = parser_vals[pIndex + 4]; //! Redo pass later and map
                 }
                 p.optional.particle_constituent_number = Int8Data_t(constituents.begin(), constituents.end());
                 p.optional.particle_scattering_element_composition_whole.resize(numPoints);
                 if (constituents.size() >= UINT8_MAX) throw (std::invalid_argument("Shape has too many constituents."));
                 p.required.number_of_particle_constituents = static_cast<uint8_t>(constituents.size());
                 for (size_t i = 0; i < numPoints; ++i)
                 {
                     size_t pIndex = 7 * i;
                     uint64_t substance_id = static_cast<uint64_t>(parser_vals[pIndex + 4]);
                     size_t offset = 0;
                     for (auto it = constituents.cbegin(); it != constituents.cend(); ++it, ++offset) {
                         if ((*it) == substance_id) break;
                     }
                     size_t idx = (i*constituents.size()) + offset;
                     p.optional.particle_scattering_element_composition_whole[idx] = 1;
                 }
                 p.required.particle_scattering_element_coordinates_are_integral = 1;
             }
readHeader()
void icedb::Examples::Shapes::readHeader (const char * in, std::string & desc, size_t & np, size_t & headerEnd)
Definition at line 113 of file shapeIOtextParsers.cpp.
Referenced by m_atoi(), and readDDSCAT().
             {
                 using namespace std;
                 // Do header processing using istreams.
                 // The previous method used strings, but this didn't work with compressed reads.
                 //size_t &pend = headerEnd;
                 const char* pend = in;
                 const char* pstart = in;
                 // The header is seven lines long
                 for (size_t i = 0; i < 7; i++)
                 {
                     pstart = pend;
                     pend = strchr(pend, '\n');
                     pend++; // Get rid of the newline
                             //pend = in.find_first_of("\n", pend+1);
                     string lin(pstart, pend - pstart - 1);
                     if (*(lin.rbegin()) == '\r') lin.pop_back();
                     //std::getline(in,lin);
                     size_t posa = 0, posb = 0;
                     //Eigen::Array3f *v = nullptr;
                     switch (i)
                     {
                     case 0: // Title line
                         desc = lin;
                         break;
                     case 1: // Number of dipoles
                     {
                         // Seek to first nonspace character
                         posa = lin.find_first_not_of(" \t\n", posb);
                         // Find first space after this position
                         posb = lin.find_first_of(" \t\n", posa);
                         size_t len = posb - posa;
                         string s = lin.substr(posa, len);
                         np = boost::lexical_cast<size_t>(s);
                         //np = macros::m_atoi<size_t>(&(lin.data()[posa]), len);
                     }
                     break;
                     case 6: // Junk line
                     default:
                         break;
                     case 2: // a1
                     case 3: // a2
                     case 4: // d
                     case 5: // x0
                             // These all have the same structure. Read in three doubles, then assign.
                         /*
                     {
                         Eigen::Array3f v;
                         for (size_t j = 0; j < 3; j++)
{
                             // Seek to first nonspace character
                             posa = lin.find_first_not_of(" \t\n,", posb);
                             // Find first space after this position
                             posb = lin.find_first_of(" \t\n,", posa);
                             size_t len = posb - posa;
                             string s = lin.substr(posa, len);
                             v(j) = boost::lexical_cast<float>(s);
                             //v(j) = macros::m_atof<float>(&(lin.data()[posa]), len);
                         }
                         hdr->block<3, 1>(0, i - 2) = v;
                     }
                     */
                     break;
                     }
                 }
                 headerEnd = (pend - in) / sizeof(char);
             }
readPSUfile()
ShapeDataBasic icedb::Examples::Shapes::readPSUfile (const std::string & filename)
Reads a Penn State-style geometry file.
Todo:
Convert to using my "HDF for Humans" interface once it is ready.
VARIABLE: Cartesian coordinates of the center of each scattering element Written in form of x_1, y_1, z_1, x_2, y_2, z_2, ... Dimensions of [number_of_particle_scattering_elements][axis]
Definition at line 137 of file shapeIOpsu.cpp.
References icedb::Examples::Shapes::ScopedHandles::ScopedHandle< HandleType, InvalidValueClass, CloseMethod >::h, ICEDB_throw, icedb::Examples::Shapes::ShapeRequiredData::number_of_particle_constituents, icedb::Examples::Shapes::ShapeRequiredData::number_of_particle_scattering_elements, icedb::Examples::Shapes::ShapeDataBasic::optional, icedb::Examples::Shapes::ShapeCommonOptionalData::particle_constituent_single_name, icedb::Examples::Shapes::ShapeRequiredData::particle_id, icedb::Examples::Shapes::ShapeRequiredData::particle_scattering_element_coordinates, icedb::Examples::Shapes::ShapeRequiredData::particle_scattering_element_coordinates_are_integral, icedb::Examples::Shapes::ShapeCommonOptionalData::particle_scattering_element_radius, icedb::Examples::Shapes::ShapeCommonOptionalData::particle_scattering_element_spacing, readDataset(), icedb::Examples::Shapes::ShapeDataBasic::required, icedb::Examples::Shapes::ScopedHandles::ScopedHandle< HandleType, InvalidValueClass, CloseMethod >::valid(), icedb::error::xAssert, and icedb::error::xBadInput.
Referenced by main().
             {
                 using namespace std;
                 ShapeDataBasic shpdata;
                 // The particle index is not specific enough. Let's use the filename for an id.
                 boost::filesystem::path p(filename);
                 auto pfile = p.filename();
 #if BOOST_VERSION < 104600
                 string id = pfile.c_str(); // Needed for older RHEL machines
 #else
                 string id = pfile.string().c_str(); // Totally assuming a lack of non-Latin characters in the path.
 #endif
                 ScopedHandles::H5F_handle hFile(H5Fopen(filename.c_str(), H5F_ACC_RDONLY, H5P_DEFAULT));
                 if (!hFile.valid()) ICEDB_throw(icedb::error::error_types::xBadInput)
                     .add("Reason", "Cannot open a netCDF/HDF5 file.")
                     .add("Filename", filename);
                 // A valid PSU file has these tables: particle_index, sphere_index, r, x, y, z.
                 // particle_index has one row, one column.
                 // The rest have one column, and a number of rows that correspond to the number of spheres used to represent the particle.
                 auto verifyDatasetExists = [](hid_t file_id, const char* dataset_name) -> bool {
                     if ((H5Lexists(file_id, dataset_name, H5P_DEFAULT) <= 0)) return false;
                     H5O_info_t objinfo;
                     if ((H5Oget_info_by_name(file_id, dataset_name, &objinfo, H5P_DEFAULT) < 0)) return false;
                     if (objinfo.type != H5O_TYPE_DATASET) return false;
                     return true;
                 };
                 if (!verifyDatasetExists(hFile.h, "/particle_index")
                     || !verifyDatasetExists(hFile.h, "/sphere_index")
                     || !verifyDatasetExists(hFile.h, "/r")
                     || !verifyDatasetExists(hFile.h, "/x")
                     || !verifyDatasetExists(hFile.h, "/y")
                     || !verifyDatasetExists(hFile.h, "/z"))
                     ICEDB_throw(icedb::error::error_types::xBadInput)
                     .add("Reason", "This file does not have the proper structure for a Penn State geometry file.")
                     .add("Filename", filename);
                 // Open all of the datasets. Make sure that they have the correct dimensionality.
                 // Read the data into vectors. Verify that the data have the appropriate sizes.
                 vector<float> xs, ys, zs, rs;
                 vector<int32_t> sphere_indices;
                 // No need to read particle_index. Not being used.
                 readDataset<int32_t>(hFile.h, "/sphere_index", sphere_indices);
                 readDataset<float>(hFile.h, "/r", rs);
                 readDataset(hFile.h, "/x", xs);
                 readDataset(hFile.h, "/y", ys);
                 readDataset(hFile.h, "/z", zs);
                 // Check that the read arrays have matching sizes.
                 const size_t numPoints = rs.size();
                 if (numPoints != xs.size()) ICEDB_throw(icedb::error::error_types::xAssert);
                 if (numPoints != ys.size()) ICEDB_throw(icedb::error::error_types::xAssert);
                 if (numPoints != zs.size()) ICEDB_throw(icedb::error::error_types::xAssert);
                 if (numPoints != sphere_indices.size()) ICEDB_throw(icedb::error::error_types::xAssert);
                 // Finally, pack the data in the shpdata structure.
                 shpdata.required.number_of_particle_scattering_elements = static_cast<uint64_t>(numPoints);
                 shpdata.required.number_of_particle_constituents = 1;
                 shpdata.required.particle_id = filename; // TODO: improve this
                 shpdata.required.particle_scattering_element_coordinates_are_integral = false;
                 shpdata.required.particle_scattering_element_coordinates.resize(3 * numPoints);
                 for (size_t i = 0; i < numPoints; ++i) {
                     shpdata.required.particle_scattering_element_coordinates[(3 * i) + 0] = xs[i];
                     shpdata.required.particle_scattering_element_coordinates[(3 * i) + 1] = ys[i];
                     shpdata.required.particle_scattering_element_coordinates[(3 * i) + 2] = zs[i];
                 }
                 shpdata.optional.particle_constituent_single_name = "ice";
                 shpdata.optional.particle_scattering_element_spacing = 0.001f; // 1 mm
                 shpdata.optional.particle_scattering_element_radius = rs;
                 return shpdata;
             }
readRawText()
ShapeDataBasic icedb::Examples::Shapes::readRawText (const char * iin)
Simple file assuming one substance, with 3-column rows, each representing a single point. ADDA allows comment lines at the beginning of the file. Each line starts with a '#'.
Definition at line 317 of file shapeIOtextParsers.cpp.
References icedb::Examples::Shapes::ShapeRequiredData::number_of_particle_constituents, icedb::Examples::Shapes::ShapeRequiredData::number_of_particle_scattering_elements, icedb::Examples::Shapes::ShapeDataBasic::optional, anonymous_namespace{shapeIOtextParsers.cpp}::parse_shapefile_entries(), icedb::Examples::Shapes::ShapeCommonOptionalData::particle_constituent_number, icedb::Examples::Shapes::ShapeRequiredData::particle_id, icedb::Examples::Shapes::ShapeCommonOptionalData::particle_scattering_element_composition_whole, icedb::Examples::Shapes::ShapeRequiredData::particle_scattering_element_coordinates, icedb::Examples::Shapes::ShapeRequiredData::particle_scattering_element_coordinates_are_integral, and icedb::Examples::Shapes::ShapeDataBasic::required.
Referenced by m_atoi(), and readTextFile().
             {
                 using namespace std;
                 ShapeDataBasic res;
                 //Eigen::Vector3f crdsm, crdsi; // point location and diel entries
                 const char* pa = iin; // Start of the file
                 const char* pb = strchr(pa + 1, '\0'); // End of the file
                 const char* pNumStart = pa;
                 // Search for the first line that is not a comment.
                 // Nmat lines for ADDA are also ignored.
                 while ((pNumStart[0] == '#' || pNumStart[0] == 'N' || pNumStart[0] == 'n') && pNumStart < pb) {
                     const char* lineEnd = strchr(pNumStart + 1, 'n');
                     pNumStart = lineEnd + 1;
                 }
                 if (pNumStart >= pb) throw(std::invalid_argument("Cannot find any points in a shapefile."));
                 const char* firstLineEnd = strchr(pNumStart + 1, '\n'); // End of the first line containing numberic data.
                 // Attempt to guess the number of points based on the number of lines in the file.
                 int guessNumPoints = std::count(pNumStart, pb, '\n');
                 std::vector<float> firstLineVals; //(numPoints*8);
                 //std::vector<float> &parser_vals = res.required.particle_scattering_element_coordinates;
                 std::vector<float> parser_vals;
                 parser_vals.reserve(guessNumPoints * 4);
                 parse_shapefile_entries(pNumStart, pb, parser_vals);
                 const void* floatloc = memchr(pNumStart, '.', pb - pNumStart);
                 res.required.particle_scattering_element_coordinates_are_integral = (floatloc) ? 0 : 1;
                 parse_shapefile_entries(pNumStart, firstLineEnd, firstLineVals);
                 size_t numCols = firstLineVals.size();
                 bool good = false;
                 if (numCols == 3) good = true; // Three columns, x, y and z
                 if (numCols == 4) good = true; // Four columns, x, y, z and material
                 if (!good) throw (std::invalid_argument("Bad read"));
                 if (parser_vals.size() == 0) throw (std::invalid_argument("Bad read"));
                 size_t actualNumPoints = parser_vals.size() / numCols;
                 assert(actualNumPoints == guessNumPoints);
                 res.required.number_of_particle_scattering_elements = actualNumPoints;
                 if (numCols == 3) {
                     res.required.number_of_particle_constituents = 1;
                     res.required.particle_scattering_element_coordinates = parser_vals;
                 }
                 else if (numCols == 4) {
                     // Count the number of distinct materials
                     uint8_t max_constituent = 1;
                     for (size_t i = 0; i < actualNumPoints; ++i) {
                         auto constit = parser_vals[(4 * i) + 3];
                         assert(static_cast<uint8_t>(constit) < UINT8_MAX);
                         if (static_cast<uint8_t>(constit) > max_constituent)
                             max_constituent = static_cast<uint8_t>(constit);
                     }
                     res.required.number_of_particle_constituents = max_constituent;
                     res.optional.particle_constituent_number.resize(max_constituent);
                     for (size_t i = 0; i < max_constituent; ++i)
                         res.optional.particle_constituent_number[i] = static_cast<uint8_t>(i + 1); // assert-checked before
                     res.required.particle_scattering_element_coordinates.resize(actualNumPoints * 3);
                     res.optional.particle_scattering_element_composition_whole.resize(actualNumPoints);
                     for (size_t i = 0; i < actualNumPoints; ++i) {
                         size_t crdindex = (3 * i);
                         size_t parserindex = (4 * i);
                         res.required.particle_scattering_element_coordinates[crdindex + 0] = parser_vals[parserindex + 0];
                         res.required.particle_scattering_element_coordinates[crdindex + 1] = parser_vals[parserindex + 1];
                         res.required.particle_scattering_element_coordinates[crdindex + 2] = parser_vals[parserindex + 2];
                         res.optional.particle_scattering_element_composition_whole[i] = static_cast<uint8_t>(parser_vals[parserindex + 3]);
                     }
                 }
                 res.required.particle_id = "";
                 return res;
             }
readTextFile()
ShapeDataBasic icedb::Examples::Shapes::readTextFile (const std::string & filename)
Definition at line 405 of file shapeIOtextParsers.cpp.
References readDDSCAT(), and readRawText().
Referenced by m_atoi(), main(), and readtask().
{
                 // Open the file and copy to a string. Check the first few lines to see if any
                 // alphanumeric characters are present. If there are, treat it as a DDSCAT file.
                 // Otherwise, treat as a raw text file.
                 std::ifstream in(filename.c_str());
                 std::ostringstream so;
                 boost::iostreams::copy(in, so);
                 std::string s = so.str();
                 auto end = s.find_first_of("\n\0");
                 Expects(end != std::string::npos);
                 std::string ssub = s.substr(0,end);
                 auto spos = ssub.find_first_not_of("0123456789. \t\n");
                 if (std::string::npos == spos) // This is a raw text file
                     return readRawText(s.c_str());
                 else return readDDSCAT(s.c_str()); // This is a DDSCAT file
                 //if ((std::string::npos != spos) && (spos < end)) {
                 //  return readDDSCAT(s.c_str());
                 //}
                 //else {
                 //  return readTextRaw(s.c_str());
                 //}
             }
strints_array_to_floats()
size_t icedb::Examples::Shapes::strints_array_to_floats (const char * in, const size_t inlen, float * out, const size_t outlen, float & max_element)
Definition at line 18 of file shapeIOtextParsers2.cpp.
Referenced by m_atoi().
             {
                 max_element = 0;
                 size_t curout = 0;
                 // Accepts numbers of the form: [0-9]*
                 // No negatives, exponents or decimals.
                 float numerator = 0;
                 assert(in);
                 const char* end = in + inlen;
                 bool readnums = false;
                 for (const char* cur = in; (cur <= end) && (curout < outlen); ++cur) {
                     if ((*cur <= '9') && (*cur >= '0')) {
                         numerator *= 10;
                         numerator += (*cur - '0');
                         readnums = true;
                     } else if(readnums){
                         out[curout] = numerator;
                         if (numerator > max_element) max_element = numerator;
                         curout++;
                         numerator = 0;
                         readnums = false;
                     }
                 }
                 return curout;
             }
writeDDSCAT()
void icedb::Examples::Shapes::writeDDSCAT (const std::string & filename, const ShapeDataBasic & p)
Definition at line 255 of file shapeIOtextParsers.cpp.
References icedb::Examples::Shapes::ShapeRequiredData::number_of_particle_constituents, icedb::Examples::Shapes::ShapeRequiredData::number_of_particle_scattering_elements, icedb::Examples::Shapes::ShapeDataBasic::optional, icedb::Examples::Shapes::ShapeRequiredData::particle_id, icedb::Examples::Shapes::ShapeCommonOptionalData::particle_scattering_element_composition_fractional, icedb::Examples::Shapes::ShapeCommonOptionalData::particle_scattering_element_composition_whole, icedb::Examples::Shapes::ShapeRequiredData::particle_scattering_element_coordinates, icedb::Examples::Shapes::ShapeCommonOptionalData::particle_scattering_element_number, anonymous_namespace{shapeIOtextParsers.cpp}::print_shapefile_entries(), and icedb::Examples::Shapes::ShapeDataBasic::required.
             {
                 using namespace std;
                 std::ofstream out(filename.c_str());
                 out << p.required.particle_id << endl;
                 out << p.required.number_of_particle_scattering_elements << "\t= Number of lattice points" << endl;
                 out << "1.0\t1.0\t1.0\t= target vector a1 (in TF)" << endl;
                 out << "0.0\t1.0\t0.0\t= target vector a2 (in TF)" << endl;
                 out << "1.0\t1.0\t1.0\t= d_x/d  d_y/d  d_x/d  (normally 1 1 1)" << endl;
                 //out << (*hdr)(X0, 0) << "\t" << (*hdr)(X0, 1) << "\t" << (*hdr)(X0, 2);
                 out << "0.0\t0.0\t0.0\t= X0(1-3) = location in lattice of target origin" << endl;
                 out << "\tNo.\tix\tiy\tiz\tICOMP(x, y, z)" << endl;
                 //size_t i = 1;
                 const size_t numPoints = p.required.number_of_particle_scattering_elements;
                 std::vector<float> oi(numPoints * 7);
                 for (size_t j = 0; j < numPoints; j++)
                 {
                     const float &x = p.required.particle_scattering_element_coordinates[j * 3+0];
                     const float &y = p.required.particle_scattering_element_coordinates[j * 3+1];
                     const float &z = p.required.particle_scattering_element_coordinates[j * 3+2];
                     if (p.optional.particle_scattering_element_number.empty()) {
                         oi[j * 7 + 0] = j+1;
                     }
                     else {
                         oi[j * 7 + 0] = p.optional.particle_scattering_element_number[j];
                     }
                     oi[j * 7 + 1] = x;
                     oi[j * 7 + 2] = y;
                     oi[j * 7 + 3] = z;
                     uint64_t comp = 1;
                     if (p.required.number_of_particle_constituents > 1) {
                         if (p.optional.particle_scattering_element_composition_whole.size()) {
                             comp = p.optional.particle_scattering_element_composition_whole[j];
                         }
                         if (p.optional.particle_scattering_element_composition_fractional.size()) {
                             throw(std::invalid_argument("Cannot write a DDSCAT shape file with this type of dielectric!"));
                         }
                     }
                     oi[j * 7 + 4] = comp;
                     oi[j * 7 + 5] = comp;
                     oi[j * 7 + 6] = comp;
                 }
                 std::string generated;
                 std::back_insert_iterator<std::string> sink(generated);
                 if (!print_shapefile_entries(sink, oi))
                 {
                     throw(std::invalid_argument("Somehow unable to print the shape points properly."));
                 }
                 out << generated;
             }
writeTextRaw()
void icedb::Examples::Shapes::writeTextRaw (const std::string & filename, const ShapeDataBasic & p)
Definition at line 392 of file shapeIOtextParsers.cpp.
References icedb::Examples::Shapes::ShapeRequiredData::particle_scattering_element_coordinates, anonymous_namespace{shapeIOtextParsers.cpp}::print_shapefile_pts(), and icedb::Examples::Shapes::ShapeDataBasic::required.
             {
                 using namespace std;
                 std::ofstream out(filename.c_str());
                 std::string generated;
                 std::back_insert_iterator<std::string> sink(generated);
                 if (!print_shapefile_pts(sink, p.required.particle_scattering_element_coordinates))
                 {
                     throw(std::invalid_argument("Somehow unable to print the shape points properly."));
                 }
                 out << generated;
             }