icedb: anonymous_namespace{shapeIOtextParsers.cpp} Namespace Reference
anonymous_namespace{shapeIOtextParsers.cpp} Namespace Reference
Internal namespace for the reader parsers.
Functions
template<typename Iterator >
bool parse_shapefile_entries (Iterator first, Iterator last, std::vector< float > &v)
Parses space-separated shapefile entries.
template<typename OutputIterator , typename Container >
bool print_shapefile_entries (OutputIterator &sink, Container const &v)
Used in quickly printing shapefile.
template<typename OutputIterator , typename Container >
bool print_shapefile_pts (OutputIterator &sink, Container const &v)
Detailed Description
Internal namespace for the reader parsers.
Function Documentation
parse_shapefile_entries()
template<typename Iterator > bool anonymous_namespace{shapeIOtextParsers.cpp}::parse_shapefile_entries (Iterator first, Iterator last, std::vector< float > & v)
Parses space-separated shapefile entries.
Definition at line 35 of file shapeIOtextParsers.cpp.
Referenced by icedb::Examples::Shapes::readDDSCATtextContents(), and icedb::Examples::Shapes::readRawText().
     {
         using qi::double_;
         using qi::long_;
         using qi::float_;
         using qi::phrase_parse;
         using qi::_1;
         using ascii::space;
         using phoenix::push_back;
         bool r = phrase_parse(first, last,
             //  Begin grammar
             (
                 // *long_[push_back(phoenix::ref(v), _1)]
                 *float_
                 )
             ,
             //  End grammar
             space, v);
         if (first != last) // fail if we did not get a full match
             return false;
         return r;
     }
print_shapefile_entries()
template<typename OutputIterator , typename Container > bool anonymous_namespace{shapeIOtextParsers.cpp}::print_shapefile_entries (OutputIterator & sink, Container const & v)
Used in quickly printing shapefile.
Definition at line 64 of file shapeIOtextParsers.cpp.
Referenced by icedb::Examples::Shapes::writeDDSCAT().
     {
         using boost::spirit::karma::long_;
         using boost::spirit::karma::float_;
         using boost::spirit::karma::repeat;
         using boost::spirit::karma::generate;
         //using boost::spirit::karma::generate_delimited;
         using boost::spirit::ascii::space;
         bool r = generate(
             sink,                           // destination: output iterator
             *(
                 //repeat(7)()
                 '\t' << long_ << '\t' << // point id
                 float_ << '\t' << float_ << '\t' << float_ << '\t' << // point coordinates
                 long_ << '\t' << long_ << '\t' << long_ << '\n' // dielectric
                 ),
             //space,                          // the delimiter-generator
             v                               // the data to output
         );
         return r;
     }
print_shapefile_pts()
template<typename OutputIterator , typename Container > bool anonymous_namespace{shapeIOtextParsers.cpp}::print_shapefile_pts (OutputIterator & sink, Container const & v)
Definition at line 88 of file shapeIOtextParsers.cpp.
Referenced by icedb::Examples::Shapes::writeTextRaw().
     {
         using boost::spirit::karma::long_;
         using boost::spirit::karma::float_;
         using boost::spirit::karma::repeat;
         using boost::spirit::karma::generate;
         //using boost::spirit::karma::generate_delimited;
         using boost::spirit::ascii::space;
         bool r = generate(
             sink,                           // destination: output iterator
             *(
                 //repeat(7)()
                 float_ << '\t' << float_ << '\t' << float_ << '\n'
                 ),
             //space,                          // the delimiter-generator
             v                               // the data to output
         );
         return r;
     }