icedb: icedb::units::implementations::spectralUnits Struct Reference
icedb::units::implementations::spectralUnits Struct Reference
#include <unitsBackend.hpp>
Public Member Functions
spectralUnits (const std::string &in, const std::string &out)
virtual ~spectralUnits ()
virtual bool isValid () const
virtual double convert (double input) const
Public Member Functions inherited from icedb::units::implementations::Unithandler
virtual ~Unithandler ()
Static Public Member Functions
static bool canConvert (Converter_registry_provider::optsType opts)
static std::shared_ptr< const implementations::Unithandler > constructConverter (Converter_registry_provider::optsType opts)
Public Attributes
std::string _inUnits
std::string _outUnits
bool _valid
bool _Iin
bool _Iout
std::shared_ptr< const implementations::Unithandler > hIn
std::shared_ptr< const implementations::Unithandler > hOut
Additional Inherited Members
Protected Member Functions inherited from icedb::units::implementations::Unithandler
Unithandler (const char *id)
Protected Attributes inherited from icedb::units::implementations::Unithandler
const char * id
Detailed Description
Definition at line 35 of file unitsBackend.hpp.
Constructor & Destructor Documentation
spectralUnits()
icedb::units::implementations::spectralUnits::spectralUnits (const std::string & in, const std::string & out)
Definition at line 214 of file unitsSimple.cpp.
                                                                                   :
                 Unithandler("spectral"),
                 _inUnits(in), _outUnits(out), _valid(true), _Iin(false),
                 _Iout(false)
             {
             }
~spectralUnits()
icedb::units::implementations::spectralUnits::~spectralUnits () virtual
Definition at line 221 of file unitsSimple.cpp.
 {}
Member Function Documentation
canConvert()
bool icedb::units::implementations::spectralUnits::canConvert (Converter_registry_provider::optsType opts) static
Definition at line 174 of file unitsSimple.cpp.
References icedb::units::converter::canConvert().
{
                 const std::string in = opts->getVal<std::string>("inUnits");
                 const std::string out = opts->getVal<std::string>("outUnits");
                 bool inIsLen = converter::canConvert(in, "m");
                 bool inIsWv = converter::canConvert(in, "Hz");
                 bool outIsLen = converter::canConvert(out, "m");
                 bool outIsWv = converter::canConvert(out, "Hz");
                 if ((inIsLen || inIsWv) && (outIsLen || outIsWv)) return true;
                 return false;
             }
constructConverter()
std::shared_ptr< const implementations::Unithandler > icedb::units::implementations::spectralUnits::constructConverter (Converter_registry_provider::optsType opts) static
Definition at line 184 of file unitsSimple.cpp.
References icedb::units::converter::canConvert(), icedb::units::converter::getConverter(), and icedb::units::implementations::simpleUnits::simpleUnits().
Referenced by icedb::units::conv_spec::conv_spec().
{
                 const std::string in = opts->getVal<std::string>("inUnits");
                 const std::string out = opts->getVal<std::string>("outUnits");
                 // Can input be converted to a length, or is it an inverse length?
                 bool inIsLen = converter::canConvert(in, "m");
                 bool inIsWv = converter::canConvert(in, "Hz");
                 bool outIsLen = converter::canConvert(out, "m");
                 bool outIsWv = converter::canConvert(out, "Hz");
                 if ((inIsLen && outIsLen) || (inIsWv && outIsWv)) {
                     return std::shared_ptr<simpleUnits>(new simpleUnits(in, out, true));
                 }
                 // These are heterogeneous.
                 std::shared_ptr<spectralUnits> res(new spectralUnits(in, out));
                 if (inIsLen) {
                     res->hIn = converter::getConverter(in, "m");
                     res->_Iin = true;
                 }
                 if (inIsWv) res->hIn = converter::getConverter(in, "Hz");
                 if (outIsLen) {
                     res->hOut = converter::getConverter("m", out);
                     res->_Iout = true;
                 }
                 if (outIsWv) res->hOut = converter::getConverter("Hz", out);
                 if (res->hIn && res->hOut) res->_valid = true;
                 else res->_valid = false;
                 return res;
             }
convert()
double icedb::units::implementations::spectralUnits::convert (double input) const virtual
Implements icedb::units::implementations::Unithandler.
Definition at line 224 of file unitsSimple.cpp.
References _Iin, _Iout, _valid, hIn, and hOut.
{
                 if (!_valid) return -1;
                 double res = input;
                 res = hIn->convert(res);
                 const double c = 2.99792458e8; // m/s
                                                // If inversion needed...
                 if (_Iin) res = c / res;
                 // Res is now in Hz. Do output conversion.
                 if (_Iout) res = c / res;
                 res = hOut->convert(res);
                 return res;
             }
isValid()
bool icedb::units::implementations::spectralUnits::isValid () const virtual
Implements icedb::units::implementations::Unithandler.
Definition at line 222 of file unitsSimple.cpp.
References _valid.
 { return _valid; }
Member Data Documentation
_Iin
bool icedb::units::implementations::spectralUnits::_Iin
Definition at line 42 of file unitsBackend.hpp.
Referenced by convert().
_inUnits
std::string icedb::units::implementations::spectralUnits::_inUnits
Definition at line 41 of file unitsBackend.hpp.
_Iout
bool icedb::units::implementations::spectralUnits::_Iout
Definition at line 42 of file unitsBackend.hpp.
Referenced by convert().
_outUnits
std::string icedb::units::implementations::spectralUnits::_outUnits
Definition at line 41 of file unitsBackend.hpp.
_valid
bool icedb::units::implementations::spectralUnits::_valid
Definition at line 42 of file unitsBackend.hpp.
Referenced by convert(), and isValid().
hIn
std::shared_ptr<const implementations::Unithandler> icedb::units::implementations::spectralUnits::hIn
Definition at line 43 of file unitsBackend.hpp.
Referenced by convert().
hOut
std::shared_ptr<const implementations::Unithandler> icedb::units::implementations::spectralUnits::hOut
Definition at line 43 of file unitsBackend.hpp.
Referenced by convert().
The documentation for this struct was generated from the following files:
lib/private/unitsBackend.hpp
lib/src/unitsSimple.cpp