icedb: icedb::units::implementations::simpleUnits Struct Reference
icedb::units::implementations::simpleUnits Struct Reference
#include <unitsBackend.hpp>
Public Member Functions
simpleUnits (const std::string &in, const std::string &out, bool init=true)
bool validLength (const std::string &_inUnits, const std::string &_outUnits)
bool validFreq (const std::string &_inUnits, const std::string &_outUnits)
bool validVol (const std::string &_inUnits, const std::string &_outUnits)
bool validPres (const std::string &in, const std::string &out)
bool validMass (const std::string &in, const std::string &out)
bool validTemp (const std::string &in, const std::string &out)
bool validDens (const std::string &in, const std::string &out)
virtual ~simpleUnits ()
virtual bool isValid () const
double convert (double inVal) const
Public Member Functions inherited from icedb::units::implementations::Unithandler
virtual ~Unithandler ()
Static Public Member Functions
static bool canConvert (Converter_registry_provider::optsType opts)
static std::shared_ptr< const Unithandler > constructConverter (Converter_registry_provider::optsType opts)
Public Attributes
double _inOffset
double _outOffset
double _convFactor
std::string _inUnits
std::string _outUnits
bool _valid
Additional Inherited Members
Protected Member Functions inherited from icedb::units::implementations::Unithandler
Unithandler (const char *id)
Protected Attributes inherited from icedb::units::implementations::Unithandler
const char * id
Detailed Description
Definition at line 15 of file unitsBackend.hpp.
Constructor & Destructor Documentation
simpleUnits()
icedb::units::implementations::simpleUnits::simpleUnits (const std::string & in, const std::string & out, bool init = true)
Definition at line 24 of file unitsSimple.cpp.
References _valid, validDens(), validFreq(), validLength(), validMass(), validPres(), validTemp(), and validVol().
Referenced by constructConverter(), and icedb::units::implementations::spectralUnits::constructConverter().
                                                                                          :
                 Unithandler("simple"),
                 _inOffset(0), _outOffset(0), _convFactor(1),
                 _inUnits(in), _outUnits(out), _valid(true)
             {
                 if (!init) return;
                 if (validLength(in, out)) return;
                 if (validFreq(in, out)) return;
                 if (validVol(in, out)) return;
                 if (validPres(in, out)) return;
                 if (validMass(in, out)) return;
                 if (validTemp(in, out)) return;
                 if (validDens(in, out)) return;
                 _valid = false;
             }
~simpleUnits()
icedb::units::implementations::simpleUnits::~simpleUnits () virtual
Definition at line 162 of file unitsSimple.cpp.
 {}
Member Function Documentation
canConvert()
bool icedb::units::implementations::simpleUnits::canConvert (Converter_registry_provider::optsType opts) static
Definition at line 10 of file unitsSimple.cpp.
Referenced by icedb::units::implementations::_init().
{
                 const std::string in = opts->getVal<std::string>("inUnits");
                 const std::string out = opts->getVal<std::string>("outUnits");
                 simpleUnits test(in, out);
                 if (test._valid) return true;
                 return false;
             }
constructConverter()
std::shared_ptr< const implementations::Unithandler > icedb::units::implementations::simpleUnits::constructConverter (Converter_registry_provider::optsType opts) static
Definition at line 17 of file unitsSimple.cpp.
References simpleUnits().
Referenced by icedb::units::implementations::_init().
{
                 const std::string in = opts->getVal<std::string>("inUnits");
                 const std::string out = opts->getVal<std::string>("outUnits");
                 std::shared_ptr<simpleUnits> res(new simpleUnits(in, out, true));
                 return res;
             }
convert()
double icedb::units::implementations::simpleUnits::convert (double inVal) const virtual
Implements icedb::units::implementations::Unithandler.
Definition at line 164 of file unitsSimple.cpp.
References _convFactor, _inOffset, _outOffset, and _valid.
             {
                 if (_valid) return ((inVal + _inOffset) * _convFactor) + (_outOffset);
                 throw;
                 //ICEDB_throw(scatdb::ICEDB_LOG_ERROR::ICEDB_LOG_ERROR_types::xBadInput)
                 //  .add<std::string>("Reason", "Trying to convert with bad converter units.")
                 //  ;
                 return 0;
             }
isValid()
bool icedb::units::implementations::simpleUnits::isValid () const virtual
Implements icedb::units::implementations::Unithandler.
Definition at line 163 of file unitsSimple.cpp.
References _valid.
 { return _valid; }
validDens()
bool icedb::units::implementations::simpleUnits::validDens (const std::string & in, const std::string & out)
Definition at line 147 of file unitsSimple.cpp.
References _convFactor.
Referenced by simpleUnits().
{
                 _convFactor = 1.f;
                 // Handling only number density here
                 // TODO: do other types of conversions
                 // Most further stuff requires knowledge of R, thus knowledge of
                 // relative humidity
                 bool inV = false, outV = false;
                 if (in == "m^-3") inV = true;
                 if (in == "cm^-3") { inV = true; _convFactor *= 1e6; }
                 if (out == "cm^-3") { outV = true; _convFactor /= 1e6; }
                 if (out == "m^-3") outV = true;
                 if (inV && outV) { return true; }
                 if (in == "ppmv" && out == "ppmv") { return true; } // ppmv identity
                 return false;
             }
validFreq()
bool icedb::units::implementations::simpleUnits::validFreq (const std::string & _inUnits, const std::string & _outUnits)
Definition at line 65 of file unitsSimple.cpp.
References _convFactor.
Referenced by simpleUnits().
{
                 bool inV = false, outV = false;
                 _convFactor = 1.f;
                 if (_inUnits == "GHz") { _convFactor *= 1e9; inV = true; }
                 if (_inUnits == "MHz") { _convFactor *= 1e6; inV = true; }
                 if (_inUnits == "KHz") { _convFactor *= 1e3; inV = true; }
                 if (_inUnits == "Hz" || _inUnits == "s^-1" || _inUnits == "1/s") inV = true;
                 if (_outUnits == "GHz") { _convFactor /= 1e9; outV = true; }
                 if (_outUnits == "MHz") { _convFactor /= 1e6; outV = true; }
                 if (_outUnits == "KHz") { _convFactor /= 1e3; outV = true; }
                 if (_outUnits == "Hz" || _outUnits == "s^-1" || _outUnits == "1/s") outV = true;
                 if (inV && outV) { return true; }
                 return false;
             }
validLength()
bool icedb::units::implementations::simpleUnits::validLength (const std::string & _inUnits, const std::string & _outUnits)
Definition at line 40 of file unitsSimple.cpp.
References _convFactor.
Referenced by simpleUnits().
{
                 bool inV = false, outV = false;
                 _convFactor = 1.f;
                 if (_inUnits == "nm") { _convFactor /= 1e9; inV = true; }
                 if (_inUnits == "um" || _inUnits == "microns" || _inUnits == "micrometers")
                 {
                     _convFactor /= 1e6; inV = true;
                 }
                 if (_inUnits == "mm") { _convFactor /= 1e3; inV = true; }
                 if (_inUnits == "cm") { _convFactor *= 0.01; inV = true; }
                 if (_inUnits == "km") { _convFactor *= 1000.; inV = true; }
                 if (_inUnits == "m") inV = true;
                 if (_outUnits == "nm") { _convFactor *= 1e9; outV = true; }
                 if (_outUnits == "um" || _outUnits == "microns" || _outUnits == "micrometers")
                 {
                     _convFactor *= 1e6; outV = true;
                 }
                 if (_outUnits == "mm") { _convFactor *= 1e3; outV = true; }
                 if (_outUnits == "cm") { _convFactor *= 100.; outV = true; }
                 if (_outUnits == "km") { _convFactor /= 1000.; outV = true; }
                 if (_outUnits == "m") outV = true;
                 if (inV && outV) { return true; }
                 return false;
             }
validMass()
bool icedb::units::implementations::simpleUnits::validMass (const std::string & in, const std::string & out)
Definition at line 118 of file unitsSimple.cpp.
References _convFactor.
Referenced by simpleUnits().
{
                 bool inV = false, outV = false;
                 _convFactor = 1.f;
                 if (in == "ug") { _convFactor /= 1e9; inV = true; }
                 if (in == "mg") { _convFactor /= 1e6; inV = true; }
                 if (in == "g") { _convFactor /= 1e3; inV = true; }
                 if (in == "kg") inV = true;
                 if (out == "ug") { _convFactor *= 1e9; outV = true; }
                 if (out == "mg") { _convFactor *= 1e6; outV = true; }
                 if (out == "g") { _convFactor *= 1e3; outV = true; }
                 if (out == "kg") outV = true;
                 if (inV && outV) { return true; }
                 return false;
             }
validPres()
bool icedb::units::implementations::simpleUnits::validPres (const std::string & in, const std::string & out)
Definition at line 103 of file unitsSimple.cpp.
References _convFactor.
Referenced by simpleUnits().
{
                 bool inV = false, outV = false;
                 _convFactor = 1.f;
                 if (in == "mb" || in == "millibar") { _convFactor *= 100; inV = true; }
                 if (in == "hPa") { _convFactor *= 100; inV = true; }
                 if (in == "Pa") inV = true;
                 if (in == "kPa") { _convFactor *= 1000; inV = true; }
                 if (in == "bar") { _convFactor *= 100000; inV = true; }
                 if (out == "mb" || out == "millibar" || out == "hPa") { _convFactor /= 100; outV = true; }
                 if (out == "bar") { _convFactor /= 100000; outV = true; }
                 if (out == "Pa") outV = true;
                 if (out == "kPa") { _convFactor /= 1000; outV = true; }
                 if (inV && outV) { return true; }
                 return false;
             }
validTemp()
bool icedb::units::implementations::simpleUnits::validTemp (const std::string & in, const std::string & out)
Definition at line 132 of file unitsSimple.cpp.
References _convFactor, _inOffset, and _outOffset.
Referenced by simpleUnits().
{
                 _convFactor = 1.f;
                 bool inV = false, outV = false;
                 // K - Kelvin, C - Celsius, F - Fahrenheit, R - Rankine
                 if (in == "K" || in == "degK") inV = true;
                 if (in == "C" || in == "degC") { inV = true; _inOffset += 273.15; }
                 if (in == "F" || in == "degF") { inV = true; _convFactor *= 5. / 9.; _inOffset += 459.67; }
                 if (in == "R" || in == "degR") { inV = true; _convFactor *= 5. / 9; }
                 if (out == "K" || out == "degK") outV = true;
                 if (out == "C" || out == "degC") { outV = true; _outOffset -= 273.15; }
                 if (out == "F" || out == "degF") { outV = true; _convFactor *= 9. / 5.; _outOffset -= 459.67; }
                 if (out == "R" || out == "degR") { outV = true; _convFactor *= 9. / 5.; }
                 if (inV && outV) { return true; }
                 return false;
             }
validVol()
bool icedb::units::implementations::simpleUnits::validVol (const std::string & _inUnits, const std::string & _outUnits)
Definition at line 80 of file unitsSimple.cpp.
References _convFactor, _inUnits, and _outUnits.
Referenced by simpleUnits().
{
                 bool inV = false, outV = false;
                 _convFactor = 1.f;
                 std::string in = _inUnits, out = _outUnits;
                 // If it doesn't end in ^3, add it. Used to prevent awkward string manipulations.
                 if (in.find("^3") == std::string::npos) in.append("^3");
                 if (out.find("^3") == std::string::npos) out.append("^3");
                 if (in == "nm^3") { _convFactor /= 1e27; inV = true; }
                 if (in == "um^3") { _convFactor /= 1e18; inV = true; }
                 if (in == "mm^3") { _convFactor /= 1e9; inV = true; }
                 if (in == "cm^3") { _convFactor /= 1e6; inV = true; }
                 if (in == "km^3") { _convFactor *= 1e6; inV = true; }
                 if (in == "m^3") inV = true;
                 if (out == "nm^3") { _convFactor *= 1e27; outV = true; }
                 if (out == "um^3") { _convFactor *= 1e18; outV = true; }
                 if (out == "mm^3") { _convFactor *= 1e9; outV = true; }
                 if (out == "cm^3") { _convFactor *= 1e6; outV = true; }
                 if (out == "km^3") { _convFactor /= 1e6; outV = true; }
                 if (out == "m^3") outV = true;
                 if (inV && outV) { return true; }
                 return false;
             }
Member Data Documentation
_convFactor
double icedb::units::implementations::simpleUnits::_convFactor
Definition at line 28 of file unitsBackend.hpp.
Referenced by convert(), validDens(), validFreq(), validLength(), validMass(), validPres(), validTemp(), and validVol().
_inOffset
double icedb::units::implementations::simpleUnits::_inOffset
Definition at line 28 of file unitsBackend.hpp.
Referenced by convert(), and validTemp().
_inUnits
std::string icedb::units::implementations::simpleUnits::_inUnits
Definition at line 29 of file unitsBackend.hpp.
Referenced by validVol().
_outOffset
double icedb::units::implementations::simpleUnits::_outOffset
Definition at line 28 of file unitsBackend.hpp.
Referenced by convert(), and validTemp().
_outUnits
std::string icedb::units::implementations::simpleUnits::_outUnits
Definition at line 29 of file unitsBackend.hpp.
Referenced by validVol().
_valid
bool icedb::units::implementations::simpleUnits::_valid
Definition at line 30 of file unitsBackend.hpp.
Referenced by convert(), isValid(), and simpleUnits().
The documentation for this struct was generated from the following files:
lib/private/unitsBackend.hpp
lib/src/unitsSimple.cpp