icedb: lib/src/util.cpp File Reference
util.cpp File Reference
#include "../icedb/defs.h"
#include "../icedb/util.h"
#include "../icedb/util.hpp"
#include <cstring>
#include <cwchar>
#include <signal.h>
Namespaces
icedb
Functions
ICEDB_BEGIN_DECL_C ICEDB_SYMBOL_SHARED size_t ICEDB_COMPAT_strncpy_s (char *dest, size_t destSz, const char *src, size_t srcSz)
ICEDB_SYMBOL_SHARED char * ICEDB_COMPAT_strdup_s (const char *src, size_t srcSz)
ICEDB_SYMBOL_SHARED size_t ICEDB_COMPAT_wcsncpy_s (wchar_t *dest, size_t destSz, const wchar_t *src, size_t srcSz)
ICEDB_SYMBOL_SHARED wchar_t * ICEDB_COMPAT_wcsdup_s (const wchar_t *src, size_t srcSz)
ICEDB_SYMBOL_SHARED void * ICEDB_malloc (size_t numBytes)
Allocate memory in bytes. Generally this is just malloced, but a custom allocator may be substituted.
ICEDB_SYMBOL_SHARED void ICEDB_free (void *obj)
Free memory region. Should not be double-freed.
ICEDB_SYMBOL_SHARED void ICEDB_DEBUG_RAISE_EXCEPTION_HANDLER_WC (const wchar_t *file, int line, const wchar_t *fsig)
ICEDB_SYMBOL_SHARED void ICEDB_DEBUG_RAISE_EXCEPTION_HANDLER_A (const char *file, int line, const char *fsig)
ICEDB_SYMBOL_SHARED void * icedb::_malloc (size_t numBytes)
ICEDB_SYMBOL_SHARED void icedb::_free (void *obj)
Function Documentation
ICEDB_COMPAT_strdup_s()
ICEDB_SYMBOL_SHARED char* ICEDB_COMPAT_strdup_s (const char * src, size_t srcSz)
Safe char array initialization and copy. Null appended at end (added to srcSz).
Definition at line 42 of file util.cpp.
References ICEDB_COMPAT_strncpy_s(), ICEDB_DEBUG_RAISE_EXCEPTION, and ICEDB_malloc().
Referenced by error_context_add_string(), and ICEDB_enumModules().
 {
     if (!src) ICEDB_DEBUG_RAISE_EXCEPTION();
     char* res = (char*)ICEDB_malloc(sizeof(char)*(srcSz + 1));
     ICEDB_COMPAT_strncpy_s(res, srcSz + 1, src, srcSz + 1);
     return res;
 }
ICEDB_COMPAT_strncpy_s()
ICEDB_BEGIN_DECL_C ICEDB_SYMBOL_SHARED size_t ICEDB_COMPAT_strncpy_s (char * dest, size_t destSz, const char * src, size_t srcSz)
Safe char array copy.
Returns
the number of characters actually written.
Parameters
dest is the pointer to the destination. Always null terminated.
destSz is the size of the destination buller, including the trailing null character.
src is the pointer to the source. Characters from src are copied either until the first null character or until srcSz. Note that null termination comes later.
srcSz is the max size of the source buffer.
Definition at line 14 of file util.cpp.
References ICEDB_DEBUG_RAISE_EXCEPTION.
Referenced by error_code_to_message(), error_context_append(), error_context_copy(), error_context_create_impl(), error_context_to_message(), error_context_to_message_size(), error_context_widen(), icedb::versioning::genVersionInfo(), ICEDB_COMPAT_strdup_s(), ICEDB_findModuleByFunc(), ICEDB_getAppDir(), ICEDB_getAppPath(), ICEDB_getCWD(), ICEDB_getLibDir(), ICEDB_getLibPath(), ICEDB_getPluginDir(), and ICEDB_WriteLibVersionInfoC().
 {
     if (!dest || !src)ICEDB_DEBUG_RAISE_EXCEPTION();
 #if ICEDB_USING_SECURE_STRINGS
     strncpy_s(dest, destSz, src, srcSz);
 #else
     if (srcSz <= destSz) {
         strncpy(dest, src, srcSz);
     }
     else {
         strncpy(dest, src, destSz);
     }
 #endif
     dest[destSz - 1] = 0;
     for (size_t i = 0; i < destSz; ++i) if (dest[i] == '\0') return i;
     return 0; // Should never be reached
 }
ICEDB_COMPAT_wcsdup_s()
ICEDB_SYMBOL_SHARED wchar_t* ICEDB_COMPAT_wcsdup_s (const wchar_t * src, size_t srcSz)
Safe char array initialization and copy. Null appended at end (added to srcSz).
Definition at line 80 of file util.cpp.
References ICEDB_COMPAT_wcsncpy_s(), ICEDB_DEBUG_RAISE_EXCEPTION, and ICEDB_malloc().
 {
     if (!src) ICEDB_DEBUG_RAISE_EXCEPTION();
     wchar_t* res = (wchar_t*)ICEDB_malloc(sizeof(wchar_t)*(srcSz + 1));
     ICEDB_COMPAT_wcsncpy_s(res, srcSz + 1, src, srcSz + 1);
     return res;
 }
ICEDB_COMPAT_wcsncpy_s()
ICEDB_SYMBOL_SHARED size_t ICEDB_COMPAT_wcsncpy_s (wchar_t * dest, size_t destSz, const wchar_t * src, size_t srcSz)
Safe char array copy.
Returns
the number of characters actually written.
Parameters
dest is the pointer to the destination. Always null terminated.
destSz is the size of the destination buller, including the trailing null character.
src is the pointer to the source. Characters from src are copied either until the first null character or until srcSz. Note that null termination comes later.
srcSz is the max size of the source buffer.
Definition at line 52 of file util.cpp.
References ICEDB_DEBUG_RAISE_EXCEPTION.
Referenced by ICEDB_COMPAT_wcsdup_s().
 {
     if (!dest || !src)ICEDB_DEBUG_RAISE_EXCEPTION();
 #if ICEDB_USING_SECURE_STRINGS
     wcsncpy_s(dest, destSz, src, srcSz);
 #else
     if (srcSz <= destSz) {
         wcsncpy(dest, src, srcSz);
     }
     else {
         wcsncpy(dest, src, destSz);
     }
 #endif
     dest[destSz - 1] = 0;
     for (size_t i = 0; i < destSz; ++i) if (dest[i] == '\0') return i;
     return 0; // Should never be reached
 }
ICEDB_DEBUG_RAISE_EXCEPTION_HANDLER_A()
ICEDB_SYMBOL_SHARED void ICEDB_DEBUG_RAISE_EXCEPTION_HANDLER_A (const char * file, int line, const char * fsig)
Definition at line 113 of file util.cpp.
References ICEDB_BEGIN_DECL, ICEDB_COMPAT_fprintf_s, and ICEDB_END_DECL_C.
 {
     ICEDB_COMPAT_fprintf_s(stderr, "Exception raised in file %s, line %d, function %s.\n", file, line, fsig);
 #ifdef _WIN32
     DebugBreak();
 #else
     raise(SIGTRAP);
     exit(999);
 #endif
 }
ICEDB_DEBUG_RAISE_EXCEPTION_HANDLER_WC()
ICEDB_SYMBOL_SHARED void ICEDB_DEBUG_RAISE_EXCEPTION_HANDLER_WC (const wchar_t * file, int line, const wchar_t * fsig)
Definition at line 102 of file util.cpp.
References ICEDB_COMPAT_fwprintf_s.
 {
     ICEDB_COMPAT_fwprintf_s(stderr, L"Exception raised in file %s, line %d, function %s.\n", file, line, fsig);
 #ifdef _WIN32
     DebugBreak();
 #else
     raise(SIGTRAP);
     exit(999);
 #endif
 }
ICEDB_free()
ICEDB_SYMBOL_SHARED void ICEDB_free (void * obj)
Free memory region. Should not be double-freed.
Definition at line 97 of file util.cpp.
References icedb::free(), and ICEDB_DEBUG_RAISE_EXCEPTION.
Referenced by icedb::_free(), error_context_append(), error_context_create_impl(), error_context_deallocate(), error_context_to_message(), error_context_to_message_size(), error_context_widen(), ICEDB_free_enumModulesRes(), and icedb::os_functions::populateOSstrings().
 {
     if (!obj) ICEDB_DEBUG_RAISE_EXCEPTION();
     free(obj);
 }
ICEDB_malloc()
ICEDB_SYMBOL_SHARED void* ICEDB_malloc (size_t numBytes)
Allocate memory in bytes. Generally this is just malloced, but a custom allocator may be substituted.
Definition at line 90 of file util.cpp.
References ICEDB_DEBUG_RAISE_EXCEPTION, and icedb::malloc().
Referenced by icedb::_malloc(), error_context_append(), error_context_copy(), error_context_create_impl(), error_context_to_message(), error_context_to_message_size(), error_context_widen(), ICEDB_COMPAT_strdup_s(), ICEDB_COMPAT_wcsdup_s(), ICEDB_enumModules(), and icedb::os_functions::populateOSstrings().
 {
     void* res = malloc(numBytes);
     if (!res) ICEDB_DEBUG_RAISE_EXCEPTION();
     return res;
 }