icedb: lib/src/versioning.cpp File Reference
versioning.cpp File Reference
#include "../icedb/versioning/versioning.hpp"
#include "../icedb/util.h"
#include <sstream>
Namespaces
icedb
icedb::versioning
icedb::versioning::internal
Macros
#define tryNum(x) if (a->vn[versionInfo:: x] != b->vn[versionInfo:: x]) return res;
#define tryBool(x) if (a->vb[versionInfo:: x] != b->vb[versionInfo:: x]) return res;
#define tryStr(x) if (std::strncmp(a-> x, b-> x, versionInfo::charmax) != 0) return res;
#define tryNumB(x) if ((a->vn[versionInfo:: x] != b->vn[versionInfo:: x]) && a->vn[versionInfo:: x]) return res;
Functions
ICEDB_ver_match icedb::versioning::compareVersions (const versionInfo_p a, const versionInfo_p b)
void icedb::versioning::getLibVersionInfo (versionInfo &out)
versionInfo_p icedb::versioning::getLibVersionInfo ()
ICEDB_BEGIN_DECL_C void ICEDB_VersionInfo_Free (ICEDB_VersionInfo_p p)
ICEDB_VersionInfo_p ICEDB_getLibVersionInfo ()
const char * ICEDB_WriteLibVersionInfoCC (ICEDB_VersionInfo_p p)
char * ICEDB_WriteLibVersionInfoC (ICEDB_VersionInfo_p p, char *buf, size_t sz)
ICEDB_ver_match ICEDB_CompareVersions (const ICEDB_VersionInfo_p a, const ICEDB_VersionInfo_p b)
Variables
versionInfo_p icedb::versioning::internal::ver_int
Macro Definition Documentation
tryBool
#define tryBool (x) if (a->vb[versionInfo:: x] != b->vb[versionInfo:: x]) return res;
Referenced by icedb::versioning::compareVersions().
tryNum
#define tryNum (x) if (a->vn[versionInfo:: x] != b->vn[versionInfo:: x]) return res;
Referenced by icedb::versioning::compareVersions().
tryNumB
#define tryNumB (x) if ((a->vn[versionInfo:: x] != b->vn[versionInfo:: x]) && a->vn[versionInfo:: x]) return res;
Referenced by icedb::versioning::compareVersions().
tryStr
#define tryStr (x) if (std::strncmp(a-> x, b-> x, versionInfo::charmax) != 0) return res;
Referenced by icedb::versioning::compareVersions().
Function Documentation
ICEDB_CompareVersions()
ICEDB_ver_match ICEDB_CompareVersions (const ICEDB_VersionInfo_p a, const ICEDB_VersionInfo_p b)
Definition at line 98 of file versioning.cpp.
References icedb::versioning::compareVersions(), ICEDB_END_DECL_C, and ICEDB_VersionInfo::p.
{
     return icedb::versioning::compareVersions(a->p, b->p);
 }
ICEDB_getLibVersionInfo()
ICEDB_VersionInfo_p ICEDB_getLibVersionInfo ()
Definition at line 80 of file versioning.cpp.
References icedb::versioning::getLibVersionInfo(), and ICEDB_VersionInfo::p.
{
     ICEDB_VersionInfo_p res(new ICEDB_VersionInfo);
     res->p = icedb::versioning::getLibVersionInfo();
     return res;
 }
ICEDB_VersionInfo_Free()
ICEDB_BEGIN_DECL_C void ICEDB_VersionInfo_Free (ICEDB_VersionInfo_p p)
Definition at line 78 of file versioning.cpp.
 { if (p) delete p; }
ICEDB_WriteLibVersionInfoC()
char* ICEDB_WriteLibVersionInfoC (ICEDB_VersionInfo_p p, char * buf, size_t sz)
Definition at line 93 of file versioning.cpp.
References ICEDB_COMPAT_strncpy_s(), ICEDB_WriteLibVersionInfoCC(), and ICEDB_VersionInfo::vstr.
{
     ICEDB_WriteLibVersionInfoCC(p);
     ICEDB_COMPAT_strncpy_s(buf, sz, p->vstr.c_str(), p->vstr.size());
     return buf;
 }
ICEDB_WriteLibVersionInfoCC()
const char* ICEDB_WriteLibVersionInfoCC (ICEDB_VersionInfo_p p)
Definition at line 86 of file versioning.cpp.
References icedb::versioning::debug_preamble(), ICEDB_VersionInfo::p, and ICEDB_VersionInfo::vstr.
Referenced by ICEDB_WriteLibVersionInfoC().
{
     if (p->vstr.size()) return p->vstr.c_str();
     std::ostringstream out;
     icedb::versioning::debug_preamble(*(p->p.get()), out);
     p->vstr = out.str();
     return p->vstr.c_str();
 }