icedb: lib/icedb/versioning/versioningForwards.h File Reference
versioningForwards.h File Reference
#include "../defs.h"
Macros
#define ICEDB_H_VERSIONING_FORWARDS
Typedefs
typedef ICEDB_VersionInfo * ICEDB_VersionInfo_p
Enumerations
enum ICEDB_ver_match {
ICEDB_VER_INCOMPATIBLE, ICEDB_VER_COMPATIBLE_1, ICEDB_VER_COMPATIBLE_2, ICEDB_VER_COMPATIBLE_3,
ICEDB_VER_EXACT_MATCH
}
Functions
DL_ICEDB void ICEDB_VersionInfo_Free (ICEDB_VersionInfo_p)
DL_ICEDB ICEDB_VersionInfo_p ICEDB_getLibVersionInfo ()
DL_ICEDB char * ICEDB_WriteLibVersionInfoC (ICEDB_VersionInfo_p, char *, size_t sz)
DL_ICEDB const char * ICEDB_WriteLibVersionInfoCC (ICEDB_VersionInfo_p)
DL_ICEDB ICEDB_ver_match ICEDB_CompareVersions (const ICEDB_VersionInfo_p a, const ICEDB_VersionInfo_p b)
Macro Definition Documentation
ICEDB_H_VERSIONING_FORWARDS
#define ICEDB_H_VERSIONING_FORWARDS
Definition at line 3 of file versioningForwards.h.
Typedef Documentation
ICEDB_VersionInfo_p
typedef ICEDB_VersionInfo* ICEDB_VersionInfo_p
Definition at line 13 of file versioningForwards.h.
Enumeration Type Documentation
ICEDB_ver_match
enum ICEDB_ver_match
Enumerator
ICEDB_VER_INCOMPATIBLE
ICEDB_VER_COMPATIBLE_1
ICEDB_VER_COMPATIBLE_2
ICEDB_VER_COMPATIBLE_3
ICEDB_VER_EXACT_MATCH
Definition at line 7 of file versioningForwards.h.
                      {
     ICEDB_VER_INCOMPATIBLE, ICEDB_VER_COMPATIBLE_1,
     ICEDB_VER_COMPATIBLE_2, ICEDB_VER_COMPATIBLE_3,
     ICEDB_VER_EXACT_MATCH
 };
Function Documentation
ICEDB_CompareVersions()
DL_ICEDB ICEDB_ver_match ICEDB_CompareVersions (const ICEDB_VersionInfo_p a, const ICEDB_VersionInfo_p b)
Definition at line 98 of file versioning.cpp.
References icedb::versioning::compareVersions(), ICEDB_END_DECL_C, and ICEDB_VersionInfo::p.
{
     return icedb::versioning::compareVersions(a->p, b->p);
 }
ICEDB_getLibVersionInfo()
DL_ICEDB ICEDB_VersionInfo_p ICEDB_getLibVersionInfo ()
Definition at line 80 of file versioning.cpp.
References icedb::versioning::getLibVersionInfo(), and ICEDB_VersionInfo::p.
{
     ICEDB_VersionInfo_p res(new ICEDB_VersionInfo);
     res->p = icedb::versioning::getLibVersionInfo();
     return res;
 }
ICEDB_VersionInfo_Free()
DL_ICEDB void ICEDB_VersionInfo_Free (ICEDB_VersionInfo_p)
Definition at line 78 of file versioning.cpp.
 { if (p) delete p; }
ICEDB_WriteLibVersionInfoC()
DL_ICEDB char* ICEDB_WriteLibVersionInfoC (ICEDB_VersionInfo_p , char * , size_t sz)
Definition at line 93 of file versioning.cpp.
References ICEDB_COMPAT_strncpy_s(), ICEDB_WriteLibVersionInfoCC(), and ICEDB_VersionInfo::vstr.
{
     ICEDB_WriteLibVersionInfoCC(p);
     ICEDB_COMPAT_strncpy_s(buf, sz, p->vstr.c_str(), p->vstr.size());
     return buf;
 }
ICEDB_WriteLibVersionInfoCC()
DL_ICEDB const char* ICEDB_WriteLibVersionInfoCC (ICEDB_VersionInfo_p)
Definition at line 86 of file versioning.cpp.
References icedb::versioning::debug_preamble(), ICEDB_VersionInfo::p, and ICEDB_VersionInfo::vstr.
Referenced by ICEDB_WriteLibVersionInfoC().
{
     if (p->vstr.size()) return p->vstr.c_str();
     std::ostringstream out;
     icedb::versioning::debug_preamble(*(p->p.get()), out);
     p->vstr = out.str();
     return p->vstr.c_str();
 }