#pragma once
#ifndef ICEDB_PLUGIN_NETCDF_H_INTERFACE
#define ICEDB_PLUGIN_NETCDF_H_INTERFACE

#include "../../libicedb/icedb/dlls/linking.h"
#include <netcdf.h>

ICEDB_DLL_INTERFACE_BEGIN(netcdf)

ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_libvers, const char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_strerror, const char*, int)

ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_open, int, const char*, int, int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_close, int, int)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_create, int, const char*, int, int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_redef, int, int)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_enddef, int, int)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq, int, int, int*, int*, int*, int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_ndims, int, int, int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_nvars, int, int, int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_natts, int, int, int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_unlimdim, int, int, int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_format, int, int, int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_sync, int, int)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_abort, int, int)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_set_fill, int, int, int, int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_set_default_format, int, int, int*)

ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_ncid, int, int, char*, int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_grps, int, int, int*, int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_varids, int, int, int*, int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_dimids, int, int, int*, int*, int)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_grpname, int, int, char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_grpname_full, int, int, size_t*, char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_grpname_len, int, int, size_t*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_grp_parent, int, int, int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_def_grp, int, int, char*, int*)

ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_def_dim, int, int, const char*, size_t, int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_dimid, int, int, const char*, int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_dim, int, int, int, char*, size_t*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_dimname, int, int, int, char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_dimlen, int, int, int, size_t*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_rename_dim, int, int, int, const char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_unlimdims, int, int, int*, int*)

ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_typeids, int, int, int*, int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_type, int, int, nc_type, char*, size_t*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_user_type, int, int, nc_type, char*, size_t*, nc_type*, size_t*, int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_def_compound, int, int, size_t, char*, nc_type*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_insert_compound, int, nc_type, char*, size_t, nc_type)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_insert_array_compound, int, int, nc_type, char*, size_t, nc_type, int, int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_compound, int, int, nc_type, char*, size_t*, size_t*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_compound_name, int, int, nc_type, char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_compound_size, int, int, nc_type, size_t*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_compound_nfields, int, int, nc_type, size_t*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_compound_field, int, int, nc_type, int, char*, size_t*, nc_type*, int*, int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_compound_fieldname, int, nc_type, int, char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_compound_fieldindex, int, nc_type, char*, int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_compound_fieldoffset, int, nc_type, int, size_t*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_compound_fieldtype, int, nc_type, int, nc_type*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_compound_fieldndims, int, int, nc_type, int, int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_compound_fielddim_sizes, int, int, nc_type, int, int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_def_vlen, int, int, char*, nc_type, nc_type*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_vlen, int, int, nc_type, char*, size_t*, nc_type*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_free_vlen, int, nc_vlen_t*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_def_opaque, int, int, char*, size_t, nc_type*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_opaque, int, int, nc_type, char*, size_t*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_def_enum, int, int, nc_type, const char*, nc_type*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_insert_enum, int, int, nc_type, const char*, const void*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_enum, int, int, nc_type, char*, nc_type*, size_t*, size_t*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_enum_member, int, int, nc_type, int, char*, void*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_enum_ident,int, nc_type, long long, char*)

ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_def_var, int, int, const char*, nc_type, int, const int[], int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_def_var_chunking, int, int, int, int, size_t*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_var_chunking, int, int, int, int*, int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_def_var_fill, int, int, int, int, void*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_var_fill, int, int, int, int*, void*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_def_var_deflate, int, int, int, int, int, int)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_var_deflate, int, int, int, int*, int*, int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_def_var_fletcher32, int, int, int, int)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_var_fletcher32, int, int, int, int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_def_var_endian, int, int, int, int)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_var_endian, int, int, int, int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_varid, int, int, const char*, int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_var, int, int, int, char*, nc_type*, int*, int[], int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_varname, int, int, int, char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_vartype, int, int, int, nc_type*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_varndims, int, int, int, int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_vardimid, int, int, int, int[])
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_varnatts, int, int, int, int*)

ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_var1_text, int, int, int, const size_t[], const char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_var1_uchar, int, int, int, const size_t[], const unsigned char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_var1_schar, int, int, int, const size_t[], const signed char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_var1_short, int, int, int, const size_t[], const short*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_var1_int, int, int, int, const size_t[], const int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_var1_long, int, int, int, const size_t[], const long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_var1_float, int, int, int, const size_t[], const float*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_var1_double, int, int, int, const size_t[], const double*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_var1_ubyte, int, int, int, const size_t[], const unsigned char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_var1_ushort, int, int, int, const size_t[], const unsigned short*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_var1_uint, int, int, int, const size_t[], const unsigned int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_var1_longlong, int, int, int, const size_t[], const long long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_var1_ulonglong, int, int, int, const size_t[], const unsigned long long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_var1_string, int, int, int, const size_t[], const char**)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_var1, int, int, int, const size_t*, const void*)

ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_var_text, int, int, int, const char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_var_uchar, int, int, int, const unsigned char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_var_schar, int, int, int, const signed char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_var_short, int, int, int, const short*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_var_int, int, int, int, const int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_var_long, int, int, int, const long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_var_float, int, int, int, const float*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_var_double, int, int, int, const double*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_var_ubyte, int, int, int, const unsigned char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_var_ushort, int, int, int, const unsigned short*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_var_uint, int, int, int, const unsigned int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_var_longlong, int, int, int, const long long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_var_ulonglong, int, int, int, const unsigned long long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_var_string, int, int, int, const char**)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_var, int, int, int, const void*)

ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_vara_text, int, int, int, const size_t[], const size_t[], const char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_vara_uchar, int, int, int, const size_t[], const size_t[], const unsigned char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_vara_schar, int, int, int, const size_t[], const size_t[], const signed char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_vara_short, int, int, int, const size_t[], const size_t[], const short*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_vara_int, int, int, int, const size_t[], const size_t[], const int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_vara_long, int, int, int, const size_t[], const size_t[], const long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_vara_float, int, int, int, const size_t[], const size_t[], const float*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_vara_double, int, int, int, const size_t[], const size_t[], const double*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_vara_ubyte, int, int, int, const size_t[], const size_t[], const unsigned char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_vara_ushort, int, int, int, const size_t[], const size_t[], const unsigned short*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_vara_uint, int, int, int, const size_t[], const size_t[], const unsigned int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_vara_longlong, int, int, int, const size_t[], const size_t[], const long long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_vara_ulonglong, int, int, int, const size_t[], const size_t[], const unsigned long long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_vara_string, int, int, int, const size_t[], const size_t[], const char**)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_vara, int, int, int, const size_t[], const size_t*, const void*)

ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_vars_text, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_vars_uchar, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const unsigned char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_vars_schar, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const signed char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_vars_short, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const short*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_vars_int, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_vars_long, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_vars_float, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const float*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_vars_double, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const double*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_vars_ubyte, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const unsigned char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_vars_ushort, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const unsigned short*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_vars_uint, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const unsigned int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_vars_longlong, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const long long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_vars_ulonglong, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const unsigned long long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_vars_string, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const char**)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_vars, int, int, int, const size_t[], const size_t[], const ptrdiff_t*, const void*)

ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_varm_text, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const ptrdiff_t[], const char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_varm_uchar, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const ptrdiff_t[], const unsigned char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_varm_schar, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const ptrdiff_t[], const signed char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_varm_short, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const ptrdiff_t[], const short*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_varm_int, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const ptrdiff_t[], const int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_varm_long, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const ptrdiff_t[], const long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_varm_float, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const ptrdiff_t[], const float*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_varm_double, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const ptrdiff_t[], const double*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_varm_ubyte, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const ptrdiff_t[], const unsigned char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_varm_ushort, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const ptrdiff_t[], const unsigned short*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_varm_uint, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const ptrdiff_t[], const unsigned int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_varm_longlong, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const ptrdiff_t[], const long long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_varm_ulonglong, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const ptrdiff_t[], const unsigned long long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_varm_string, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const ptrdiff_t[], const char**)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_varm, int, int, int, const size_t[], const size_t[], const ptrdiff_t*, const ptrdiff_t*, const void*)

ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_var1_text, int, int, int, const size_t[], char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_var1_uchar, int, int, int, const size_t[], unsigned char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_var1_schar, int, int, int, const size_t[], signed char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_var1_short, int, int, int, const size_t[], short*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_var1_int, int, int, int, const size_t[], int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_var1_long, int, int, int, const size_t[], long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_var1_float, int, int, int, const size_t[], float*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_var1_double, int, int, int, const size_t[], double*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_var1_ubyte, int, int, int, const size_t[], unsigned char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_var1_ushort, int, int, int, const size_t[], unsigned short*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_var1_uint, int, int, int, const size_t[], unsigned int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_var1_longlong, int, int, int, const size_t[], long long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_var1_ulonglong, int, int, int, const size_t[], unsigned long long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_var1_string, int, int, int, const size_t[], char**)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_var1, int, int, int, const size_t*, void*)

ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_var_text, int, int, int, char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_var_uchar, int, int, int, unsigned char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_var_schar, int, int, int, signed char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_var_short, int, int, int, short*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_var_int, int, int, int, int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_var_long, int, int, int, long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_var_float, int, int, int, float*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_var_double, int, int, int, double*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_var_ubyte, int, int, int, unsigned char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_var_ushort, int, int, int, unsigned short*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_var_uint, int, int, int, unsigned int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_var_longlong, int, int, int, long long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_var_ulonglong, int, int, int, unsigned long long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_var_string, int, int, int, char**)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_var, int, int, int, void*)

ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_vara_text, int, int, int, const size_t[], const size_t[], char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_vara_uchar, int, int, int, const size_t[], const size_t[], unsigned char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_vara_schar, int, int, int, const size_t[], const size_t[], signed char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_vara_short, int, int, int, const size_t[], const size_t[], short*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_vara_int, int, int, int, const size_t[], const size_t[], int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_vara_long, int, int, int, const size_t[], const size_t[], long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_vara_float, int, int, int, const size_t[], const size_t[], float*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_vara_double, int, int, int, const size_t[], const size_t[], double*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_vara_ubyte, int, int, int, const size_t[], const size_t[], unsigned char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_vara_ushort, int, int, int, const size_t[], const size_t[], unsigned short*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_vara_uint, int, int, int, const size_t[], const size_t[], unsigned int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_vara_longlong, int, int, int, const size_t[], const size_t[], long long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_vara_ulonglong, int, int, int, const size_t[], const size_t[], unsigned long long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_vara_string, int, int, int, const size_t[], const size_t[], char**)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_vara, int, int, int, const size_t[], const size_t*, void*)

ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_vars_text, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_vars_uchar, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const unsigned char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_vars_schar, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const signed char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_vars_short, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const short*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_vars_int, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_vars_long, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_vars_float, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const float*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_vars_double, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const double*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_vars_ubyte, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const unsigned char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_vars_ushort, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const unsigned short*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_vars_uint, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const unsigned int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_vars_longlong, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const long long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_vars_ulonglong, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const unsigned long long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_vars_string, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const char**)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_vars, int, int, int, const size_t[], const size_t[], const ptrdiff_t*, const void*)

ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_varm_text, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const ptrdiff_t[], const char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_varm_uchar, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const ptrdiff_t[], const unsigned char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_varm_schar, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const ptrdiff_t[], const signed char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_varm_short, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const ptrdiff_t[], const short*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_varm_int, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const ptrdiff_t[], const int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_varm_long, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const ptrdiff_t[], const long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_varm_float, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const ptrdiff_t[], const float*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_varm_double, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const ptrdiff_t[], const double*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_varm_ubyte, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const ptrdiff_t[], const unsigned char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_varm_ushort, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const ptrdiff_t[], const unsigned short*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_varm_uint, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const ptrdiff_t[], const unsigned int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_varm_longlong, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const ptrdiff_t[], const long long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_varm_ulonglong, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const ptrdiff_t[], const unsigned long long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_varm_string, int, int, int, const size_t[], const size_t[], const ptrdiff_t[], const ptrdiff_t[], const char**)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_varm, int, int, int, const size_t[], const size_t[], const ptrdiff_t*, const ptrdiff_t*, const void*)

ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_free_string, int, size_t, char**)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_rename_var, int, int, int, const char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_copy_var, int, int, int, int)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_var_par_access, int, int, int, int)

ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_att_text, int, int, int, const char*, size_t, const char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_att_uchar, int, int, int, const char*, nc_type, size_t, const unsigned char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_att_schar, int, int, int, const char*, nc_type, size_t, const signed char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_att_short, int, int, int, const char*, nc_type, size_t, const short*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_att_int, int, int, int, const char*, nc_type, size_t, const int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_att_long, int, int, int, const char*, nc_type, size_t, const long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_att_float, int, int, int, const char*, nc_type, size_t, const float*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_att_double, int, int, int, const char*, nc_type, size_t, const double*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_att_ubyte, int, int, int, const char*, nc_type, size_t, const unsigned char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_att_ushort, int, int, int, const char*, nc_type, size_t, const unsigned short*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_att_uint, int, int, int, const char*, nc_type, size_t, const unsigned int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_att_longlong, int, int, int, const char*, nc_type, size_t, const long long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_att_ulonglong, int, int, int, const char*, nc_type, size_t, const unsigned long long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_att_string, int, int, int, const char*, size_t, const char**)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_put_att, int, int, int, const char*, nc_type, size_t, const void*)

ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_att, int, int, int, const char*, nc_type*, size_t*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_atttype, int, int, int, const char*, nc_type*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_attlen, int, int, int, const char*, size_t*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_attname, int, int, int, int, char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_inq_attid, int, int, int, const char*, int*)

ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_att_text, int, int, int, const char*, char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_att_uchar, int, int, int, const char*, unsigned char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_att_schar, int, int, int, const char*, signed char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_att_short, int, int, int, const char*, short*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_att_int, int, int, int, const char*, int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_att_long, int, int, int, const char*, long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_att_float, int, int, int, const char*, float*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_att_double, int, int, int, const char*, double*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_att_ubyte, int, int, int, const char*, unsigned char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_att_ushort, int, int, int, const char*, unsigned short*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_att_uint, int, int, int, const char*, unsigned int*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_att_longlong, int, int, int, const char*, long long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_att_ulonglong, int, int, int, const char*, unsigned long long*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_att_string, int, int, int, const char*, char**)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_get_att, int, int, int, const char*, void*)

ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_del_att, int, int, int, const char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_rename_att, int, int, int, const char*, const char*)
ICEDB_DLL_INTERFACE_DECLARE_FUNCTION(netcdf, nc_copy_att, int, int, int, const char*, int, int)

ICEDB_DLL_INTERFACE_END


#endif
