#pragma once
#ifndef ICEDB_H_MEMINTERFACEIMPL
#define ICEDB_H_MEMINTERFACEIMPL
#include "mem.h"
#include "memInterface.h"
#include "../dlls/dllsInterfaceImpl.hpp"

ICEDB_DLL_INTERFACE_IMPLEMENTATION_BEGIN(ICEDB_core_mem);
ICEDB_DLL_INTERFACE_IMPLEMENTATION_SYMBOL_FUNCTION(ICEDB_core_mem, malloc, "ICEDB_malloc", void*, size_t);
ICEDB_DLL_INTERFACE_IMPLEMENTATION_SYMBOL_FUNCTION(ICEDB_core_mem, free, "ICEDB_free", void, void*);
ICEDB_DLL_INTERFACE_IMPLEMENTATION_CONSTRUCTOR(ICEDB_core_mem);
ICEDB_DLL_INTERFACE_IMPLEMENTATION_FUNCTION(ICEDB_core_mem, malloc, void*, size_t);
ICEDB_DLL_INTERFACE_IMPLEMENTATION_FUNCTION(ICEDB_core_mem, free, void, void*);
ICEDB_DLL_INTERFACE_IMPLEMENTATION_END(ICEDB_core_mem);



#endif
