icedb: icedb::Tables::Table Class Reference
icedb::Tables::Table Class Reference abstract
#include <Table.hpp>
Public Types
typedef std::vector< size_t > Dimensions_Type
The dimensions of a Table are expressed as a vector of unsigned integers.
typedef std::unique_ptr< Table > Table_Type
The preferred method of access of a Table is through std::unique_ptr.
Public Member Functions
virtual ~Table ()
size_t getNumDimensions () const
Returns the number of dimensions of a table.
Dimensions_Type getDimensions () const
Returns a vector containing the dimensions of the table.
void attachDimensionScale (size_t DimensionNumber, gsl::not_null< const Table *> scale)
void detachDimensionScale (size_t DimensionNumber, gsl::not_null< const Table *> scale)
Detaches a dimension scale from this table.
bool isDimensionScale () const
Is this Table used as a dimension scale?
void setDimensionScale (const std::string &dimensionScaleName)
Designate this table as a dimension scale.
void setDimensionScaleAxisLabel (size_t DimensionNumber, const std::string &label)
Set the axis label for the dimension designated by DimensionNumber.
std::string getDimensionScaleAxisLabel (size_t DimensionNumber) const
Get the axis label for the dimension designated by DimensionNumber.
std::string getDimensionScaleName () const
Get the name of this table's defined dimension scale.
template<class Type >
bool isTableOfType () const
Check if this table has the matching Type.
std::type_index getTableTypeId () const
Get the type of the table (i.e. int64_t, float, etc.)
template<class DataType >
void readAll (std::vector< size_t > &dims, std::vector< DataType > &data) const
Read all of the data in the associated table.
template<class DataType >
void writeAll (const gsl::span< const DataType > &outData) const
Write the passed data to the table. Writes whole table.
template<class DataType >
void writeAll (const gsl::span< DataType > &outData) const
Write the passed data to the table. Writes whole table.
template<class DataType >
void writeAll (const std::vector< DataType > &outData) const
Write the passed data to the table. Writes whole table. Convenience converter function.
Public Member Functions inherited from icedb::Attributes::CanHaveAttributes
~CanHaveAttributes ()
bool doesAttributeExist (const std::string &attributeName) const
Does the object have an attribute with the given name?
std::type_index getAttributeTypeId (const std::string &attributeName) const
Returns the type of an attribute.
template<class Type >
bool isAttributeOfType (const std::string &attributeName) const
Is the type of the attribute "Type"?
std::set< std::string > getAttributeNames () const
List all attributes attached to this object.
void deleteAttribute (const std::string &attributeName)
Delete an attribute, by name, that is attached to this object.
template<class DataType >
void readAttributeData (const std::string &attributeName, std::vector< size_t > &dimensions, std::vector< DataType > &data) const
Function to read the data from an attribute using the provided input vectors.
template<class DataType >
void writeAttributeData (const std::string &attributeName, const std::vector< size_t > &dimensionas, const std::vector< DataType > &data)
Function to write an attribute to an object, with the provided raw data.
template<class DataType >
Attribute< DataType > readAttribute (const std::string &attributeName) const
Convenience function to read an attribute's data and return an Attribute object.
template<class DataType >
void writeAttribute (const Attribute< DataType > &attribute)
Convenience function to write an Attribute to an object.
template<class DataType >
void writeAttribute (const std::string &name, std::initializer_list< size_t > dims, std::initializer_list< DataType > data)
Convenience function to write a small Attribute to an object, using initializer lists.
Public Attributes
const std::string name
The name of the Table.
Protected Member Functions
virtual void _setTableSelf (std::shared_ptr< H5::DataSet > obj)=0
Associates the icedb table with the fundamental HDF5 DataSet. Only used internally.
virtual std::shared_ptr< H5::DataSet > _getTableSelf () const =0
Gets the fundamental HDF5 DataSet associated with the table. Only used internally.
bool valid () const
Checks that Table is well-formed during runtime. Only used internally.
Table (const std::string &name="")
Default constructor, used by CanHaveTables.
Protected Member Functions inherited from icedb::Attributes::CanHaveAttributes
CanHaveAttributes ()
virtual void _setAttributeParent (std::shared_ptr< H5::H5Object > obj)=0
virtual std::shared_ptr< H5::H5Object > _getAttributeParent () const =0
Private Member Functions
template<class DataType >
void writeAllInner (const gsl::span< const DataType > &outData) const
Friends
class CanHaveTables
Additional Inherited Members
Static Public Member Functions inherited from icedb::Attributes::CanHaveAttributes
static bool doesAttributeExist (gsl::not_null< const H5::H5Object *> parent, const std::string &attributeName)
Does an object (parent) have an attribute with the given name?
static std::type_index getAttributeTypeId (gsl::not_null< const H5::H5Object *> parent, const std::string &attributeName)
Returns the type of an attribute.
template<class DataType >
static void readAttributeData (gsl::not_null< const H5::H5Object *> parent, const std::string &attributeName, std::vector< size_t > &dimensions, std::vector< DataType > &data)
Function to read the data from an attribute.
template<class DataType >
static Attribute< DataType > readAttribute (gsl::not_null< const H5::H5Object *> obj, const std::string &attributeName)
Convenience function to read an attribute's data and return an Attribute object.
Detailed Description
This defines a table.
See also
CanHaveTables for the functions to create, access and remove tables.
Definition at line 16 of file Table.hpp.
Member Typedef Documentation
Dimensions_Type
typedef std::vector<size_t> icedb::Tables::Table::Dimensions_Type
The dimensions of a Table are expressed as a vector of unsigned integers.
Definition at line 33 of file Table.hpp.
Table_Type
typedef std::unique_ptr<Table> icedb::Tables::Table::Table_Type
The preferred method of access of a Table is through std::unique_ptr.
Definition at line 35 of file Table.hpp.
Constructor & Destructor Documentation
Table()
icedb::Tables::Table::Table (const std::string & name = "") protected
Default constructor, used by CanHaveTables.
Definition at line 11 of file Tables.cpp.
 : name{ name } {}
~Table()
icedb::Tables::Table::~Table () virtual
Definition at line 10 of file Tables.cpp.
 {}
Member Function Documentation
_getTableSelf()
virtual std::shared_ptr<H5::DataSet> icedb::Tables::Table::_getTableSelf () const protected pure virtual
Gets the fundamental HDF5 DataSet associated with the table. Only used internally.
Implemented in icedb::Tables::Table_impl.
Referenced by attachDimensionScale(), detachDimensionScale(), getDimensions(), getDimensionScaleAxisLabel(), getDimensionScaleName(), getNumDimensions(), getTableTypeId(), isDimensionScale(), readAll(), setDimensionScale(), setDimensionScaleAxisLabel(), valid(), and writeAllInner().
_setTableSelf()
virtual void icedb::Tables::Table::_setTableSelf (std::shared_ptr< H5::DataSet > obj) protected pure virtual
Associates the icedb table with the fundamental HDF5 DataSet. Only used internally.
Implemented in icedb::Tables::Table_impl.
attachDimensionScale()
void icedb::Tables::Table::attachDimensionScale (size_t DimensionNumber, gsl::not_null< const Table *> scale)
Attaches a dimension scale to a table.
See also
the HDF5 HL dimension scale API docs, at https://support.hdfgroup.org/HDF5/doc/HL/RM_H5DS.html Attach a dimension scale to this table.
Definition at line 29 of file Tables.cpp.
References _getTableSelf(), getNumDimensions(), and valid().
{
             Expects(valid());
             Expects(scale->valid());
             Expects(DimensionNumber < getNumDimensions());
             auto selfptr = _getTableSelf();
             auto tblscaleptr = scale->_getTableSelf();
             const herr_t res = H5DSattach_scale(selfptr->getId(), tblscaleptr->getId(), static_cast<unsigned int>(DimensionNumber));
             assert(res == 0);
         }
detachDimensionScale()
void icedb::Tables::Table::detachDimensionScale (size_t DimensionNumber, gsl::not_null< const Table *> scale)
Detaches a dimension scale from this table.
Definition at line 39 of file Tables.cpp.
References _getTableSelf(), getNumDimensions(), and valid().
{
             Expects(valid());
             Expects(scale->valid());
             Expects(DimensionNumber < getNumDimensions());
             auto selfptr = _getTableSelf();
             auto tblscaleptr = scale->_getTableSelf();
             const herr_t res = H5DSdetach_scale(selfptr->getId(), tblscaleptr->getId(), static_cast<unsigned int>(DimensionNumber));
             assert(res == 0);
         }
getDimensions()
Table::Dimensions_Type icedb::Tables::Table::getDimensions () const
Returns a vector containing the dimensions of the table.
Definition at line 21 of file Tables.cpp.
References _getTableSelf(), icedb::fs::hdf5::readDatasetDimensions(), and valid().
Referenced by writeAllInner().
{
             Expects(valid());
             auto ptr = _getTableSelf();
             Table::Dimensions_Type dims;
             fs::hdf5::readDatasetDimensions(ptr.get(), dims);
             return dims;
         }
getDimensionScaleAxisLabel()
std::string icedb::Tables::Table::getDimensionScaleAxisLabel (size_t DimensionNumber) const
Get the axis label for the dimension designated by DimensionNumber.
Definition at line 122 of file Tables.cpp.
References _getTableSelf(), getNumDimensions(), and valid().
{
             Expects(valid());
             Expects(DimensionNumber < getNumDimensions());
             auto selfptr = _getTableSelf();
             constexpr size_t max_label_size = 1000;
             std::array<char, max_label_size> label;
             label.fill('\0');
             const ssize_t res = H5DSget_label(selfptr->getId(), static_cast<unsigned int>(DimensionNumber), label.data(), max_label_size);
             // res is the size of the label. The HDF5 documentation does not include whether the label is null-terminated,
             // so I am terminating it manually.
             label[max_label_size - 1] = '\0';
             return std::string(label.data());
         }
getDimensionScaleName()
std::string icedb::Tables::Table::getDimensionScaleName () const
Get the name of this table's defined dimension scale.
Definition at line 136 of file Tables.cpp.
References _getTableSelf(), and valid().
{
             Expects(valid());
             auto selfptr = _getTableSelf();
             constexpr size_t max_label_size = 1000;
             std::array<char, max_label_size> label;
             label.fill('\0');
             const ssize_t res = H5DSget_scale_name(selfptr->getId(), label.data(), max_label_size);
             // res is the size of the label. The HDF5 documentation does not include whether the label is null-terminated,
             // so I am terminating it manually.
             label[max_label_size - 1] = '\0';
             return std::string(label.data());
         }
getNumDimensions()
size_t icedb::Tables::Table::getNumDimensions () const
Returns the number of dimensions of a table.
Todo:
Need to ensure that tables have dimension scales attached in all cases. Required for netCDF compatibility.
Definition at line 15 of file Tables.cpp.
References _getTableSelf(), icedb::fs::hdf5::readDatasetNumDimensions(), and valid().
Referenced by attachDimensionScale(), detachDimensionScale(), getDimensionScaleAxisLabel(), and setDimensionScaleAxisLabel().
{
             Expects(valid());
             auto ptr = _getTableSelf();
             return fs::hdf5::readDatasetNumDimensions(ptr.get());
         }
getTableTypeId()
std::type_index icedb::Tables::Table::getTableTypeId () const
Get the type of the table (i.e. int64_t, float, etc.)
Definition at line 149 of file Tables.cpp.
References _getTableSelf(), and valid().
{
             Expects(valid());
             auto selfptr = _getTableSelf();
             if (fs::hdf5::isType<uint64_t, H5::DataSet>(selfptr.get())) return (typeid(uint64_t));
             if (fs::hdf5::isType<int64_t, H5::DataSet>(selfptr.get())) return (typeid(int64_t));
             if (fs::hdf5::isType<uint32_t, H5::DataSet>(selfptr.get())) return (typeid(uint32_t));
             if (fs::hdf5::isType<int32_t, H5::DataSet>(selfptr.get())) return (typeid(int32_t));
             if (fs::hdf5::isType<uint16_t, H5::DataSet>(selfptr.get())) return (typeid(uint16_t));
             if (fs::hdf5::isType<int16_t, H5::DataSet>(selfptr.get())) return (typeid(int16_t));
             if (fs::hdf5::isType<uint8_t, H5::DataSet>(selfptr.get())) return (typeid(uint8_t));
             if (fs::hdf5::isType<int8_t, H5::DataSet>(selfptr.get())) return (typeid(int8_t));
             if (fs::hdf5::isType<double, H5::DataSet>(selfptr.get())) return (typeid(double));
             if (fs::hdf5::isType<float, H5::DataSet>(selfptr.get())) return (typeid(float));
             if (fs::hdf5::isType<char, H5::DataSet>(selfptr.get())) return (typeid(char));
             if (fs::hdf5::isType<std::string, H5::DataSet>(selfptr.get())) return (typeid(std::string));
             throw;
         }
isDimensionScale()
bool icedb::Tables::Table::isDimensionScale () const
Is this Table used as a dimension scale?
Definition at line 97 of file Tables.cpp.
References _getTableSelf(), and valid().
Referenced by setDimensionScale().
{
             Expects(valid());
             auto selfptr = _getTableSelf();
             const htri_t res = H5DSis_scale(selfptr->getId());
             assert(res >= 0);
             if (res > 0) return true;
             return false;
         }
isTableOfType()
template<class Type > bool icedb::Tables::Table::isTableOfType () const inline
Check if this table has the matching Type.
Definition at line 68 of file Table.hpp.
{
                 std::type_index atype = getTableTypeId();
                 if (atype == typeid(Type)) return true;
                 return false;
             }
readAll()
template<class DataType > void icedb::Tables::Table::readAll (std::vector< size_t > & dims, std::vector< DataType > & data) const
Read all of the data in the associated table.
Parameters
DataType is the type of data.
Exceptions
if the DataType is mismatched (see isTableOfType and getTableTypeId).
Parameters
dims is an output parameter representing the size of each of the table's dimensions
data is an output parameter that stores the table's data.
Note
This convenience function uses a std::vector to store the output. This uses dynamic memory.
Definition at line 180 of file Tables.cpp.
References _getTableSelf(), icedb::fs::hdf5::readDatasetDimensions(), and valid().
         {
             Expects(valid());
             auto selfptr = _getTableSelf();
             fs::hdf5::readDatasetDimensions(selfptr.get(), dims);
             size_t sz = 1;
             for (const auto &s : dims) sz *= s;
             data.resize(sz);
             pullData<DataType, H5::DataSet>(dims, data, selfptr.get());
         }
setDimensionScale()
void icedb::Tables::Table::setDimensionScale (const std::string & dimensionScaleName)
Designate this table as a dimension scale.
Definition at line 106 of file Tables.cpp.
References _getTableSelf(), isDimensionScale(), and valid().
Referenced by icedb::Shapes::Shape::createShape().
{
             Expects(valid());
             Expects(!isDimensionScale());
             auto selfptr = _getTableSelf();
             const htri_t res = H5DSset_scale(selfptr->getId(), dimensionScaleName.c_str());
             assert(res == 0);
         }
setDimensionScaleAxisLabel()
void icedb::Tables::Table::setDimensionScaleAxisLabel (size_t DimensionNumber, const std::string & label)
Set the axis label for the dimension designated by DimensionNumber.
Definition at line 114 of file Tables.cpp.
References _getTableSelf(), getNumDimensions(), and valid().
{
             Expects(valid());
             Expects(DimensionNumber < getNumDimensions());
             auto selfptr = _getTableSelf();
             const htri_t res = H5DSset_label(selfptr->getId(), static_cast<unsigned int>(DimensionNumber), label.c_str());
             assert(res == 0);
         }
valid()
bool icedb::Tables::Table::valid () const protected
Checks that Table is well-formed during runtime. Only used internally.
Definition at line 13 of file Tables.cpp.
References _getTableSelf().
Referenced by icedb::Tables::CanHaveTables::_createTable(), attachDimensionScale(), detachDimensionScale(), getDimensions(), getDimensionScaleAxisLabel(), getDimensionScaleName(), getNumDimensions(), icedb::Tables::CanHaveTables::getTableNames(), getTableTypeId(), isDimensionScale(), icedb::Tables::CanHaveTables::openTable(), readAll(), setDimensionScale(), setDimensionScaleAxisLabel(), icedb::Tables::CanHaveTables::unlinkTable(), and writeAllInner().
 { if (_getTableSelf()) return true; return false; }
writeAll() [1/3]
template<class DataType > void icedb::Tables::Table::writeAll (const gsl::span< const DataType > & outData) const inline
Write the passed data to the table. Writes whole table.
Parameters
DataType is the type of the data.
Exceptions
if the DataType does not match the fundamental type of the table.
Parameters
outData is the data to be written to the table.
Exceptions
if outData's size does not match the table's size.
Definition at line 100 of file Table.hpp.
Referenced by icedb::Shapes::Shape::createShape().
{
                 static_assert(icedb::Data_Types::Is_Valid_Data_Type<DataType>() == true,
                     "Data to be written must be a valid data type");
                 this->template writeAllInner<DataType>(outData);
             }
writeAll() [2/3]
template<class DataType > void icedb::Tables::Table::writeAll (const gsl::span< DataType > & outData) const inline
Write the passed data to the table. Writes whole table.
Parameters
DataType is the type of the data.
Exceptions
if the DataType does not match the fundamental type of the table.
Parameters
outData is the data to be written to the table.
Exceptions
if outData's size does not match the table's size.
Definition at line 111 of file Table.hpp.
{
                 this->template writeAll<DataType>(gsl::span<const DataType>(outData.cbegin(), outData.cend()));
             }
writeAll() [3/3]
template<class DataType > void icedb::Tables::Table::writeAll (const std::vector< DataType > & outData) const inline
Write the passed data to the table. Writes whole table. Convenience converter function.
Parameters
DataType is the type of the data.
Exceptions
if the DataType does not match the fundamental type of the table.
Parameters
outData is the data to be written to the table.
Exceptions
if outData's size does not match the table's size.
Definition at line 120 of file Table.hpp.
{
                 this->template writeAll<DataType>(gsl::span<const DataType>(outData.data(), outData.size()));
             }
writeAllInner()
template<class DataType > void icedb::Tables::Table::writeAllInner (const gsl::span< const DataType > & outData) const private
Definition at line 221 of file Tables.cpp.
References _getTableSelf(), getDimensions(), and valid().
{
             Expects(valid());
             Expects(isTableOfType<DataType>());
             auto selfptr = _getTableSelf();
             const auto dimensionality = getDimensions();
             size_t sz = 1;
             for (const auto &d : dimensionality) sz *= d;
             Expects(outData.size() == sz);
             icedb::fs::hdf5::writeDatasetArray<DataType, H5::DataSet>(dimensionality, selfptr.get(), outData.data());
         }
Friends And Related Function Documentation
CanHaveTables
friend class CanHaveTables friend
Definition at line 17 of file Table.hpp.
Member Data Documentation
name
const std::string icedb::Tables::Table::name
The name of the Table.
Definition at line 31 of file Table.hpp.
The documentation for this class was generated from the following files:
lib/icedb/Table.hpp
lib/src/Tables.cpp