icedb: scatdb::registry Namespace Reference
scatdb::registry Namespace Reference
Functions
template<>
std::shared_ptr< IOhandler > write_file_type_multi<::scatdb::shape::shapeIO > (std::shared_ptr< IOhandler > sh, std::shared_ptr< options > opts, const std::shared_ptr< const ::scatdb::shape::shapeIO > s)
template<>
std::shared_ptr< IOhandler > read_file_type_multi<::scatdb::shape::shapeIO > (std::shared_ptr< IOhandler > sh, std::shared_ptr< options > opts, std::shared_ptr<::scatdb::shape::shapeIO > s)
Function Documentation
read_file_type_multi<::scatdb::shape::shapeIO >()
template<> std::shared_ptr<IOhandler> scatdb::registry::read_file_type_multi<::scatdb::shape::shapeIO > (std::shared_ptr< IOhandler > sh, std::shared_ptr< options > opts, std::shared_ptr<::scatdb::shape::shapeIO > s)
Definition at line 162 of file shapeIOtext.cpp.
References scatdb::plugins::builtin::shape::readDDSCAT().
         {
             IOtype iotype = opts->getVal<IOtype>("iotype", IOtype::READONLY);
             auto h = prepHandle<plugins::builtin::shape::shape_text_handle>
                 (sh, opts, std::string(plugins::builtin::shape::PLUGINID));
             s->shapes.clear();
             auto shp = ::scatdb::shape::shape::generate();
             if (!h->in) SDBR_throw(scatdb::error::error_types::xOtherError)
                 .add<std::string>("Reason", "Input stream not set. Wrong handle opening io type!");
             scatdb::plugins::builtin::shape::readDDSCAT(shp, *(h->in.get()), opts);
             s->shapes.push_back(shp);
             return h;
         }
write_file_type_multi<::scatdb::shape::shapeIO >()
template<> std::shared_ptr<IOhandler> scatdb::registry::write_file_type_multi<::scatdb::shape::shapeIO > (std::shared_ptr< IOhandler > sh, std::shared_ptr< options > opts, const std::shared_ptr< const ::scatdb::shape::shapeIO > s)
Todo:
If no exporttype, attempt to guess from the file extension?
Definition at line 145 of file shapeIOtext.cpp.
References scatdb::plugins::builtin::shape::export_ddscat(), and scatdb::plugins::builtin::shape::export_raw().
         {
             std::string exporttype = opts->exportType();
             if (exporttype == "raw") return plugins::builtin::shape::export_raw(sh, opts, s);
             else if (exporttype == "ddscat" || !exporttype.size()) return plugins::builtin::shape::export_ddscat(sh, opts, s);
             //else if (exporttype == "adda") return plugins::builtin::shape::export_adda(sh, opts, s);
             else SDBR_throw(scatdb::error::error_types::xUnimplementedFunction)
                 .add<std::string>("Reason", "Attempting to write a shape to a file, but the format specifier is not understood.")
                 .add<std::string>("Format", exporttype);
             return nullptr;
         }